---
title: "Bivariate Modeling Assignment"
author: "your name here"
format: html
execute:
  echo: true
  warning: false
  message: false
---


```{r}
# put the code to load any necessary R libraries and read in your cleaned data here. Delete this text afterward.
```


# (Q ~ B) Two sample T-Test for Independent Groups

1. **Identify response and explanatory variables**


2. **Visualize and summarise bivariate relationship** 


3. **Write the relationship you want to examine in the form of a research question.**

Let $\mu_{1}$ be the true mean ...
Let $\mu_{2}$ be the true mean ...

$H_{0}: \mu_{1} - \mu_{2} = 0$  
$H_{A}: \mu_{1} - \mu_{2} \neq 0$ 

4. **State and justify the analysis model. Check assumptions.**

5. **Conduct the test and make a decision about the plausibility of the alternative hypothesis.**
 

6. **Write a conclusion in context of the problem that includes a point estimate, confidence interval, and p-value.**


\newpage

# (Q ~ C) Analysis of Variance


1. **Identify response and explanatory variables**


2. **Visualize and summarise bivariate relationship** 


3. **Write the relationship you want to examine in the form of a research question using symbols and words.**

Let $\mu_{1}$ be the true mean ...
Let $\mu_{2}$ be the true mean ...
Let $\mu_{3}$ be the true mean ...


$H_{0}: \mu_{1} = \mu_{2} =  ...$   

$H_{A}:$ At least one group mean ...  


4. **State and justify the analysis model. Check assumptions.**


5. **Conduct the test and make a decision about the plausibility of the alternative hypothesis.**
 

6. **Write a conclusion in context of the problem that includes a point estimate, confidence interval, and p-value.**


\newpage 
 
# (B ~ C) Chi-Square test of Association

1. **Identify response and explanatory variables**


2. **Visualize and summarise bivariate relationship** 


3. **Write the relationship you want to examine in the form of a research question using symbols and words.**

Let $p_{i}$ be the true ...


$H_{0}: p_{1} = p_{2} = ...$   

$H_{A}:$ At least ... 

  
4. **State and justify the analysis model. Check assumptions.**

5. **Conduct the test and make a decision about the plausibility of the alternative hypothesis.**
 

6. **Write a conclusion in context of the problem that includes a point estimate, confidence interval, and p-value.**


\newpage
 
# (Q ~ Q) Correlation Analysis



1. **Identify response and explanatory variables**


2. **Visualize and summarise bivariate relationship** 


3. **Write the relationship you want to examine in the form of a research question using symbols and words.**

Let $\rho$ be the true ... 


$H_{0}: \rho = 0$  

$H_{A}: \rho \neq 0$   

4. **State and justify the analysis model. Check assumptions.**

5. **Conduct the test and make a decision about the plausibility of the alternative hypothesis.**
 

6. **Write a conclusion in context of the problem that includes a point estimate, confidence interval, and p-value.**
