---
title: "Moderation Assignment"
author: "your name here"
execute:
  echo: true
  warning: false
  message: false
---


```{r}
# put the code to load any necessary R libraries and read in your cleaned data here. Delete this text afterward.
```

# ANOVA

1. **Identify response, explanatory, and moderating variables**

* Categorical explanatory variable = 
* Quantitative response variable = 
* Categorical Potential Moderator = 

2. **Visualize and summarise the potential effect of the moderator** 


3. **Write the relationship you want to examine in the form of a research question - including a statement about the modifier**

5
4. **Fit both the original, and stratified models.**


5. **Determine if the Third Variable is a moderator or not.**



---- 

# Chi-Squared Test of Equal Proportions

1. **Identify response, explanatory, and moderating variables**

* Categorical explanatory variable = 
* Categorical response variable = 
* Categorical Potential Moderator = 

2. **Visualize and summarise the potential effect of the moderator** 


3. **Write the relationship you want to examine in the form of a research question - including a statement about the modifier**


4. **Fit both the original, and stratified models.**


5. **Determine if the Third Variable is a moderator or not.**


---- 

# Linear Regression

1. **Identify response, explanatory, and moderating variables**

* Quantitative explanatory variable = 
* Quantitative response variable = 
* Categorical Potential Moderator = 

2. **Visualize and summarise the potential effect of the moderator** 


3. **Write the relationship you want to examine in the form of a research question - including a statement about the modifier**


4. **Fit both the original, and stratified models.**


5. **Determine if the Third Variable is a moderator or not.**


