{
  "hash": "3f735b673acfe015e485cac48b25307d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"HW 08: Fitting Simple Regression models\"\nsubtitle: \"Intro to regression\"\nexecute:\n  echo: true\n  warning: false\n  message: false\nformat: \n  html: \n    toc: false\n  pdf: default\n---\n\n\n\n\n# Purpose\n\nPractice fitting and interpreting the coefficients of a simple regression model. \n\n----\n\n# Submission instructions\n\n* No template this time! Use the structure structure of prior assignments as a guide to create your own nicely formatted report. \n* Upload your rendered **PDF** to Gradescope (Canvas) by the due date. \n\n\n::: {.callout-important}\nFor this assignment, I want you to show _both_ the raw R output of summary tables and regression results *and* a nice table using functions such as `kable`, `tbl_summary` and `tbl_regression`. \n:::\n\n----\n\n# Assignment Overview\n\nYou will only fit **1** model in this assignment, but you will follow the full 6 steps that you did in the last assignment. Read each step below carefully as the details for each step have slightly changed. \n\n1. Identify variables under consideration and state which variable will be your explanatory variable and which will be your response variable. \n    - Think about the relationship among your variables, which one do you think could _explain_ the other? \n    \n2. Create an appropriate bivariate plot to visualize the relationship you are exploring. \n    - Calculate appropriate summary statistics. \n    - Summarize the relationship between the explanatory and outcome variables in short paragraph form. \n\n3. Write the relationship you want to examine in the form of a research question using symbols and words.\n    - Define the slope parameter $\\beta_{1}$ being tested.\n    - Translate the null and alternative hypotheses into $H_{0}$ and $H_{A}$ with symbols. \n\n4. Fit the simple regression model using `lm(y~x)`\n    - Write a simple sentence on whether or not there is reason to believe that a relationship between x and y exists.\n\n5. Verify assumptions & assess model fit\n    - Assumption of linearity can be discussed using the plot you created earlier. \n    - Other assumptions are checked by examining the residuals using functions in the `performance` package\n    - :warning: Make sure all your plots can be seen! \n    - Even if these assumptions are potentially violated, for the purposes of this assignment, acknowledge this limitation and continue with the prescribed analysis. \n    \n6. Interpret ALL regression coefficients (including the intercept) in a sentence that includes a point estimate, confidence interval, and p-value. Also interpret $R^{2}$ the coefficient of determination. \n\n----\n\n\n## Example: Body mass and bill length of penguins\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(gtsummary)\nlibrary(performance)\npen <- palmerpenguins::penguins\n```\n:::\n\n\n\n\n### 1. Identify response and explanatory variables\n\n-   The quantitative explanatory variable is body mass (g) `body_mass_g`\n-   The quantitative response variable is bill length (mm) `bill_length_mm`\n\n### 2. Visualize and summarise bivariate relationship {.smaller}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(pen, aes(x=body_mass_g, y=bill_length_mm)) + \n  geom_point() + geom_smooth(col = \"blue\")\n```\n\n::: {.cell-output-display}\n![](hw08-slr_files/figure-pdf/unnamed-chunk-2-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\ncor(pen$body_mass_g, pen$bill_length_mm, use = \"pairwise.complete.obs\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5951098\n```\n\n\n:::\n:::\n\n\n\n\nThere is a strong, positive, mostly linear relationship between the body mass (g) of penguins and their bill length (mm) (r=.595).\n\n### 3. Write the relationship you want to examine\n\nLet $\\beta_1$ be the true slope parameter that describes the change in bill length of the penguin as body mass increases.\n\n-  $H_{0}: \\beta_{1}=0$ There is no linear relationship between body mass and bill length.\n-  $H_{A}: \\beta_{1} \\neq 0$ Alternate Hypothesis: There is a linear relationship between body mass and bill length.\n\n### 4. Fit the regression model\n\nDecide if there is evidence to believe that there is a relationship\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npen.body.bill <- lm(bill_length_mm ~ body_mass_g, data=pen)\npen.body.bill |> summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = bill_length_mm ~ body_mass_g, data = pen)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-10.1251  -3.0434  -0.8089   2.0711  16.1109 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 2.690e+01  1.269e+00   21.19   <2e-16 ***\nbody_mass_g 4.051e-03  2.967e-04   13.65   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.394 on 340 degrees of freedom\n  (2 observations deleted due to missingness)\nMultiple R-squared:  0.3542,\tAdjusted R-squared:  0.3523 \nF-statistic: 186.4 on 1 and 340 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\nThe p-value for $b_{1}$ is \\<.0001, so there is sufficient evidence to believe that there is a linear relationship between body mass and bill length.\n\n### 5. Verify assumptions & assess model fit\n\nIn the scatterplot, Both the outcome and predictor are continuous variables that have a visible linear relationship, and we assume the observations are independent.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_model(pen.body.bill) |> plot()\n```\n\n::: {.cell-output-display}\n![](hw08-slr_files/figure-pdf/unnamed-chunk-4-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n* The distribution of the residuals is mostly normal, pretty heavy right tail. This is indicative of a nonlinear trend somewhere in the data.\n* The variance of Y is **not** constant. This is a warning that our linear model does *not* fit the data well and we should look into possible refinements and improvements.\n* The observed distribution of bill length is bimodal, and so the model is overestimating some values and underestimating others. There is clearly some other *confounding* variable that predicts bill length better than just body mass.\n\n\n### 6. Write a conclusion in context of the problem. {.smaller}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npen.body.bill |> \n  tbl_regression(intercept=TRUE, \n                 # to increase the display digits\n                 estimate_fun = purrr::partial(style_ratio, digits = 3)) |>\n  add_glance_source_note(include = c(r.squared))\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.4pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lccc}\n\\toprule\n\\textbf{Characteristic} & \\textbf{Beta} & \\textbf{95\\% CI} & \\textbf{p-value} \\\\ \n\\midrule\\addlinespace[2.5pt]\n(Intercept) & 26.90 & 24.40, 29.40 & <0.001 \\\\ \nbody\\_mass\\_g & 0.004 & 0.003, 0.005 & <0.001 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\begin{minipage}{\\linewidth}\nAbbreviation: CI = Confidence Interval\\\\\nR² = 0.354\\\\\n\\end{minipage}\n\\end{table}\n\n:::\n:::\n\n\n\n\n* For a penguin who weighs 0 kg, the predicted bill length is 26.9 (24.4, 29.4)mm. This is an impossible situation.  \n* Each 1g increase in body mass of a penguin is associated with a significant increase of 0.004 (0.0035, 0.0046) mm of bill length (p\\<.0001). In more reasonable numbers, an increase of 1kg of body mass in a penguin corresponds to a 4(3.5, 4.6) mm increase in bill length. \n* Body mass explains 35.4% of the variation in bill length.\n\nHowever, model diagnostics indicate that a linear model may not be appropriate for this relationship. The assumption of constant variance is not upheld and there may be another variable that affects bill length.\n",
    "supporting": [
      "hw08-slr_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "\\usepackage{booktabs}\n\\usepackage{caption}\n\\usepackage{longtable}\n\\usepackage{colortbl}\n\\usepackage{array}\n\\usepackage{anyfontsize}\n\\usepackage{multirow}\n"
      ]
    },
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}