project:
  type: website
  output-dir: _site
  preview:
    port: 4200
    browser: true
    
website:
  page-navigation: true
  title: "Data Analysis for Graduate Research"
  description: "Homepage for MATH 615 Fall 22"
  site-url: "https://norcalbiostat.github.io/MATH615"
  
  repo-url: https://github.com/norcalbiostat/math615_test
  repo-actions: [edit, issue]
  twitter-card: 
    creator: "@norcalbiostat"
  
  page-footer:
    background: "#2e3846"
    left: "This site is built with :heart: and [Quarto](https://quarto.org/) by [Robin Donatello](www.norcalbiostat.com)."
    

  sidebar:
    pinned: true
    align: center
    style: "docked"
    search: true
    #    logo: "images/logo.gif"
    # tools:
    #  - icon: discord
    #    href: https://discord.gg/tzcB4MJadW
    #    text: Discord
    contents: 
      - index.qmd
      - syllabus.qmd
      - section: "Schedule"
        contents:
          - schedule.qmd
          - calendar.qmd
      - project.qmd
      - section: "Materials"
        contents:
          - topics.qmd
          - slides.qmd
          - hw.qmd
          - collab_notes.qmd
          - reading.qmd
      - help.qmd

from: markdown+emoji
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    highlight: tango
    toc: true
    code-copy: true
    code-overflow: scroll
    

execute:
  freeze: auto # re-render only when source changes
  echo: false
  warning: false
