project:
  type: website
  output-dir: _site
  preview:
    port: 4200
    browser: true
    
website:
  page-navigation: true
  title: "Data Analysis for Graduate Research"
  description: "Homepage for MATH 615"
  site-url: "https://norcalbiostat.github.io/MATH615"
  repo-url: https://github.com/norcalbiostat/MATH615
  repo-actions: [edit, issue]
  
  page-footer:
    #background: light
    left: "This site is built with 💚 and [Quarto](https://quarto.org/) by [Robin Donatello](www.norcalbiostat.com)."
    

  navbar: 
    pinned: true
    background: "#654378"
    left:
      - text: "Overview"
        file: modules.qmd
      - text: "All Materials"
        menu:
        - text: "Topics"
          file: topics.qmd
        - text: "Slides"
          file: slides.qmd
        - text: "Assignments"
          file: hw.qmd

      - text: "Research Project"
        menu:
        - text: "Overview and Information"
          file: project.qmd
        - text: "Guide for Authors"
          file: author_guide.qmd
        
    right: 
      - icon: google
        href: https://drive.google.com/drive/folders/1f9oKqswqB0wo1I957xFW6yjhIt2FRhwr
      - text: "Reference Texts"
        menu: 
          - text: "Applied Stats Notebook"
            href: https://norcalbiostat.github.io/AppliedStatistics_notes/
          - text: "Intro to Modern Stats"
            href: "https://openintro-ims.netlify.app/"
          - icon: google
      - syllabus.qmd
      - text: "Help"
        href: help.qmd

from: markdown+emoji
format:
  html:
    highlight-style: a11y
    theme: 
      light: flatly
      dark: darkly
    highlight: pygments
    toc: true
    code-copy: true
    code-overflow: scroll
    

execute:
  freeze: auto # re-render only when source changes
  echo: false
  warning: false
  message: false
