project:
  type: website

website:
  page-navigation: true
  title: "Data Analysis for Graduate Students"
  description: "Homepage for MATH 615 Fall 22"
  site-url: "https://norcalbiostat.github.io/MATH615"
  
  #repo-url: https://github.com/rstudio-conf-2022/teach-ds
  #repo-actions: [edit, issue]
  
 # page-footer:
 #    left: "This page is built with -heart- and [Quarto](https://quarto.org/)."
 #    right: "&copy; Copyright 2022, Robin Donatello"
 #    #background: "#2e3846"
 #     - icon: github
 #       href: https://github.com/norcalbiostat
 #     - icon: twitter
 #       href: https://twitter.com/norcalbiostat


  sidebar:
    pinned: true
    align: center
    style: "docked"
    search: true
    #    logo: "images/logo.gif"
    # tools:
    #   - icon: github
    #     href: https://github.com/norcalbiostat
    #     text: GitHub
    contents: 
      - index.qmd
      - section: "Schedule"
        contents:
          - schedule.qmd
          - calendar.qmd
      - section: "Materials"
        contents:
          - topics.qmd
          - slides.qmd
          - hw.qmd
          - collab_notes.qmd
          - reading.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    highlight: tango
    toc: true
    code-copy: true
    code-overflow: scroll

execute:
  #freeze: auto
  echo: false
  warning: false
