---
title: "Data Analysis for Graduate Research"
subtitle: |
  MATH 615 • Fall 2022 <br> Formerly known as Statistical Methods for Graduate Research.<br> California State University, Chico
toc: false
sidebar: false
page-layout: full
---


:::{.callout-important}
# Site in progress
This site is currently being revised for the Fall 22 semester.
:::

## Course Information

This course provides a hands-on introduction to using data to rigorously answer research questions. Students practice cleaning and manipulating data, creating data visualizations, and conducting introductory level statistical analysis using real-world data sets that are relevant to their field. Analysis topics include single and two-sample inference, analysis of variance, multiple regression, analysis of co-variance, experimental design, repeated measures, nonparametric procedures, and categorical data analysis. Reproducible research is strongly emphasized through the use of statistical computing software (e.g. SPSS, Stata, SAS, R, Python). Recommended for all majors that use data for research.

::: {.grid .course-details}


::: {.g-col-4}
### Course details

{{< fa calendar >}} &nbsp; {{< var course.days >}}
{{< fa clock >}} &nbsp; {{< var course.time >}}
{{< fa location-dot >}} &nbsp; {{< var course.location >}}
{{< fa people-roof >}} &nbsp; {{< var course.moi >}}
:::


::: {.g-col-4}
#### Pre-reqs
{{< var course.pre_req >}}

#### Student Drop in Hours
{{< var course.oh >}}

:::



::: {.g-col-4}
### Instructor

{{< fa user >}} &nbsp; [{{< var instructor.name >}}]({{< var instructor.url >}})
{{< fa university >}} &nbsp; {{< var instructor.office >}}
{{< fa envelope >}} &nbsp; <a href="mailto:{{< var instructor.email >}}">{{< var instructor.email >}}</a>  
{{< fa brands twitter >}} &nbsp; [{{< var instructor.twitter >}}](https://www.twitter.com/{{< var instructor.twitter >}})  
{{< fa calendar-check >}} &nbsp; [Schedule an appointment]({{< var instructor.appointment_url >}})
:::

:::


:::{.callout-tip}
You can toggle dark mode by clicking the {{< fa toggle-off >}} button in the top right navigation bar.
:::