---
title: "Class Overview"
execute: 
  echo: false
  message: false
  warning: false
format: 
  html: 
    toc: false
---


```{r}
library(tidyverse)
library(kableExtra)
options(knitr.table.format = "html", knitr.kable.NA = '') 

# Import data
mod <- googlesheets4::read_sheet("19EBk4rX0bS2a0eYZPxdpEGs18lnwu02hxukFfB3-TNc", 
                                 sheet="module_overview", 
                                 col_types = c("nncccccccc"))  %>% 
  mutate(across(-Order, ~str_replace_all(., "\\[([^\\]]+)\\]\\(([^)]+)\\)", '<a href="\\2\">\\1</a>')), 
         Reading = gsub("\\n", "<br>", Reading))
```

#### ⚠️ Details are subject to change. See Canvas for due dates. 

_Last Updated: `r format(Sys.time(), "%a %b %d %X")`_ 

```{r}
# content rows
content  <- mod %>% filter(is.na(tnum))

# topic info
headers  <- mod %>% filter(!is.na(tnum))

# create topic number index
tn <- headers %>% 
        select(tnum, Topic) %>%
        mutate(start=0, end=0)

for(t in 0:max(as.numeric(tn$tnum))){
  tn$start[t+1] <- min(which(content$Order %/% 1 ==t))
  tn$end[t+1]   <- max(which(content$Order %/% 1==t))
}

out <- content %>% 
  select(Topic, Reading, Video, Slides, Activities, Assess) 

# highlight rows
now.col <-  "background-color: #557ef6; color: #fff;"
notnow.col <-  "background-color: #445179; color: #fff;"
```


```{r}
out %>% 
  kbl(align = "lcccccc", format = "html", escape=FALSE) %>%
  kable_styling(bootstrap_options = c("hover", "striped", "responsive", "bordered")) %>% 
  pack_rows(tn$Topic[1], tn$start[1],   tn$end[1], label_row_css =notnow.col) %>% 
  pack_rows(tn$Topic[2], tn$start[2],   tn$end[2], label_row_css =notnow.col) %>%
  pack_rows(tn$Topic[3], tn$start[3],   tn$end[3], label_row_css =notnow.col) %>%
  pack_rows(tn$Topic[4], tn$start[4],   tn$end[4], label_row_css =notnow.col) %>%
  pack_rows(tn$Topic[5], tn$start[5],   tn$end[5], label_row_css =notnow.col) %>%
  pack_rows(tn$Topic[6], tn$start[6],   tn$end[6], label_row_css =notnow.col) %>%
  pack_rows(tn$Topic[7], tn$start[7],   tn$end[7], label_row_css =notnow.col) %>%
  pack_rows(tn$Topic[8], tn$start[8],   tn$end[8], label_row_css =notnow.col) %>%
  pack_rows(tn$Topic[9], tn$start[9],   tn$end[9], label_row_css =notnow.col) %>%
  pack_rows(tn$Topic[10], tn$start[10], tn$end[10], label_row_css =now.col) %>%
  pack_rows(tn$Topic[11], tn$start[11], tn$end[11], label_row_css =notnow.col) %>%
  column_spec(1, width = "25%") %>%
  column_spec(2, width = "20%") %>%
  column_spec(3, width = "0.4in") %>%
  column_spec(4, width = "5%") %>% 
  column_spec(5, width = "5%") %>%
  column_spec(6, width_min = "1.3in") 
```
