---
title: "Welcome to MATH 615"
subtitle: "Data Analysis for Graduate Research"
date: "2022-08-22"
description: "1"
author: "Robin Donatello"
footer: "[🔗 https://norcalbiostat.github.io/MATH615](https://norcalbiostat.github.io/MATH615/) / Hello Math 615 Fall 22 cohort"
format: 
  revealjs:
    theme: beige
#    theme: ../slides.scss
    multiplex: true
    transition: fade
    slide-number: true
    incremental: false 
    chalkboard: true
execute:
  freeze: auto
  echo: true
knitr:
  opts_chunk: 
    R.options:
      width: 200
---

# Meet your instructor {background-image="../images/Zombatar.jpg" background-size="200px" background-position="45% 25%"}

## Dr. Robin Donatello (she/her) {.smaller}

You can address me as "Robin", "Dr. D", or some other respectful title.

I have a Doctorate in Public Health (DrPH) Biostatistics from UCLA, but I'm a Chico alum. I double majored in Statistics & Biology, with minor in Chemistry, and a first generation college student who started at Butte College.

My campus life consists of training the next generation of Scientists how to harness the power of Statistics and Data in a responsible and ethical manner, leading the Data Science Initiative (DSI) provide training and experiences for students and faculty, and providing analytical support and statistical consulting for many projects on and off campus.

When I'm not on campus, typically I'm growing food for my family, out adventuring with my dogs, or getting some game time in. You can learn more about the projects i'm involved in on my [website](http://www.norcalbiostat.com/).

## Your turn

* Turn to your neighbor and introduce yourself. 
* You'll post an introduction in Discord this week so everyone will get to know everyone else. 

# Code of Conduct

## Everyone is welcome here

It is my intent that students from all diverse backgrounds and perspectives be well-served by this course, that students' learning needs be addressed both in and out of class, and that the diversity that the students bring to this class be viewed as a resource, strength and benefit. 

It is my intent to present materials and activities that are respectful of diversity: gender identity, sexuality, disability, age, socioeconomic status, ethnicity, race, nationality, religion, and culture. 

## Supportive Learning Environment

I would like to create a learning environment that supports a diversity of thoughts, perspectives and experiences, and honors your identities (including race, gender, class, sexuality, religion, ability, etc.) 

## To help accomplish this:

* Let me know if you have a name and/or set of pronouns that differ from those that appear in your official Chico records. 
* Help me pronounce your name as accurately as possible. Corrections are welcome. 
* If you feel like your performance in the class is being impacted by your experiences outside of class, please don't hesitate to come and talk with me. I want to be a resource for you.

# What is this class about? 

## Learning goals {.smaller}

::: incremental
-   Developing the skills to conduct statistically valid and reproducible research.
-   Understanding how data needs to be structured and formatted for analysis, so you can better prepare data collection methods for future research.
-   Practicing the skills to be the boss of your own data without relying on others to "run the numbers" for you.
-   Learning basic statistical techniques for a small selection of analysis situations.
-   Learning how to do all of this in a reproducible manner to save you headache and time during your research.
-   Laying the statistical foundation so you can learn to apply more advanced statistical models as needed, such as those covered in Applied Statistics II (Math 456).

See the [syllabus](../syllabus.html) for more detailed learning objectives.
:::

# How are we going to accomplish all that? 

## Lots of course materials and tools

* I don't sanitize this class for you by keeping everything in a learning management system like Blackboard or Canvas. 

* In a working environment you have to deal with multiple platforms, multiple accounts and manage multiple locations for files and content. I use the best tools for the job.

* Homework 0 provides a checklist for getting connected and testing out your tools.

## Class website

<div style="text-align:center"> https://math615.netlify.app/

-   Bookmark this page. You will be here a lot.
-   Contains details on weekly topics, due dates, links to notes, assignments and additional materials
-   Sometimes links will be broken. Typo's happen. Notify me via Discord and I'll get to it asap.

## Textbook

-   The textbook is used for reading and learning content at a more in depth level than my overview slides.
-   This will be used in Math 456, and is an excellent reference guide.
-   If you're curious, I get about 1% of the sale in royalty. The income is *not* why I collaborated on this edition. I used the 4th edition in grad school and really like teaching out of it.

## Blackboard Learn (BBL)

-   Used for recording grades via grading rubric.

## Google Drive

-   Assignments will be turned in and peer reviewed through Google Drive.
-   You have been added to the Math 615 Google drive using your campus email.

## Discord

-   Used for outside class discussions, meme sharing, homework help and general chatter.
-   I will not answer most class-content based questions through email.
-   Download either the phone app or the desktop app (I use both). This is mandatory.
    -   Do not rely on remembering to log in via the web browser. You will miss important notifications.

## Lecture notes (slides)

* Stand alone lecture notes like these.
* Click on three lines in the bottom right to see options for exporting a copy
* Collaborative lecture notes on Hack MD (more info below) 

## Video

* Sometimes I will record lectures and want you to watch them before class. 
* This frees up in class time for actively working on homework or your project with your peers

## Hack MD

-   Interactive collaborative notes
-   No account needed to view, but account needed for editing (which you will be doing)

## Poll Everywhere

-   web-based student response system.
-   During class I will display an activity on-screen and you respond on your device (computer or mobile).
-   I have already registered you for my class
-   Use your student email to log in and use the password reset link to create a new password. Let me know if you can't get registered.

# What does this look like in practice?

## Suggested schedule for student success {.smaller}

::: incremental
-   Sunday you check the course calendar to note important upcoming due dates and to plan accordingly.
-   Before Monday class you do some reading/watching on the topic for the week. 
-   Monday class: \~25 min lecture/discussion, \~50 min actively working on assignments
-   Before Wednesday class you complete the assigned reading and videos, review the assignment rubric. 
-   Wednesday class: \~10 minute topic quiz, \~25 min lecture/discussion, \~50 min actively working on assignments
-   Before Thursday EOD you submit your draft assignment to Google drive.
-   Between Friday & Saturday noon you provide feedback on 1-2 of your classmates assignments and finish your own assignment. 
-   By EOD Sunday you revise your assignment based on your peer's feedback and submit your final assignment for grading

:::

<div style="text-align:right">  EOD: End of day, or 11:59pm.

## Time Commitment 

* Expect to spend 10-12 hours each week on this class. 
* I will do my best not to move due dates so you can plan accordingly.

# Research Project

## Project Overview

-   Semester long project
-   Individual projects with peer review collaboration
-   All assignments are designed to support your research.
-   Must choose a project out of select data sets.
    -   Individual research is typically not developed or robust enough to be demonstrative.
-   Project will culminate with the creation and presentation of a research poster.
-   More details are on the [project](project.html) page.

# Data Analysis Software

## Welcome to modern Statistics & Data Analysis {.smaller}

::: incremental
* No more TI-83, modern statistics is computational based. 
    - And I don't mean Excel.
* Big push for open research in the Natural and Social Sciences.
    - Sharing code & data. Sometimes required along with manuscript for publishing.
-   Reproducibility. Give someone else access to your data and code, and they can replicate your findings.
    - We will practice this in this class.
    - This course website is an example (link in footer)
-   I'm not the only one [teaching reproducible research](http://benmarwick.github.io/UW-eScience-reproducibility-social-sciences/#/).
-   Expect to bring your laptop every day to class.
    -   The more reading and content engagement done outside of class, the more time for in class analysis and discussion
:::


## Software program of choice (SPC) {.smaller}

::: incremental

* This class is not a class on how to use the software program. 
* You will be responsible for learning a lot of the programming language outside of class on your own time.
    - Part of a MS program is learning how to learn.
* The help page on the website has a section on programming resources.
* All my lecture notes use R with some examples in SPSS. 
* I will not dictate which software program you use in this class. 
* I will expect you to submit reproducible code. 
    - You can point and click your way to an answer, but code must be saved and reusable with minimal changes.
:::

## Software cont. {.smaller}

::: incremental

* Be open to new things, there is power in being polyglottal. You can use one language in here and another language for another class or project.
* Your professors in your other classes, or your masters committee may want you to learn a specific language. So should your industry. 
* Don't make assumptions, look at job postings and see what they want.
    - E.g. Center for Healthy Communities has a lot of Nutrition faculty/students who typically use SPSS, but the Research & Evaluation Team is solidly using R.
* Political Science & Economics often use Stata. I've met Sociologists that use SAS, Stata, R and SPSS.
* I am fluent in SAS, STATA and R, reasonably read in SPSS but can provide limited support for Python.
-   I highly recommend making a habit to attend [Community Coding](https://www.csuchico.edu/datascience/community-coding.shtml) even if it's just to sit and do your work with your classmates in a supportive environment. 
:::

## Questions? 