---
title: "Welcome to MATH 615"
subtitle: "Data Analysis for Graduate Research"
date: "2024-08-26"
author: "Robin Donatello"
footer: "[🔗 https://math615.netlify.app](https://math615.netlify.app) / Hello Math 615 Fall 24 cohort"
format: 
  revealjs:
    theme: sky
#    theme: ../slides.scss
    transition: fade
    slide-number: true
    incremental: false 
    chalkboard: true
execute:
  freeze: auto
  echo: true
knitr:
  opts_chunk: 
    R.options:
      width: 200
---

# Meet your instructor {background-image="../images/Zombatar.jpg" background-size="200px" background-position="45% 25%"}

## Dr. Robin Donatello (she/her) {.smaller}

You can address me as "Robin", "Dr. D", or some other respectful title.

I have a Doctorate in Public Health (DrPH) Biostatistics from UCLA, but I'm a Chico alum. I double majored in Statistics & Biology, with minor in Chemistry, and a first generation college student who started at Butte College.

My campus life consists of training the next generation of Scientists how to harness the power of Statistics and Data in a responsible and ethical manner, leading the Data Science Initiative (DSI) provide training and experiences for students and faculty, and providing analytical support and statistical consulting for many projects on and off campus.

When I'm not on campus, typically I'm growing food for my family, out adventuring with my dogs, or getting some game time in. You can learn more about the projects i'm involved in on my [website](http://www.norcalbiostat.com/).

## Your turn

-   Turn to your neighbor and introduce yourself.
-   You'll post an introduction in Discord this week so everyone will get to know everyone else.

# Code of Conduct

## Everyone is welcome here

It is my intent that students from all diverse backgrounds and perspectives be well-served by this course, that students' learning needs be addressed both in and out of class, and that the diversity that the students bring to this class be viewed as a resource, strength and benefit.

It is my intent to present materials and activities that are respectful of diversity: gender identity, sexuality, disability, age, socioeconomic status, ethnicity, race, nationality, religion, and culture.

## Supportive Learning Environment

I would like to create a learning environment that supports a diversity of thoughts, perspectives and experiences, and honors your identities (including race, gender, class, sexuality, religion, ability, etc.)

## To help accomplish this:

-   Let me know if you have a name and/or set of pronouns that differ from those that appear in your official Chico records.
-   Help me pronounce your name as accurately as possible. Corrections are welcome.
-   If you feel like your performance in the class is being impacted by your experiences outside of class, please don't hesitate to come and talk with me. I want to be a resource for you.

# What is this class about?

## Learning goals {.smaller}

::: incremental
-   Developing the skills to conduct statistically valid and reproducible research.
-   Understanding how data needs to be structured and formatted for analysis, so you can better prepare data collection methods for future research.
-   Practicing the skills to be the boss of your own data without relying on others to "run the numbers" for you.
-   Learning basic statistical techniques for a small selection of analysis situations.
-   Learning how to do all of this in a reproducible manner to save you headache and time during your research.
-   Laying the statistical foundation so you can learn to apply more advanced statistical models as needed, such as those covered in Applied Statistics II (Math 456).

See the [syllabus](../syllabus.html) for more detailed learning objectives.
:::

# How are we going to accomplish all that?

## Lots of course materials and tools

-   I don't sanitize this class for you by keeping everything in a learning management system like Canvas.

-   In a working environment you have to deal with multiple platforms, multiple accounts and manage multiple locations for files and content. I use the best tools for the job.

-  Homework 0 provides a checklist for getting connected and testing out your tools.

- Video also that goes over the details of each tool to not take up class time.  

# Research Project

## Project Overview

-   Semester long project
-   Co-authored research project with regular peer review
-   All regular assignments are designed to support your research.
-   Your choice (within guidelines) of research topic and data set.
-   End goal is a research poster presentation and research brief.



# Policies

## Mode of Instruction / Attendance

-   This is an in person class. Attendance is expected
-   This is a graduate class and you all are adults with lives outside this class.
-   Each class session will be live streamed, with the recording posted to Canvas within a few days.
-   Common reasons to join the class virtually:
    -   you're sick
    -   you're out of town on field work


## Collaboration & Plagerism {.smaller}

Collaboration on assignments is encouraged. People learn better when they have someone else to talk through concepts and debugging with. However your submitted work must represent **your personal effort** on all parts. 

-   Collaboration on exams and individual quizzes is not allowed.
-   You can use ChatGPT/AI tools **to help you learn**, but you must disclose when you do.
-   Your work must be your own. 

See the syllabus for details on acceptable uses of collaboration.

## Time Commitment

-   Expect to spend 10-12 hours each week on this class.
    -   Note that this is 1-2 hours more than an undergraduate 3 unit course would take (9 hrs). This is to acknowledge that it may take you longer than expected to complete the work until you gain practice coding.
-   I will do my best not to move due dates so you can plan accordingly.
-   Use the calendar in Canvas


## Syllabus

This overview is not a replacement for reading the syllabus. That document contains more information on policies and procedures that you need to be aware of. You can access an HTML version on the course website in the navigation bar, and a PDF version from inside Canvas.

# Questions?
