---
title: "Formulating research questions"
date: "2024-09-04"
footer: "[🔗 https://math615.netlify.app](https://math615.netlify.app) / Formulating research questions "
from: markdown+emoji
format: 
  revealjs:
    theme: sky
    transition: fade
    slide-number: true
    incremental: false 
    chalkboard: true
execute:
  freeze: auto
  echo: true
knitr:
  opts_chunk: 
    R.options:
      width: 200
---


## A Research Hypothesis poses a question about the relationship between two or more measurable characteristics.

:::{.callout-tip icon=false}
## Example
Is there a relationship between smoking frequency and suicide? 
:::


## Simple vs Complex

:::{layout-ncol=2}

:::{.callout-tip icon=false}
## Simple Hypothesis
Is there a relationship between smoking frequency and suicide? 
:::
* Simple relationship between two measures
* Can be answered with a 'yes' or 'no'


:::{.callout-tip icon=false}
## Complex Hypothesis
Does smoking frequency exacerbate poor mental health outcomes such as anxiety, depression and suicide? 
:::
* Stated as a relationship between multiple variables
* Can't be answered directly but through multiple sub-questions
::::



## Null vs Alternative 
AKA Statistical Hypothesis

:::{layout-ncol=2}

:::{.callout-tip icon=false}
## Null Hypothesis
Drug X has no affect on outcome Y
:::
* Stated as no relationship
* the 'status quo' or current status

:::{.callout-tip icon=false}
## Alternative Hypothesis
Drug X is associated with a change in outcome Y
:::
* stated as a relationship exists
* typically what you hope to show

::::


## Collaborative discussion

:::{.callout-note icon=false}
## Discuss each question below with your neighbor. 

Respond to the first three prompts in the Google Docs **Formulating Research Questions** collaborative notes. Put your names next to your answer. 
:::

* What are the characteristics of a good research question?  
* What is the one essential document you need to review before you can formulate a research question?
* Write an example of a research question

## Where to find prior information on your research topic? {.smaller}

* Google ofc. 
* Library for primary and secondary sources

:::{.callout-note icon=false}
## What are primary and secondary sources?

Answer the next set of questions in the collab notes. 
:::


* Give an example of a primary source of information.
* Give an example of a secondary source of information.
* What are some problems with secondary source literature?

