{
  "hash": "22904122cb3d60fb7d0317fbf72e4416",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Correlation Analysis\"\ndate: \"2025-10-22\"\nauthor: \"Robin Donatello\"\ndescription: \"lec07e\"\nfooter: \"[🔗 https://math615.netlify.app](https://math615.netlify.app)\"\nfrom: markdown+emoji\nformat: \n  revealjs:\n    theme: sky\n    transition: fade\n    slide-number: true\n    incremental: false \n    chalkboard: true\nexecute:\n  freeze: auto\n  echo: true\n  message: false\n  warning: false\nknitr:\n  opts_chunk: \n    R.options:\n      width: 200\neditor: \n  markdown: \n    wrap: 72\n---\n\n\n\n## Opening Remarks\n\nThe PMA6 textbook (Chapter 7) goes into great detail on this topic,\nsince regression is typically the basis for all advanced models.\n\nThe book also distinguishes between a \"fixed-x\" case, where the values\nof the explanatory variable $x$ only take on pre-specified values, and a\n\"variable-x\" case, where the values of $x$ are observations from a\npopulation distribution of X's.\n\nThis latter case is what we will be concerning ourselves with.\n\n## Bivariate distribution {.smaller}\n\nThe *bivariate distribution* describes how of $X$ and $Y$ are jointly\ndistributed, and is best interpreted by a look at the scatter diagram.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ny.bar <- mean(pen$bill_length_mm, na.rm=TRUE)\nx.bar <- mean(pen$body_mass_g, na.rm=TRUE)\n\np <- ggplot(pen, aes(x=body_mass_g, y=bill_length_mm)) + geom_point() + \n  geom_hline(yintercept = y.bar) + \n  geom_vline(xintercept = x.bar) \nggExtra::ggMarginal(p, type=\"histogram\")\n```\n\n::: {.cell-output-display}\n![](lec07e-correlation_files/figure-revealjs/unnamed-chunk-2-1.png){fig-align='center' width=576}\n:::\n:::\n\n\nIf $X$ and $Y$ come from independent normal distributions, the pair\n$(X,Y)$ comes from a *bivariate normal distribution*, and the data will\ntend to cluster around the means of $X$ and $Y$.\n\n## Ellipse of concentration\n\nWe can view the *ellipse of concentration* as measure of strength and\ndirection of the correlation between X and Y.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggpubr::ggscatter(pen, x = \"body_mass_g\", y = \"bill_length_mm\",\n   ellipse = TRUE, mean.point = TRUE,\n   star.plot = TRUE)\n```\n\n::: {.cell-output-display}\n![](lec07e-correlation_files/figure-revealjs/unnamed-chunk-3-1.png){fig-align='center' width=480}\n:::\n:::\n\n\nSee PMA6 Figure 7.5 for more examples.\n\n## Correlation\n\nThe **correlation coefficient** is designated by $r$ for the sample\ncorrelation, and $\\rho$ for the population correlation. The correlation\nis a measure of the strength and direction of a *linear relationship*\nbetween two variables.\n\nThe correlation ranges from +1 to -1. A correlation of +1 means that\nthere is a perfect, positive linear relationship between the two\nvariables. A correlation of -1 means there is a perfect, negative linear\nrelationship between the two variables. In both cases, knowing the value\nof one variable, you can perfectly predict the value of the second.\n\n\n## Reminder to visualize your data before analysis\n\n![These all have the same r value](images/ansQtet.png){fig-align=\"center\"}\n\n\n## Strength of the correlation\n\nHere are rough estimates for interpreting the strengths of correlations\nbased on the magnitude of $r$.\n\n-   $|r| \\geq 0.7$: Very strong relationship\n-   $0.4 \\leq |r| < 0.7$: Strong relationship\n-   $0.3 \\leq |r| < 0.4$: Moderate relationship\n-   $0.2 \\leq |r| < 0.3:$ Weak relationship\n-   $|r| < 0.2:$ Negligible or no relationship\n\n## As a measure of model fit\n\nWhen we square $r$ (i.e. $R^{2}$), it tells us what proportion of the\nvariability in one variable that is described by variation in the second\nvariable.\n\n\\\n\nYes, this is mathematically the same as the coefficient of determination\nwe saw in ANOVA.\n\n## Pearson test of correlation\n\nTo test for a *linear* correlation between two variables we use the\n**Pearson correlation coefficient** which is defined as the covariance\nof the two variables divided by the product of their standard\ndeviations.\n\n$$\n\\rho_{X,Y} = \\frac{cov(X,Y)}{\\sigma_{x}\\sigma_{Y}}\n$$\n\nThere are many modifications and adjustments to this measure that we\nwill not get into detail with. We are using correlation as a stepping\nstool to Linear Regression.\n\n## Example: Body mass and bill length of penguins\n\n### 1. Identify response and explanatory variables\n\n-   The quantitative explanatory variable is body mass (g)\n-   The quantitative response variable is bill length (mm)\n\n## 2. Visualize and summarise \n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(pen, aes(x=body_mass_g, y=bill_length_mm)) + \n  geom_point() + geom_smooth(col = \"red\")\n```\n\n::: {.cell-output-display}\n![](lec07e-correlation_files/figure-revealjs/unnamed-chunk-4-1.png){width=960}\n:::\n\n```{.r .cell-code}\ncor(pen$body_mass_g, pen$bill_length_mm, use = \"pairwise.complete.obs\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5951098\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\nThere is a strong, positive, mostly linear relationship between the body\nmass (g) of penguins and their bill length (mm) (r=.595).\n:::\n:::\n\n## 3.  Write the null and research hypothesis in words and symbols. {.smaller}\n\n-   Null Hypothesis: There is no correlation between the body mass and\n    bill length of penguins.\n-   Alternate Hypothesis: There is a correlation between the body mass\n    and bill length of penguins.\n\nLet $\\rho$ be the true correlation between body mass and bill length of penguins.\n\n$H_{0}: \\rho=0 \\qquad \\qquad H_{A}: \\rho \\neq 0$\n\n## 4. State and justify the analysis model. Check assumptions. \n\n* Pearsons test of correlation will be conducted. This is appropriate\nbecause both variables are quantitative. \n* The relationship between variables are reasonably linear\n* The sample size is large.\n\n## 5. Conduct the test\n\nAnd make a decision about the plausibility of the alternative hypothesis. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(pen$body_mass_g, pen$bill_length_mm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  pen$body_mass_g and pen$bill_length_mm\nt = 13.654, df = 340, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.5220040 0.6595358\nsample estimates:\n      cor \n0.5951098 \n```\n\n\n:::\n:::\n\n\nThe p-value is very small, there is evidence in favor of a non-zero\ncorrelation.\n\n## 6. Write a conclusion in context of the problem. \n\nThere was a statistically significant and strong correlation between the\nbody mass (g) and bill length (mm) of penguins (r = 0.595, 95%CI\n.5220-.6595, p \\< .0001). The significant positive correlation shows\nthat as the body mass of a penguin increases so does the bill length.\nThese results suggest that 35% (95% CI: 27.2-43.5) of the variance in\nbill length can be explained by the body mass of the penguin.\n",
    "supporting": [
      "lec07e-correlation_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}