{
  "hash": "ce0852a70c7cf434a1fb8250a502ce93",
  "result": {
    "markdown": "---\ntitle: \"HW 09: Fitting Multiple Regression models\"\nexecute:\n  echo: true\n  warning: false\n  message: false\nformat: \n  html: \n    toc: false\n---\n\n\n# Purpose\n\nPractice fitting and interpreting different types of multiple regression models. \n\n# General Instructions\n\nYou will perform <span style=\"color:blue\">4</span> regression analyses in this assignment. \nThe instructions differ slightly for each model. Review the examples below carefully and follow all steps. \n\n## Part 1 - Model fitting & Interpretation\n\n1. Define your variables in an English sentence, and in terms of $x$ variables.\n  - Specify the levels of your binary and categorical variables, and note which one is the reference group. \n  - Write the mathematical model.\n2. Visualize and describe the relationship between your response variable and at least 2 of your predictor variable using appropriate multivariable plots. See ASCN Ch 2 for examples. \n  - Make a statement whether or not you think a relationship exists. \n3. Fit the multiple regression model and create a table of estimates, confidence intervals and p-values.\n4. Interpret ALL regression coefficients (including the intercept) in a sentence that includes a confidence interval and p-value.\n  - Don't forget to back-transform your results where appropriate before you interpret. \n5. Assess model fit\n    - Examine the residuals for linear models\n    - Compare the distribution of predicted probabilities against the true class for Logistic regression. \n\n\n1. **Model 1** Multiple Linear Regression: $Y \\sim X_{1} + X_{2}$. \n    - Use at least one quantitative and one binary predictor. \n2. **Model 2** Multiple Linear Regression with a categorical predictor: $Y \\sim X_{1} + X_{2} \\ldots X_{p}$. \n    - Use _the same_ quantitative and binary predictor from #1, but add a categorical predictor. \n3. **Model 3** Regression on a log transformed outcome: $ln(Y) \\sim X_{1} + X_{2}$. \n    - $X_{1}$ and $X_{2}$ can be of any data type. \n    - Do not interpret the intercept\n4. **Model 4** Logistic Regression: $logit(Y) \\sim X_{1} + X_{2}$. \n    - Use one quantitative variable, the other can be either binary or categorical.   \n    - When you define your $x$ and $y$ variables, also define what $p$ is. \n\n## Part II Model Comparison\n\n* Create a combined regression model table for Model 1 and 2\n* Compare these two models using at least two measures of model fit: $R^{2}_{adj}$, RMSE, AIC, or BIC. Which one would you say fits the data better, and why? \n    \n----\n\n# Submission instructions\n\n* Use the template provided: [[QMD]](_templates/hw09-multiple_regression_template.qmd)\n  - Right click and 'save as', put this in your `scripts` folder\n* Upload your rendered **PDF** to Canvas by the due date. \n\n----\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(gtsummary); library(performance)\nlibrary(ggplot2); library(ggExtra)\n\n#load(\"C:/Users/rdonatello/Box/Data/AddHealth/addhealth_clean.Rdata\")\nload(\"C:/Box/Data/AddHealth/addhealth_clean.Rdata\")\n```\n:::\n\n::: {.cell}\n\n:::\n\n\n-----\n\n# Part 1 - Model fitting & Interpretation\n\n## **Model 1** Multiple Linear Regression\n\n### 1. Define your variables and write the mathematical model.\n\n* Let $y$ be the quantitative outcome measures of body mass index (variable `BMI`)\n* Let $x_{1}$ be the quantitative predictor variable that measures the typical amount of time someone sleeps at night (`sleep_duration`)\n* Let $x_{2}$ be a binary indicator of ever having smoked a cigarette (`eversmoke_c`).  $x_{2} = 1$ when `eversmoke_c = \"Smoked at least once\"`, and 0 when `eversmoke_c = \"Never Smoked\"`\n\n$$y = \\beta_{0} + \\beta_{1}x_{1} + \\beta_{2}x_{2}$$\n### 2. Visualize and describe the relationships. Make a statement whether or not you think a relationship exists. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot1 <- addhealth %>%\n  select(sleep_duration, BMI, eversmoke_c) %>% na.omit() %>% \n  ggplot(aes(x=sleep_duration, y=BMI, color = eversmoke_c)) + \n  geom_smooth(se=FALSE) + geom_point() + \n  theme_bw()  + \n   theme(legend.position = \"bottom\")\n\nggMarginal(plot1, type = \"density\", \n           groupColour = TRUE,\n           groupFill = TRUE)\n```\n\n::: {.cell-output-display}\n![](hw09-multiple_regression_files/figure-html/unnamed-chunk-3-1.png){width=384}\n:::\n:::\n\n\nThe relationship between sleep duration and BMI seems pretty flat, regardless of whether or not someone has ever smoked a cigarette. \n\n### 3. Fit the model and create a summary table. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1 <- lm(BMI ~ sleep_duration + eversmoke_c, data=addhealth) \n\nmodel1 |> \n  tbl_regression(intercept=TRUE) |> \n  add_glance_table(include = c(adj.r.squared, nobs))\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"kamhptqriy\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#kamhptqriy table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#kamhptqriy thead, #kamhptqriy tbody, #kamhptqriy tfoot, #kamhptqriy tr, #kamhptqriy td, #kamhptqriy th {\n  border-style: none;\n}\n\n#kamhptqriy p {\n  margin: 0;\n  padding: 0;\n}\n\n#kamhptqriy .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#kamhptqriy .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#kamhptqriy .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#kamhptqriy .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#kamhptqriy .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#kamhptqriy .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kamhptqriy .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#kamhptqriy .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#kamhptqriy .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#kamhptqriy .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#kamhptqriy .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#kamhptqriy .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#kamhptqriy .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#kamhptqriy .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#kamhptqriy .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#kamhptqriy .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#kamhptqriy .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#kamhptqriy .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#kamhptqriy .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kamhptqriy .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#kamhptqriy .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#kamhptqriy .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#kamhptqriy .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kamhptqriy .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#kamhptqriy .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#kamhptqriy .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kamhptqriy .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kamhptqriy .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#kamhptqriy .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kamhptqriy .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#kamhptqriy .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kamhptqriy .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#kamhptqriy .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kamhptqriy .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#kamhptqriy .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kamhptqriy .gt_left {\n  text-align: left;\n}\n\n#kamhptqriy .gt_center {\n  text-align: center;\n}\n\n#kamhptqriy .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#kamhptqriy .gt_font_normal {\n  font-weight: normal;\n}\n\n#kamhptqriy .gt_font_bold {\n  font-weight: bold;\n}\n\n#kamhptqriy .gt_font_italic {\n  font-style: italic;\n}\n\n#kamhptqriy .gt_super {\n  font-size: 65%;\n}\n\n#kamhptqriy .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#kamhptqriy .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#kamhptqriy .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#kamhptqriy .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#kamhptqriy .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#kamhptqriy .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#kamhptqriy .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Beta&lt;/strong&gt;\"><strong>Beta</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;95% CI&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>95% CI</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;p-value&lt;/strong&gt;\"><strong>p-value</strong></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">30</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">29, 31</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">sleep_duration</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-0.06</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">-0.18, 0.06</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.3</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">eversmoke_c</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"ci\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Never Smoked</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">—</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Smoked at least once</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-0.86</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">-1.3, -0.43</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: #D3D3D3;\">Adjusted R²</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: #D3D3D3;\">0.003</td>\n<td headers=\"ci\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: #D3D3D3;\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: #D3D3D3;\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">No. Obs.</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">4,959</td>\n<td headers=\"ci\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> CI = Confidence Interval</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n\n### 4. Interpret ALL regression coefficients\n\n* $b_{0}$: For a non-smoker (`eversmoke_c=0`) who typically sleeps 0 hours (`sleep_duration=0`), their predicted average BMI is 30(95% CI 29, 31, p<.001)\n* $b_{1}$: Holding smoking status constant, for every additional hour a person sleeps, their predicted average BMI drops by 0.06 (95% CI -0.06, 0.18). This is not a significant association (p = 0.3).\n* $b_{2}$: Controlling for how much sleep someone gets, the predicted average BMI for smoker is 0.86 (95% CI 0.43, 1.3) points lower than for a non-smoker This is a significant difference, p<.001\n\n### 5. Assess model fit\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_model(model1)\n```\n\n::: {.cell-output-display}\n![](hw09-multiple_regression_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nThis model fits the data somewhat well. The residuals are not normal, with predicted BMI higher than the observed. The residuals are clustered into two nearly non-overlapping groups seen both in the homogeneity of variance and the linearity diagnostic plots. This is due to the binary smoking status variable, but it doesn't look like one group has a different pattern than the other. The variance of the residuals looks reasonably constant, and the scatterplot indicated that a linear model wasn't unreasonable.\n\n----\n\n## **Model 2** Multiple Linear Regression with a Categorical Predictor\n\n### 1. Define your variables and write the mathematical model.\n\n* Let $y$ be the quantitative outcome measures of body mass index (variable `BMI`)\n* Let $x_{1}$ be the quantitative predictor variable that measures the typical amount of time someone sleeps at night (`sleep_duration`)\n* Let $x_{2}$ be a binary indicator of ever having smoked a cigarette (`eversmoke_c`).  $x_{2} = 1$ when `eversmoke_c = \"Smoked at least once\"`, and 0 when `eversmoke_c = \"Never Smoked\"` \n\nCategorical Predictor: General health (`genhealth`). 5 Levels: Excellent (reference), Very good, Good, Fair and Poor.  \n\n* Let $x_{3}=1$ when `genhealth='Very good'`, and 0 otherwise,\n* let $x_{4}=1$ when `genhealth='Good'`, and 0 otherwise,\n* let $x_{5}=1$ when `genhealth='Fair'`, and 0 otherwise,\n* let $x_{6}=1$ when `genhealth='Poor'`, and 0 otherwise. \n\nThe reference group for `genhealth` is `Excellent`. \n\nThe mathematical model would look like: \n\n$$ Y \\sim \\beta_{0} + \\beta_{1}*x_{1} + \\beta_{2}x_{2} + \\beta_{3}x_{3} + \\beta_{4}x_{4} + \\beta_{5}x_{5} + \\beta_{6}x_{6} $$\n\n### 2. Visualize and describe the relationships. Make a statement whether or not you think a relationship exists. \n\n\n::: {.cell}\n\n```{.r .cell-code}\naddhealth %>%\n  select(sleep_duration, BMI, eversmoke_c, genhealth) %>% na.omit() %>% \n  ggplot(aes(x=sleep_duration, y=BMI)) + \n  geom_smooth() + geom_point() + \n  theme_bw() +\n  facet_grid(genhealth~eversmoke_c)\n```\n\n::: {.cell-output-display}\n![](hw09-multiple_regression_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nThe relationship between sleep duration and BMI seems pretty flat, regardless of whether or not someone has ever smoked a cigarette or their general health. Note that the sample size for the combination of those reporting poor health but never have smoked is very small compared to the other groups. \n\n### 3. Fit the model and create a summary table. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel2 <- lm(BMI ~ sleep_duration + eversmoke_c + genhealth, data=addhealth)\nmodel2 |> \n  tbl_regression(intercept=TRUE) |> \n  add_glance_table(include = c(adj.r.squared, nobs))\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"xpcewaqmbj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#xpcewaqmbj table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#xpcewaqmbj thead, #xpcewaqmbj tbody, #xpcewaqmbj tfoot, #xpcewaqmbj tr, #xpcewaqmbj td, #xpcewaqmbj th {\n  border-style: none;\n}\n\n#xpcewaqmbj p {\n  margin: 0;\n  padding: 0;\n}\n\n#xpcewaqmbj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#xpcewaqmbj .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#xpcewaqmbj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#xpcewaqmbj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#xpcewaqmbj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xpcewaqmbj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xpcewaqmbj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xpcewaqmbj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#xpcewaqmbj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#xpcewaqmbj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#xpcewaqmbj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#xpcewaqmbj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#xpcewaqmbj .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#xpcewaqmbj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#xpcewaqmbj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xpcewaqmbj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#xpcewaqmbj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#xpcewaqmbj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#xpcewaqmbj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xpcewaqmbj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#xpcewaqmbj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#xpcewaqmbj .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#xpcewaqmbj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xpcewaqmbj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#xpcewaqmbj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#xpcewaqmbj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xpcewaqmbj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xpcewaqmbj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#xpcewaqmbj .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xpcewaqmbj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#xpcewaqmbj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xpcewaqmbj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xpcewaqmbj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xpcewaqmbj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xpcewaqmbj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xpcewaqmbj .gt_left {\n  text-align: left;\n}\n\n#xpcewaqmbj .gt_center {\n  text-align: center;\n}\n\n#xpcewaqmbj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#xpcewaqmbj .gt_font_normal {\n  font-weight: normal;\n}\n\n#xpcewaqmbj .gt_font_bold {\n  font-weight: bold;\n}\n\n#xpcewaqmbj .gt_font_italic {\n  font-style: italic;\n}\n\n#xpcewaqmbj .gt_super {\n  font-size: 65%;\n}\n\n#xpcewaqmbj .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#xpcewaqmbj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#xpcewaqmbj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#xpcewaqmbj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#xpcewaqmbj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#xpcewaqmbj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#xpcewaqmbj .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Beta&lt;/strong&gt;\"><strong>Beta</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;95% CI&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>95% CI</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;p-value&lt;/strong&gt;\"><strong>p-value</strong></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">27</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">26, 28</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">sleep_duration</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-0.02</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">-0.13, 0.09</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.7</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">eversmoke_c</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"ci\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Never Smoked</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">—</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Smoked at least once</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-1.2</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">-1.6, -0.75</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">genhealth</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"ci\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Excellent</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">—</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Very good</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.7</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">1.1, 2.2</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Good</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">4.5</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">3.9, 5.0</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Fair</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">6.8</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">6.0, 7.6</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Poor</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">7.5</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">5.5, 9.4</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: #D3D3D3;\">Adjusted R²</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: #D3D3D3;\">0.085</td>\n<td headers=\"ci\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: #D3D3D3;\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: #D3D3D3;\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">No. Obs.</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">4,959</td>\n<td headers=\"ci\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> CI = Confidence Interval</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n\n### 4. Interpret ALL regression coefficients\n\n* $b_{0}$: The predicted BMI for individuals who get no sleep, have never smoked and reports excellent health is 27 (95% CI 26, 28). \n* $b_{1}$: After controlling for smoking and health status, for every additional for every additional hour a person sleeps, their predicted average BMI drops by 0.02 (95% CI -0.09, 0.13). This is not a significant association (p = 0.7).\n* $b_{2}$: After controlling for sleep duration and health status, the predicted average BMI for smoker is 1.2 (95% CI 0.75, 1.6) points lower than for a non-smoker This is a significant difference, p<.001\n* $b_{3}$: Those reporting very good health have 1.7 (1.1, 2.2, p<.0001) higher BMI compared to those reporting excellent health. \n* $b_{4}$:Those reporting good health have 4.5 (3.9, 5.0, p<.0001) higher BMI compared to those reporting excellent health. \n* $b_{5}$: Those reporting fair health have 6.8 (6.0, 7.6, p<.0001) higher BMI compared to those reporting excellent health. \n* $b_{6}$: Those reporting poor health have 7.5 (5.5, 9.4, p<.0001) higher BMI compared to those reporting excellent health. \n\n\n### 5. Assess model fit\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_model(model2)\n```\n\n::: {.cell-output-display}\n![](hw09-multiple_regression_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nThis model fits the data a little bit better. The predicted BMI is still higher than the observed, but the variance of the residuals is clearly increasing as the fitted values increase. We also see the same deviation from the reference line in the tails of the qqplot, indicating not strictly non-normal residuals, but lots of outliers on both high end low ends. \n\n\n----\n\n## **Model 3** Log Transformed Response \n\n### 1. Define your variables and write the mathematical model.\n\n* Let $y$ be the quantitative outcome measures of annual income (`income`). This variable is right skewed, and so has been log-transformed (`logincome`)\n* Let $x_{1}$ be the quantitative predictor variable that measures the time you wake up in the morning using a 24 hour clock(variable `wakeup`)\n* Let $x_{2}$ be a binary indicator of gender (`female_c`).  $x_{2} = 1$ when `female_c = \"Male\"`, and 0 when `female_c = \"Female\"` \n\n$$ln(y) = \\beta_{0} + \\beta_{1}x_{1} + \\beta_{2}x_{2}$$\n\n### 2. Visualize and describe the relationships. Make a statement whether or not you think a relationship exists. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot3 <- addhealth %>%\n  select(wakeup, logincome, female_c) %>% na.omit() %>% \n  ggplot(aes(x=wakeup, y=logincome, color = female_c)) + \n  geom_smooth() + geom_point() + \n  theme_bw()  + \n   theme(legend.position = \"bottom\")\n\nggMarginal(plot3, type = \"density\", \n           groupColour = TRUE,\n           groupFill = TRUE)\n```\n\n::: {.cell-output-display}\n![](hw09-multiple_regression_files/figure-html/unnamed-chunk-9-1.png){width=384}\n:::\n:::\n\n\nThere appears to be a negative and somewhat linear trend between the time someone wakes up and their income. The trend for males looks slightly different than for females. I also expect that there may be a significant impact of gender on income given how much higher the male trend line is compared to the female trend line.  \n\n### 3. Fit the model and create a summary table. \n\n> Note. `tbl_regression` doesn't exponentiate the results of a log-linear model very well. So we're going to manually create a reasonable looking summary table. You should be able to copy/paste this code and input your own model variables. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel3 <- glm(logincome~wakeup + female_c, data=addhealth)\n# check sign of coefficients\ncoef(model3) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   (Intercept)         wakeup female_cFemale \n   10.73261157    -0.02707776    -0.19671504 \n```\n:::\n\n```{.r .cell-code}\n# note that they are both negative so we subtract from 1 after exponentiation\n# then i multiply by 100 so I can interpret as a percent\npct.chg <- (1-exp(coef(model3)))*100\n# extract confidence interval, do the same transformation\nci <-  (1-exp(confint(model3)))*100\n# extract p-values and apply a formatting\npvals <- broom::tidy(model3)$p.value\n# stick them all together into a table\nmod3.table <- cbind(pct.chg, ci, pvals)\n# display table, drop first row.\nknitr::kable(mod3.table[-1,], digits = 3)\n```\n\n::: {.cell-output-display}\n|               | pct.chg|  2.5 %| 97.5 %| pvals|\n|:--------------|-------:|------:|------:|-----:|\n|wakeup         |   2.671|  3.563|  1.772|     0|\n|female_cFemale |  17.858| 20.574| 15.048|     0|\n:::\n:::\n\n\n### 4. Interpret non-intercept regression coefficients\n\n* For every hour later one wakes up in the morning, one can expect to earn 2.7% (1.8%, 3.6%) lower income than someone who wakes up one hour earlier. This is after controlling for gender.\n* Females have on average 17.9% (15%, 20.5%) percent lower income than males, after controlling for the wake up time. \n\n\n### 5. Assess model fit\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_model(model3)\n```\n\n::: {.cell-output-display}\n![](hw09-multiple_regression_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nThe predicted distribution matches the observed data nearly exactly, but the residuals are _not_ normally distributed which is interesting. We see the clustering of the fitted values due to the binary indicator of gender, but otherwise the variance of the residuals is mostly constant. I would say that this model is \"okay\" but not the best. \n\n----\n\n## **Model 4** Logistic Regression\n\n### 1. Define your variables and write the mathematical model.\n\n* Let $y$ be a binary indicator for if an individuals reported personal income is below the poverty threshold for the year this data was collected $10,210 (`poverty`). \n* Let $p$ be the probability that someone is considered to be in poverty\n* Let $x_{1}$ be the quantitative predictor variable that measures the typical amount of time someone sleeps at night (`sleep_duration`)\n* Let $x_{2}$ be a binary indicator of gender (`female_c`).  $x_{2} = 1$ when `female_c = \"Male\"`, and 0 when `female_c = \"Female\"` \n\n$$log\\Big(\\frac{p}{1-p}\\Big) \\sim \\beta_{0} + \\beta_{1}x_{1} + \\beta_{1}x_{2}$$\n\n### 2. Visualize and describe the relationships. Make a statement whether or not you think a relationship exists. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.for.model4 <- addhealth %>% \n  select(sleep_duration, poverty, female_c) %>%\n  mutate(poverty_cat = factor(poverty, \n           labels = c(\"Under poverty line\", \"Over poverty line\"))) %>%\n  na.omit()\n\nggpubr::ggdensity(data.for.model4, x = \"sleep_duration\", \n                  fill = \"poverty\", facet.by = \"female_c\")\n```\n\n::: {.cell-output-display}\n![](hw09-multiple_regression_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nThe distribution of sleep duration seems to be shifted slightly higher for those living over the poverty line compared to those living under, and does not seem to differ depending on gender. \n\n\n### 3. Fit the model and create a summary table. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel4 <- glm(poverty~sleep_duration + female_c, \n              data=data.for.model4, family='binomial')\ntbl_regression(model4, exponentiate = TRUE, intercept = TRUE)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"nxyvtcectt\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#nxyvtcectt table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#nxyvtcectt thead, #nxyvtcectt tbody, #nxyvtcectt tfoot, #nxyvtcectt tr, #nxyvtcectt td, #nxyvtcectt th {\n  border-style: none;\n}\n\n#nxyvtcectt p {\n  margin: 0;\n  padding: 0;\n}\n\n#nxyvtcectt .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#nxyvtcectt .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#nxyvtcectt .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#nxyvtcectt .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#nxyvtcectt .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nxyvtcectt .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nxyvtcectt .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nxyvtcectt .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#nxyvtcectt .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#nxyvtcectt .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#nxyvtcectt .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#nxyvtcectt .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#nxyvtcectt .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#nxyvtcectt .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#nxyvtcectt .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#nxyvtcectt .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#nxyvtcectt .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#nxyvtcectt .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#nxyvtcectt .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nxyvtcectt .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#nxyvtcectt .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#nxyvtcectt .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#nxyvtcectt .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nxyvtcectt .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#nxyvtcectt .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#nxyvtcectt .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nxyvtcectt .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nxyvtcectt .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#nxyvtcectt .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nxyvtcectt .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#nxyvtcectt .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nxyvtcectt .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nxyvtcectt .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nxyvtcectt .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nxyvtcectt .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nxyvtcectt .gt_left {\n  text-align: left;\n}\n\n#nxyvtcectt .gt_center {\n  text-align: center;\n}\n\n#nxyvtcectt .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#nxyvtcectt .gt_font_normal {\n  font-weight: normal;\n}\n\n#nxyvtcectt .gt_font_bold {\n  font-weight: bold;\n}\n\n#nxyvtcectt .gt_font_italic {\n  font-style: italic;\n}\n\n#nxyvtcectt .gt_super {\n  font-size: 65%;\n}\n\n#nxyvtcectt .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#nxyvtcectt .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#nxyvtcectt .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#nxyvtcectt .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#nxyvtcectt .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#nxyvtcectt .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#nxyvtcectt .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;OR&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>OR</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;95% CI&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>95% CI</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;p-value&lt;/strong&gt;\"><strong>p-value</strong></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.15</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">0.11, 0.20</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">sleep_duration</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.01</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">0.97, 1.05</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.7</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">female_c</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"ci\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Male</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">—</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Female</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">2.25</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">1.94, 2.62</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> OR = Odds Ratio, CI = Confidence Interval</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n\n### 4. Interpret ALL regression coefficients\n\n* $b_{0}$: The predicted probability for a male who sleeps 0 hours on average to be earning below the poverty line is 0.15 (0.11, 0.20). \n* $b_{1}$: After controlling for gender, every additional hour someone sleeps is associated with 1.01 (0.97, 1.05) times the odds of living under the poverty level. This is a non-significant difference p=.07.\n* $b_{2}$: After controlling for sleep duration, females have 2.25 (1.94, 2.62) time the odds of reporting annual earned wages below the federal poverty level compared to males.\n\n### 5. Assess model fit\nRef ASCN 12.2.1 for explanation of this code. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate predicted probabilities\np.hat <- predict(model4, type='response')\n# combine these predictions onto the data used for the model\n## note these have to have the same dimension. If you have missing\n## data you will need to use model4$model as the data\nmodel.pred.data <- cbind(data.for.model4, p.hat)\n\nggplot(model.pred.data, aes(x=poverty_cat, y=p.hat, fill=poverty_cat)) +\n      geom_violin(alpha=.4) + geom_jitter(alpha =.5, width=.2) + \n      scale_fill_viridis_d(guide=FALSE)\n```\n\n::: {.cell-output-display}\n![](hw09-multiple_regression_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nThe model predicted probability of living in poverty is on the y-axis, and the true outcome category is on the x. There does not seem to be a clear separation of outcome category based on predicted probability. \n\nMore of the responses with low predicted probabilities tend to correspond to records that are reported to be under the poverty line. However, there seems to be a very similar amount of individuals in each outcome category with similar predicted probability of around 0.25. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_performance(model4, metrics = \"PCP\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# Indices of model performance\n\nPCP  \n-----\n0.682\n```\n:::\n:::\n\nRegardless, this model does better in predicting whether or not someone reports income below the poverty line than a simple flip of a fair coin. The percent of correct predictions for this model is 68.2%. \n\n\n## Part II Model Comparison\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# set some nice themes\ntheme_gtsummary_journal(journal = \"jama\")\ntheme_gtsummary_compact()\n\ntbl1 <- model1 |> \n  tbl_regression(intercept=TRUE) |> \n  add_glance_table(include = c(adj.r.squared, sigma, AIC, BIC, nobs))\n\ntbl2 <- model2 |> \n  tbl_regression(intercept=TRUE) |> \n  add_glance_table(include = c(adj.r.squared, sigma, AIC, BIC, nobs))\n\ntbl_merge(\n  tbls = list(tbl1, tbl2),\n  tab_spanner = c(\"**Model 1**\", \"**Model 2**\")) |>\n  modify_table_body(~.x |>\n          dplyr::arrange(row_type == \"glance_statistic\"))\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"nyevkgtqcf\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#nyevkgtqcf table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#nyevkgtqcf thead, #nyevkgtqcf tbody, #nyevkgtqcf tfoot, #nyevkgtqcf tr, #nyevkgtqcf td, #nyevkgtqcf th {\n  border-style: none;\n}\n\n#nyevkgtqcf p {\n  margin: 0;\n  padding: 0;\n}\n\n#nyevkgtqcf .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 13px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#nyevkgtqcf .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#nyevkgtqcf .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#nyevkgtqcf .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#nyevkgtqcf .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nyevkgtqcf .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nyevkgtqcf .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nyevkgtqcf .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#nyevkgtqcf .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#nyevkgtqcf .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#nyevkgtqcf .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#nyevkgtqcf .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#nyevkgtqcf .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#nyevkgtqcf .gt_group_heading {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#nyevkgtqcf .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#nyevkgtqcf .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#nyevkgtqcf .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#nyevkgtqcf .gt_row {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#nyevkgtqcf .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nyevkgtqcf .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#nyevkgtqcf .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#nyevkgtqcf .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#nyevkgtqcf .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nyevkgtqcf .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#nyevkgtqcf .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#nyevkgtqcf .gt_last_summary_row {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nyevkgtqcf .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nyevkgtqcf .gt_first_grand_summary_row {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#nyevkgtqcf .gt_last_grand_summary_row_top {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nyevkgtqcf .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#nyevkgtqcf .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nyevkgtqcf .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nyevkgtqcf .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nyevkgtqcf .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nyevkgtqcf .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nyevkgtqcf .gt_left {\n  text-align: left;\n}\n\n#nyevkgtqcf .gt_center {\n  text-align: center;\n}\n\n#nyevkgtqcf .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#nyevkgtqcf .gt_font_normal {\n  font-weight: normal;\n}\n\n#nyevkgtqcf .gt_font_bold {\n  font-weight: bold;\n}\n\n#nyevkgtqcf .gt_font_italic {\n  font-style: italic;\n}\n\n#nyevkgtqcf .gt_super {\n  font-size: 65%;\n}\n\n#nyevkgtqcf .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#nyevkgtqcf .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#nyevkgtqcf .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#nyevkgtqcf .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#nyevkgtqcf .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#nyevkgtqcf .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#nyevkgtqcf .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" scope=\"colgroup\" id=\"&lt;strong&gt;Model 1&lt;/strong&gt;\">\n        <span class=\"gt_column_spanner\"><strong>Model 1</strong></span>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" scope=\"colgroup\" id=\"&lt;strong&gt;Model 2&lt;/strong&gt;\">\n        <span class=\"gt_column_spanner\"><strong>Model 2</strong></span>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Beta&lt;/strong&gt; &lt;strong&gt;(95% CI)&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Beta</strong> <strong>(95% CI)</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;p-value&lt;/strong&gt;\"><strong>p-value</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Beta&lt;/strong&gt; &lt;strong&gt;(95% CI)&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Beta</strong> <strong>(95% CI)</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;p-value&lt;/strong&gt;\"><strong>p-value</strong></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\">30 (29 to 31)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><0.001</td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">27 (26 to 28)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">sleep_duration</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\">-0.06 (-0.18 to 0.06)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\">0.32</td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">-0.02 (-0.13 to 0.09)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\">0.75</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">eversmoke_c</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Never Smoked</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Smoked at least once</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\">-0.86 (-1.3 to -0.43)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><0.001</td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">-1.2 (-1.6 to -0.75)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">genhealth</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Excellent</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Very good</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">1.7 (1.1 to 2.2)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Good</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">4.5 (3.9 to 5.0)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Fair</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">6.8 (6.0 to 7.6)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Poor</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">7.5 (5.5 to 9.4)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: #D3D3D3;\">Adjusted R²</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: #D3D3D3;\">0.003</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: #D3D3D3;\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: #D3D3D3;\">0.085</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: #D3D3D3;\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Sigma</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\">7.27</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">6.96</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">AIC</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\">33,749</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">33,326</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">BIC</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\">33,775</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">33,378</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">No. Obs.</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\">4,959</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">4,959</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"5\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> CI = Confidence Interval</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n\nThe model with the categorical variable of general health added in (Model 2) is a better model to use than Model 1 for several reasons. \n\n* The adjusted $R^2$ is a lot higher, 0.085 vs .003\n* The residual (unexplained) variance of model 2 is lower, (6.96 vs 7.27)\n* Both the AIC and BIC are lower. \n\n\n\n",
    "supporting": [
      "hw09-multiple_regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}