{
  "hash": "2b80dd8b3e22a16dee9451fa2699ea81",
  "result": {
    "markdown": "---\ntitle: \"Modeling Bivariate Relationships\" \ndate: \"2022-10-12\"\ndescription: \"8-10\"\nauthor: \"Robin Donatello\"\nfooter: \"[🔗 https://math615.netlify.app](https://math615.netlify.app) / Modeling Bivariate Relationships\"\nfrom: markdown+emoji\nformat: \n  revealjs:\n    theme: beige\n    multiplex: true\n    transition: fade\n    slide-number: true\n    incremental: false\n    code-fold: true\n    code-summary: \"Show the code\"\n    chalkboard: true\nexecute:\n  freeze: auto\n  echo: true\nknitr:\n  opts_chunk: \n    R.options:\n      width: 200\n---\n\n\n## Which analyseses to perform? \n\nMoving from: \n\n> \"What descriptive measures should be used to examine the data\"\n\nto\n\n> \"What statistical analyses should be performed? \n\n\\\n\nREF: PMA6 Chapter 6\n\n\n## Why selection can be difficult \n\n::: {.incremental}\n\n* Classroom instruction tends to present methods in logical order from a learning perspective. Building from simple to more complex. Exposure to complex models limited. \n* Real life data often contain a mixture of data types, missing data and complex patterns. This can make the choice of analysis somewhat arbitrary at times. \n* Two trained statisticians presented with the same data will often approach the analysis from different perspectives, and run different analyses depending on what assumptions they are willing to make. \n\n:::\n\n## Not always clear {.smaller}\n\n* The primary assumption of most standard statistical procedures is that the records are independent of each other. \n* Often program evaluation relies on paired measurements before and after a certain exposure or treatment (pre-post).\n    - In this case, the approach is to calculate a pairwise difference for each individual and compare the average difference to 0 (any change vs no change).\n* For the purposes of this class, we will only concern ourselves with independent groups. \n\nRepeated measures is a topic typically taught in MATH 456 (but also covered in Chapter 18 of PMA6)\n\n## Choose your adventure\n\nTable 6.2 in PMA6 shows which statistical analyses procedures are appropriate depending on the combination of explanatory and response variable. \n\n![](images/pma6_analysis_table.png)\n\n## Case study practice\n\nGo to the HackMD collaborative notes on [Choosing appropriate analysis](https://hackmd.io/@norcalbiostat/08-choosing-analysis) and work in pairs to answer an assigned question. \n\n## \n\n<a href=\"https://twitter.com/patilindrajeets/status/1360137736859095042\">\n<img src = \"images/everything_is_lm.png\" \n     alt = \"Tweet from Indrajeet Patil saying 'Your periodic reminder that the most common statistical tests are nothing but special cases of linear models.  https://lindeloev.github.io/tests-as-linear/. I wish someone had pointed out this beautiful simplicity and parsimony when I was learning statistics'\" \n     width = \"50%\" height = \"60%\">\n</a>\n\n## Additional References\n\nPMA6 does not go over T-test, ANOVA or $\\chi^{2}$ tests. To see more examples (with R code) and more mathematical detail see [Chapter 5 in the Applied Stats Course Notes](https://norcalbiostat.github.io/AppliedStatistics_notes/bivariate-analysis.html) \n\n# Quantitative Outcome ~ Binary Covariate\n\n## T-test for difference in means between two groups [(ASCN Section 5.3)](https://norcalbiostat.github.io/AppliedStatistics_notes/bv-ttest.html) {.smaller}\n\n* Parameter: $\\mu_{1} - \\mu_{2}$\n* Estimate:  $\\bar{x}_{1} - \\bar{x}_{2}$\n* Assumptions: \n    - Groups are mutually exclusive and independent\n    - Difference $\\bar{x}_{1} - \\bar{x}_{2}$ is normally distributed\n    - Variances are approximately the same\n\n$H_{0}: \\mu_{1} - \\mu_{2} = 0$: There is no difference in the averages between groups.\n\n$H_{A}: \\mu_{1} - \\mu_{2} \\neq 0$: There is a difference in the averages between groups. \n\n\n\n## Example: BMI vs smoking\nWe would like to know, is there convincing evidence that the average BMI differs between those who have ever smoked a cigarette in their life compared to those who have never smoked? \n\n\n\n\n\n::: {.callout-important}\n## Nitty gritty detail\n\nFor the purposes of learning, you will be writing out each step in the analysis in depth. As you begin to master these analyses, it is natural to slowly start to blend and some steps. However it is important for you to have a baseline reference. \n:::\n\n\n## 1. Identify response and explanatory variables\n\n* Ever smoker = binary explanatory variable (variable `eversmoke_c`)\n* BMI = quantitative response variable (variable `BMI`)\n\n## 2. Visualize and summarise bivariate relationship\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nplot.bmi.smoke <- addhealth %>% select(eversmoke_c, BMI) %>% na.omit()\n\nggplot(plot.bmi.smoke, aes(x=eversmoke_c, y=BMI, fill=eversmoke_c)) + \n      geom_boxplot(width=.3) + geom_violin(alpha=.4) + theme_bw() + \n      labs(x=\"Smoking status\") + \n      scale_fill_manual(values=c(\"skyblue\", \"orange\"), guide = \"none\") + \n      stat_summary(fun=\"mean\", geom=\"point\", size=3, pch=17, \n      position=position_dodge(width=0.75))\n```\n\n::: {.cell-output-display}\n![](lec08-bivariate_modeling_files/figure-revealjs/unnamed-chunk-2-1.png){width=960}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nplot.bmi.smoke %>% group_by(eversmoke_c) %>% \n              summarise(mean=mean(BMI, na.rm=TRUE), \n                        sd = sd(BMI, na.rm=TRUE)) %>%\n              kable(digits = 1)\n```\n\n::: {.cell-output-display}\n|eversmoke_c          | mean|  sd|\n|:--------------------|----:|---:|\n|Never Smoked         | 29.7| 7.8|\n|Smoked at least once | 28.8| 7.3|\n:::\n:::\n\n:::\n\n::::\n\n\n\nSmokers have on average BMI of 28.8, smaller than the average BMI of non-smokers at 29.7. Non-smokers have more variation in their weights (7.8 vs 7.3lbs), but the distributions both look normal, if slightly skewed right. \n\n\n## 3. Write the relationship you want to examine in the form of a research question.\n\n* Null Hypothesis: There is no difference in the average BMI between smokers and non-smokers.\n* Alternate Hypothesis: There is a difference in the average BMI between smokers and non-smokers.\n\n## 4. Perform an appropriate statistical analysis using Dr D's 4 step method.\n \n**a. Define parameters**\n\nLet $\\mu_{1}$ be the average BMI for smokers, and $\\mu_{2}$ be the average BMI for non-smokers \n\n**b. State the null and alternative hypothesis as symbols**\n\n$H_{0}: \\mu_{1} - \\mu_{2} = 0$  \n$H_{A}: \\mu_{1} - \\mu_{2} \\neq 0$\n\n##\n\n**c. State and justify the analysis model. Check assumptions.**\n\nWe are comparing the means between two independent samples. A Two-Sample T-Test for a difference in means will be conducted. The assumptions that the groups are independent is upheld because each individual can only be either a smoker or non smoker. The difference in sample means $\\bar{x}_{1}-\\bar{x}_{2}$ is normally distributed - this is a valid assumption due to the large sample size and that differences typically are normally distributed. The observations are independent, and the variances are roughly equal (67/44 = 1.5 is smaller than 2). \n\n##\n\n**d. Conduct the test and make a decision about the plausibility of the alternative hypothesis.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(BMI ~ eversmoke_c, data=addhealth)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  BMI by eversmoke_c\nt = 3.6937, df = 3395.3, p-value = 0.0002245\nalternative hypothesis: true difference in means between group Never Smoked and group Smoked at least once is not equal to 0\n95 percent confidence interval:\n 0.3906204 1.2744780\nsample estimates:\n        mean in group Never Smoked mean in group Smoked at least once \n                          29.67977                           28.84722 \n```\n:::\n:::\n\n\nThere is strong evidence in favor of the alternative hypothesis. The interval for the differences (0.4, 1.3) does not contain zero and the p-value = .0002.\n\n## 5. Write a conclusion in context of the problem. Include the point estimates, confidence interval for the difference and p-value.\n\nOn average, non-smokers have a significantly higher 0.82 (0.39, 1.27) BMI compared to smokers (p=.0002). \n\n\n# Quantitative Outcome ~ Categorical Covariate\n\n## Analysis of Variance (ANOVA)\n\nAnalysis of variance assesses whether the means of two or more groups are statistically different from each other. This analysis is appropriate whenever you want to compare the means (quantitative variables) of groups (categorical variables).\n\n\nThe null hypothesis is that there is no difference in the mean of the quantitative variable across groups (categorical variable), while the alternative is that there is a difference.\n\n##  {background-color=\"#6c972b\" background-image=\"https://imgs.xkcd.com/comics/significant.png\" background-size=\"300px\" background-position=\"85% 50%\"}\n\n:::: {.columns}\n\n::: {.column width=\"40%\"}\n**Why not multiple T-tests between all pairs of groups?**\n\n\\\n\nEach time you conduct a test, you risk coming to the wrong conclusion. \n\n\nRepeated tests compound that chance of being wrong. \n\n\\\n\nImg Ref: [https://xkcd.com/882](https://xkcd.com/882)\n\n:::\n\n::: {.column width=\"60%\"}\n\n:::\n\n::::\n\n## Type I and Type II Error (an important side topic)\n",
    "supporting": [
      "lec08-bivariate_modeling_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\r\n<script>\r\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\r\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\r\n  // slide changes (different for each slide format).\r\n  (function () {\r\n    function fireSlideChanged(previousSlide, currentSlide) {\r\n\r\n      // dispatch for htmlwidgets\r\n      const event = window.document.createEvent(\"Event\");\r\n      event.initEvent(\"slideenter\", true, true);\r\n      window.document.dispatchEvent(event);\r\n\r\n      // dispatch for shiny\r\n      if (window.jQuery) {\r\n        if (previousSlide) {\r\n          window.jQuery(previousSlide).trigger(\"hidden\");\r\n        }\r\n        if (currentSlide) {\r\n          window.jQuery(currentSlide).trigger(\"shown\");\r\n        }\r\n      }\r\n    }\r\n\r\n    // hookup for reveal\r\n    if (window.Reveal) {\r\n      window.Reveal.addEventListener(\"slidechanged\", function(event) {\r\n        fireSlideChanged(event.previousSlide, event.currentSlide);\r\n      });\r\n    }\r\n\r\n    // hookup for slidy\r\n    if (window.w3c_slidy) {\r\n      window.w3c_slidy.add_observer(function (slide_num) {\r\n        // slide_num starts at position 1\r\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\r\n      });\r\n    }\r\n\r\n  })();\r\n</script>\r\n\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}