---
title: "HW 06: Foundations for Inference"
execute:
  echo: true
  warning: false
  message: false
---

# Purpose


----

# Instructions 


----

# Submission instructions

## Draft

Upload your <span style="color:red">PDF</span> file to the `03 Data Management` folder in Google Drive. 

### Peer Review instructions

As a reviewer, this is what you're checking for: 



## Final


----

# Study Design

1. Cats on YouTube. Suppose you want to estimate the percentage of videos on YouTube that are cat videos. It is impossible for you to watch all videos on YouTube, so you use a random video picker to select 1000 videos for you. You find that 2% of these videos are cat videos. Determine which of the following is an observation, a variable, a sample statistic (value calculated based on the observed sample), or a population parameter.

  a. Percentage of all videos on YouTube that are cat videos.
  
  b. 2%.
  
  c. A video in your sample.
  
  d. Whether a video is a cat video.



2. Stressed out. A study that surveyed a random sample of otherwise healthy high school students found that they are more likely to get muscle cramps when they are stressed. The study also noted that students drink more coffee and sleep less when they are stressed.
  a. What type of study is this?
  
  b. Can this study be used to conclude a causal relationship between increased stress and muscle cramps?
  
  c. State possible confounding variables that might explain the observed relationship between increased stress and muscle cramps.



3. Screens, teens, and psychological well-being. In a study of three nationally representative large-scale datasets from Ireland, the United States, and the United Kingdom (n = 17,247), teenagers between the ages of 12 to 15 were asked to keep a diary of their screen time and answer questions about how they felt or acted. The answers to these questions were then used to compute a psychological well-being score. Additional data were collected and included in the analysis, such as each child’s sex and age, and on the mother’s education, ethnicity, psychological distress, and employment. The study concluded that there is little clear-cut evidence that screen time decreases adolescent well-being. (Orben and Baukney-Przybylski 2018)

  a. What type of study is this?

  b. Identify the explanatory variables.

  c. Identify the response variable.

  d. Comment on whether the results of the study can be generalized to the population, and why.

  e. Comment on whether the results of the study can be used to establish causal relationships.





