---
title: "HW 07: Moderation and Stratification"
subtitle: "Identifing different trends within subgroups"
execute:
  echo: true
  warning: false
  message: false
---

# Purpose
To start to motivate multiple regression, we need to explore how a third variable can muck up the relationship between a predictor and an outcome variable. This assignment will have you testing prior analyses for potential moderators. 

----

# Instructions 

1. For each type of analysis (ANOVA, $\chi^2$, Regression), decide on a third variable to test as a moderating variable.
    - The potential moderator can be different for each analyses. You need to decide what variables are most appropriate for your research question. 
    - This third variable must be categorical and the fewer number of levels it has the easier it is to interpret. 
2. Adjust your bivariate visualization to account for this third variable (see ASCN Ch 2.7 for guidance and code). 
    - Typical methods for plotting a third variable include paneling or coloring by the third variable.
    - State your thoughts about how the relationship between the explanatory and response variable has _changed_ with levels of the moderator variable.
3. Adjust your analysis hypothesis to include this third variable. 
    - Is the relationship between X and Y the same for all levels of Z?
4. For each analysis, run the original model, and stratified model.  
5. Determine if the third variable is a moderator or not and justify your answer. 
   
----

# Submission instructions

* Use the template provided: [[QMD]](_templates/hw07_moderation_template.qmd). Rename this file to `moderation_userid`
* Upload your draft **PDF** of your work to the `07 Moderation/draft` folder in Google Drive

### Peer Review instructions

As a reviewer, this is what you're checking for: 

* Did they complete all steps?
* Did they check assumptions? 
* Are the graphics, summary statistics and analysis appropriate? 
* Is the final conclusion in plain english with no statistical jargon? 
* Does their conclusion match the output of their statistical program? 

## Final

* Upload your final **PDF** to `07 Moderation/final` folder in Google Drive.
