{
  "hash": "a81d4d0bd195f085c335678edc8ebf8e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Classification\"\ndate: \"2025-11-12\"\nauthor: \"Robin Donatello / MATH 615\"\ndescription: \"lec10c\"\nfooter: \"[🔗 https://math615.netlify.app](https://math615.netlify.app)\"\nfrom: markdown+emoji\nformat: \n  revealjs:\n    theme: sky\n    transition: fade\n    slide-number: true\n    incremental: false \nexecute:\n  freeze: auto\n  echo: true\n  message: false\n  warning: false\nknitr:\n  opts_chunk: \n    R.options:\n      width: 200\neditor: \n  markdown: \n    wrap: 72\n---\n\n\n\n\n\n## Setup\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nlibrary(ggplot2)\nlibrary(ROCR)\nlibrary(ggpubr)\nlibrary(caret)\nlibrary(gtsummary)\nsource(here::here(\"load_data.R\"))\n```\n:::\n\n\n\n\n\n## Predicted Probabilities {.smaller}\n\n-   Sometimes Odds Ratios can be difficult to interpret or understand.\n-   Sometimes you just want to report the probability of the event\n    occurring.\n-   Or sometimes you want to predict whether or not a new individual is\n    going to have the event.\n\nFor all of these, we need to calculate $p_{i} = P(y_{i}=1)$, the\nprobability of the event.\n\n$$\np_{i} = \\frac{e^{\\beta_{0} + \\beta_{1}x_{1i} + \\beta_{2}x_{2i} + \\ldots + \\beta_{p}x_{pi}}}\n{1 + e^{\\beta_{0} + \\beta_{1}x_{1i} + \\beta_{2}x_{2i} + \\ldots + \\beta_{p}x_{pi}}}\n$$\n\n## Example: {.smaller}\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"nipmlzxyic\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#nipmlzxyic table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#nipmlzxyic thead, #nipmlzxyic tbody, #nipmlzxyic tfoot, #nipmlzxyic tr, #nipmlzxyic td, #nipmlzxyic th {\n  border-style: none;\n}\n\n#nipmlzxyic p {\n  margin: 0;\n  padding: 0;\n}\n\n#nipmlzxyic .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#nipmlzxyic .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#nipmlzxyic .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#nipmlzxyic .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#nipmlzxyic .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nipmlzxyic .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nipmlzxyic .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nipmlzxyic .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#nipmlzxyic .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#nipmlzxyic .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#nipmlzxyic .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#nipmlzxyic .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#nipmlzxyic .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#nipmlzxyic .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#nipmlzxyic .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#nipmlzxyic .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#nipmlzxyic .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#nipmlzxyic .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#nipmlzxyic .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nipmlzxyic .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#nipmlzxyic .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#nipmlzxyic .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#nipmlzxyic .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nipmlzxyic .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#nipmlzxyic .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#nipmlzxyic .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nipmlzxyic .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nipmlzxyic .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#nipmlzxyic .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nipmlzxyic .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#nipmlzxyic .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nipmlzxyic .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nipmlzxyic .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nipmlzxyic .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nipmlzxyic .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nipmlzxyic .gt_left {\n  text-align: left;\n}\n\n#nipmlzxyic .gt_center {\n  text-align: center;\n}\n\n#nipmlzxyic .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#nipmlzxyic .gt_font_normal {\n  font-weight: normal;\n}\n\n#nipmlzxyic .gt_font_bold {\n  font-weight: bold;\n}\n\n#nipmlzxyic .gt_font_italic {\n  font-style: italic;\n}\n\n#nipmlzxyic .gt_super {\n  font-size: 65%;\n}\n\n#nipmlzxyic .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#nipmlzxyic .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#nipmlzxyic .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#nipmlzxyic .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#nipmlzxyic .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#nipmlzxyic .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#nipmlzxyic .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#nipmlzxyic .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#nipmlzxyic div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"Kipsb2coT1IpKio=\"><span class='gt_from_md'><strong>log(OR)</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">age</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-0.02</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-0.04, 0.00</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.020</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">income</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-0.04</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-0.07, -0.01</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.009</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">sex</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Male</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">—</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Female</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.93</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.21, 1.7</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.016</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"4\"><span data-qmd-base64=\"QWJicmV2aWF0aW9uczogQ0kgPSBDb25maWRlbmNlIEludGVydmFsLCBPUiA9IE9kZHMgUmF0aW8=\"><span class='gt_from_md'>Abbreviations: CI = Confidence Interval, OR = Odds Ratio</span></span></td>\n    </tr>\n  </tfoot>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\nThe predicted probability of depression is calculated as: $$\nP(depressed) = \\frac{e^{-0.676 - 0.02096*age - .03656*income + 0.92945*sex}}\n{1 + e^{-0.676 - 0.02096*age - .03656*income + 0.92945*sex}}\n$$\n\nNotice this formulation requires you to specify a *covariate profile*. In other words, what value X take on for each record. Often when you are only concerned with comparing the effect of a single measures, you set all other measures equal to their means.\n\n## Comparing probabilities {.smaller}\n\nLet's compare the probability of being depressed for males and females separately, while holding age and income constant at the average value calculated across all individuals (regardless of sex).\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n$$\nP(depressed|Female) = \\frac{e^{-0.676 - 0.02096(44.4) - .03656(20.6) + 0.92945(1)}}\n{1 + e^{-0.676 - 0.02096(44.4) - .03656(20.6) + 0.92945(1)}} = 0.193\n$$\n\n\n$$\nP(depressed|Male) = \\frac{e^{-0.676 - 0.02096(44.4) - .03656(20.6) + 0.92945(0)}}\n{1 + e^{-0.676 - 0.02096(44.4) - .03656(20.6) + 0.92945(0)}} = 0.086\n$$\n\n\nThe probability for a 44.4 year old female who makes \\$20.6k annual income has a 0.19 probability of being depressed. The probability of depression for a male of equal age and income is 0.086.\n\n## Distribution of Predicted probabilities {.smaller}\n\nWe can use the `predict()` command to generate a vector of predictions $\\hat{p}_{i}$ for each row used in the model.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphat.depr <- predict(dep_sex_model, type='response') \ngghistogram(phat.depr, add = \"mean\" , fill = \"skyblue\")\n```\n\n::: {.cell-output-display}\n![](lec10c-classification_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\n\n\nThe average predicted probability of showing symptoms of depression is 0.17.\n\n## Plotting predictions {.smaller}\n\nThere was a significant effect of gender on depression diagnosis. How does that appear in the predicted probabilities? \n\n::: {.callout-caution title=\"Handling missing data in the model\"}\nAny row with missing data on any variable used in the model will be dropped, and so NOT get a predicted value. So the tactic is to use the data stored in the model object.\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nmodel.pred.data <- cbind(dep_sex_model$data, phat.depr)\ntail(names(model.pred.data))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"regdoc\"    \"treat\"     \"beddays\"   \"acuteill\"  \"chronill\"  \"phat.depr\"\n```\n\n\n:::\n:::\n\n\n\n\n\n##  Model predicted probability of depression\n\n:::: {.columns}\n\n::: {.column width=\"60%\"}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggpubr::ggdensity(model.pred.data, x=\"phat.depr\", add=\"mean\", color = \"sex\", fill = \"sex\", palette = c(\"#00AFBB\", \"#E7B800\"))\n```\n\n::: {.cell-output-display}\n![](lec10c-classification_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n\n:::\n\n::: {.column width=\"40%\"}\n-   Reminder this is the fitted data $\\hat{p}$ \n*   What do you notice in this plot?\n:::\n\n::::\n\n\n## Predicted Class (outcome)\n\nTo classify individual $i$ as being depressed or not, we draw a binary value ($x_{i} = 0$ or $1$), with probability $p_{i}$ by using the `rbinom` function, with a `size=1`.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(12345) #reminder: change the combo on my luggage\nplot.mpp <- data.frame(pred.prob = phat.depr, \n                       pred.class = rbinom(n = length(phat.depr), \n                                           size = 1, \n                                           p = phat.depr),\n                       truth = dep_sex_model$y)\nhead(plot.mpp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   pred.prob pred.class truth\n1 0.21108906          0     0\n2 0.08014012          0     0\n3 0.15266203          0     0\n4 0.24527840          1     0\n5 0.15208679          0     0\n6 0.17056409          0     0\n```\n\n\n:::\n:::\n\n\n\n\n\n## Confusion Matrix\n\nApplying class labels and creating a cross table of predicted (rows) vs truth (cols):\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot.mpp <- plot.mpp %>% \n            mutate(pred.class = factor(pred.class, labels=c(\"Not Depressed\", \"Depressed\")), \n                    truth = factor(truth, labels=c(\"Not Depressed\", \"Depressed\")))\n\ntable(plot.mpp$pred.class, plot.mpp$truth)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               \n                Not Depressed Depressed\n  Not Depressed           195        35\n  Depressed                49        15\n```\n\n\n:::\n:::\n\n\n\n\n\nThe model correctly identified 195 individuals as not depressed and 15 as depressed. The model got it wrong 49 + 35 times.\n\n## Accuracy {.smaller}\n\nThe **accuracy** of the model is calculated as the fraction of times the model prediction matches the observed category:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(195+15)/(195+35+49+15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7142857\n```\n\n\n:::\n:::\n\n\n\n\n\nThis model has a 71.4% accuracy.\n\n* Is this good? \n* What if death were the event?\n\nWe will see later how to use accuracy as a measure of model fit and how to optimize accuracy by changing the cutoff value. ",
    "supporting": [
      "lec10c-classification_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}