---
title: "Describing distributions of data" # title 
subtitle: "Visualizing your data is the first line of defense against bad data" # sub title
description: "9/12-9/18" #date range
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse);library(readxl); 
library(pander); library(janitor)

# Function to clean strings & separate into lists
str_prep <- function(var){
  as.list(
    str_split(var, "\r\n", simplify=TRUE)
    )
}

topic_mats <- read_excel("../schedule_615_test.xlsx", sheet="weekly_schedule") %>%
  clean_names() %>% 
  filter(grepl("t04", topic)) %>%
  mutate(assignment = gsub("hw", "../hw/hw", hw), 
         slides = sprintf("[%s](%s)", topic_name, paste0("../slides/", lecture, ".html"))) %>% 
  select(slides, collab, reading, assignment, topic_obj)
```

## Learning Path

### Where we've been
Importing & starting to wrangle our data

### Where we're at
Ready to visualize and learn characteristics of our data. 


### Objectives

```{r}
pander(str_prep(topic_mats$topic_obj))
```


## Learning Materials

{{< fa person-chalkboard >}}  **Slides (Will open in full screen. Right click to open in a new tab)**

```{r}
pander(str_prep(topic_mats$slides))
```

:books:  **Reading** 

```{r}
pander(str_prep(topic_mats$reading))
```


:pencil: **Collaborative notes**

```{r}
pander(str_prep(topic_mats$collab))
```

## Assignments

```{r}
pander(str_prep(topic_mats$assignment))
```

## Discussion

