---
title: "Describing Relationships" # title 
subtitle: "First step in investigating a question about an association" # sub title
description: "9/18-10/01" #date range
execute: 
  echo: false
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse);library(readxl); 
library(pander); library(janitor)

# Function to clean strings & separate into lists
str_prep <- function(var){
  var <- var[!is.na(var)]
  z <- as.list(
    str_split(var, "\r\n", simplify=TRUE)
    )
  z <- z[z != ""]
}

topic_mats <- read_excel(here::here("schedule_615.xlsx"), sheet="weekly_schedule") %>%
  clean_names() %>% 
  filter(grepl("t05", topic)) %>%
  mutate(assignment = gsub("hw", "../hw/hw", hw), 
         slides = sprintf("[%s](%s)", lecture, paste0("../slides/", lecture, ".html")), 
         collab = sprintf("[%s](%s)", collab_notes, collab_notes)
         ) %>% 
  select(slides, collab, reading, assignment, topic_obj, quiz)
```

## Learning Path

### Where we've been
* Visualizing a single varible
* Screening for potential errors and additional data management
* Starting to describe our project data

### Where we're at
* Ready to visualize associations between multiple variables. 


### Objectives

```{r}
pander(str_prep(topic_mats$topic_obj))
```


## Learning Materials

{{< fa person-chalkboard >}}  **Slides (Will open in full screen. Right click to open in a new tab)**

```{r}
pander(str_prep(topic_mats$slides))
```

:books:  **Reading** 

```{r}
pander(str_prep(topic_mats$reading))
```

## Assignments

```{r}
pander(str_prep(topic_mats$assignment))
```


## Assessment

```{r}
pander(str_prep(topic_mats$quiz))
```

