{
  "hash": "da12930bc340b7d256757497791c1788",
  "result": {
    "markdown": "---\ntitle: \"Describing distributions of data\" # title \nsubtitle: \"Visualizing your data is the first line of defense against bad data\" # sub title\ndescription: \"9/12-9/18\" #date range\n---\n\n::: {.cell}\n\n:::\n\n\n## Learning Path\n\n### Where we've been\nImporting & starting to wrangle our data\n\n### Where we're at\nReady to visualize and learn characteristics of our data. \n\n\n### Objectives\n\n\n::: {.cell}\n::: {.cell-output-display}\n* Create appropriate summary statistics and visualizations for different types of data.\n\n<!-- end of list -->\n:::\n:::\n\n\n\n## Learning Materials\n\n{{< fa person-chalkboard >}}  **Slides (Will open in full screen. Right click to open in a new tab)**\n\n\n::: {.cell}\n::: {.cell-output-display}\n* [Describing distributions of data](../slides/lec04-describing_data.html)\n\n<!-- end of list -->\n:::\n:::\n\n\n:books:  **Reading** \n\n\n::: {.cell}\n::: {.cell-output-display}\n* PMA6 Ch 4\n  * ASCN Ch 2.3\n\n<!-- end of list -->\n:::\n:::\n\n\n\n:pencil: **Collaborative notes**\n\n\n::: {.cell}\n::: {.cell-output-display}\n* _NA_\n\n<!-- end of list -->\n:::\n:::\n\n\n## Assignments\n\n\n::: {.cell}\n::: {.cell-output-display}\n* [HW04 Univariate Graphing](../hw/hw04-univ_graphing.html)\n\n<!-- end of list -->\n:::\n:::\n\n\n---\n\n# Notes\n:exclamation: New. I'm not too happy with the slide format, so i'm testing out a 'single page' format (which is what I historically have done anyhow)\n\n\n### Motivation\nVisualizing your data is hands down the most important thing you can learn to do. \n\n* Screen for data entry errors\n* Out of range variables\n* Mistakes in coding\n* Violation of model assumptions\n\n### Level of care depends on the audience {.smaller}\n\nThere are three main audiences in mind when creating data visualizations: \n\n1. For your eyes only (FYEO). These are quick and dirty plots, without annotation. Meant to be looked at once or twice. \n    - You'll create a TON of these. Don't spend a ton of time on them. \n    \n2. To share with others internally. These mostly need to stand on their own. Axes labels, titles, colors as needed, possibly captions.\n    - You'll create a lot of these, and you'll get better with practice at adding necessary annotation without a lot of time\n    \n\n3. Professional - Contains all bells and whistles needed to make it publication quality. \n    - You'll create very few of these, but they demand a lot of time, detail and thought. \n\n### Graphing with intent\n\nAlong with having the audience in mind, it is important to give thought to the purpose of the chart.\n\n> The effectiveness of any visualization can be measured according to how well it fulfills the tasks it was designed for. (A. Cairo, 2018).\n\n\n### Choosing Appropriate Visualization\n\n75% of your choice is determined by the data type\n\n[https://r-graph-gallery.com/](https://r-graph-gallery.com/)\n\n## Meet the Palmer Penguins\n\n<img src=\"../images/penguins.png\" width=\"60%\">\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(palmerpenguins) # for access to the penguin data\nlibrary(ggplot2)        # part of the tidyverse, but I'm being explicit here\nlibrary(sjPlot)         # alternative plotting package. GREAT for barcharts\npen <- penguins         # create a copy with a shorter name b/c I'm lazy\n```\n:::\n\n\n## Single Categorical Variable\n\n::: {.panel-tabset}\n### Tables\n\n**Frequencies (N)**\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(pen$species)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   Adelie Chinstrap    Gentoo \n      152        68       124 \n```\n:::\n:::\n\n\n**Percents (%)**\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(pen$species) |> proportions() |> round(digits=2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   Adelie Chinstrap    Gentoo \n     0.44      0.20      0.36 \n```\n:::\n:::\n\n\nPenguin species _Adelie_ make up 44% of the sample (n=152)\n\n### Plots\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsjPlot::plot_frq(pen$species) + xlab(\"Species\")\n```\n\n::: {.cell-output-display}\n![](t04-describing_distributions_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n:::\n\n:::{.callout-tip}\nMeet the base \"pipe\" `|>`\n\nThis functions sufficiently the same as `%>%` but doesn't require the `magrittr` package (part of the `tidyverse`). \nYou are welcome to use either. \n:::\n\n\n## Single Numeric Variable\n\n<img src=\"../images/culmen_depth.png\" width=\"50%\">\n\n\n::: {.panel-tabset}\n#### Center\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(pen$bill_depth_mm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n  13.10   15.60   17.30   17.15   18.70   21.50       2 \n```\n:::\n\n```{.r .cell-code}\nsd(pen$bill_depth_mm, na.rm=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.974793\n```\n:::\n:::\n\n\n\\\n\nThe average bill depth is 17.15mm, with a standard deviation of 1.9mm. \n\n#### Spread\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(pen$bill_depth_mm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n  13.10   15.60   17.30   17.15   18.70   21.50       2 \n```\n:::\n\n```{.r .cell-code}\nIQR(pen$bill_depth_mm, na.rm=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3.1\n```\n:::\n:::\n\n\\\n\nBill depth ranges from 13.1 to 21.5mm, and has an IQR of 3.1mm.\n\n\n#### Plots\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nggpubr::gghistogram(pen$bill_depth_mm, add_density = TRUE)\n```\n\n::: {.cell-output-display}\n![](t04-describing_distributions_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nggpubr::ggviolin(pen$bill_depth_mm, add = c(\"jitter\", \"boxplot\")) + coord_flip()\n```\n\n::: {.cell-output-display}\n![](t04-describing_distributions_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n:::\n\n::::\n\nThe distribution of bill depth appears to be bimodal with peaks around 15 and 18mm. \n\n:::\n\n### How to create graphs\n\n* Similar to the data management section, after identifying what you want to do, you go look up how to do that thing. \n* Don't expect to remember the exact code yet, just know where to look up an example and copy from there (all the ref's below)\n* copy/paste/pray\n* Keep graphs simple until you get more comfortable. \n\n\n### References\n\n* PMA6 Chapter 4 for appropriate plot choices\n* Applied Stats course Notes Chapter 2.3 for examples and code\n* HackMD Notes for Code specific notes\n* R specific help on the [Math 130](https://norcalbiostat.github.io/MATH130/faq.html) class page\n* `sjPlot` vignette: https://strengejacke.github.io/sjPlot/index.html\n* `ggpubr` vignette: https://rpkgs.datanovia.com/ggpubr/\n* `ggplot` vignette: https://ggplot2.tidyverse.org/index.html\n* R graphics cookbook: https://r-graphics.org/ \n\n\n",
    "supporting": [
      "t04-describing_distributions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}