{
  "hash": "01b021efc0696b9a0d7050f198741048",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Describing Distributions of Data\"\ndate: \"2024-09-16\"\nauthor: \"Robin Donatello\"\nfooter: \"[🔗 https://math615.netlify.app](https://math615.netlify.app) / Describing  Distributions of Data\"\nfrom: markdown+emoji\nformat: \n  revealjs:\n    theme: sky\n    transition: fade\n    slide-number: true\n    incremental: false \n    chalkboard: true\nexecute:\n  freeze: auto\n  echo: true\nknitr:\n  opts_chunk: \n    R.options:\n      width: 200\n---\n\n\n## Motivation\nVisualizing your data is hands down the most important thing you can learn to do. \n\n* Screen for data entry errors\n* Out of range variables\n* Mistakes in coding\n* Violation of model assumptions\n\n## Level of care depends on the audience {.smaller}\n\nThere are three main audiences in mind when creating data visualizations: \n\n1. For your eyes only (FYEO). These are quick and dirty plots, without annotation. Meant to be looked at once or twice. \n    - You'll create a TON of these. Don't spend a ton of time on them. \n    \n. . . \n\n2. To share with others internally. These mostly need to stand on their own. Axes labels, titles, colors as needed, possibly captions.\n    - You'll create a lot of these, and you'll get better with practice at adding necessary annotation without a lot of time\n    \n. . . \n\n3. Professional - Contains all bells and whistles needed to make it publication quality. \n    - You'll create very few of these, but they demand a lot of time, detail and thought. \n\n## Graphing with intent\n\nAlong with having the audience in mind, it is important to give thought to the purpose of the chart.\n\n> The effectiveness of any visualization can be measured according to how well it fulfills the tasks it was designed for. (A. Cairo, 2018).\n\n\n## Choosing Appropriate Visualization\n\n75% of your choice is determined by the data type\n\n\n#  {background-image=\"images/penguins.png\" background-size=\"50%\"}\n## Meet the Palmer Penguins\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(palmerpenguins)\npen <- penguins # because i don't want to type out penguins every time\n```\n:::\n\n\n## Single Categorical {background-image=\"images/penguins.png\" background-size=\"20%\" background-position=\"80% 10%\"}\n\n::: {.panel-tabset}\n### Tables\n\n**Frequencies (N)**\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(pen$species)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   Adelie Chinstrap    Gentoo \n      152        68       124 \n```\n\n\n:::\n:::\n\n\n**Percents (%)**\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(pen$species) |> proportions() |> round(digits=2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   Adelie Chinstrap    Gentoo \n     0.44      0.20      0.36 \n```\n\n\n:::\n:::\n\n\nPenguin species _Adelie_ make up 44% of the sample (n=152)\n\n### Plots\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsjPlot::plot_frq(pen$species) + xlab(\"Species\")\n```\n\n::: {.cell-output-display}\n![](lec04-describing_distributions_files/figure-revealjs/unnamed-chunk-4-1.png){width=960}\n:::\n:::\n\n\n### Description\n\n* Must include both the count `N` and the percent `%`.\n* Don't need to describe every bar, just the 1-2 that stand out. E.g. largest and smallest? Categories that you care about. \n\n> Penguin species _Adelie_ make up 44% of the sample (n=152)\n:::\n\n## Single Numeric {background-image=\"images/culmen_depth.png\" background-size=\"25%\" background-position=\"100% 0%\"}\n\n\n::: {.panel-tabset}\n### Center\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(pen$bill_depth_mm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n  13.10   15.60   17.30   17.15   18.70   21.50       2 \n```\n\n\n:::\n\n```{.r .cell-code}\nsd(pen$bill_depth_mm, na.rm=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.974793\n```\n\n\n:::\n:::\n\n\n\\\n\nThe average bill depth is 17.15mm, with a standard deviation of 1.9mm. \n\n### Spread\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(pen$bill_depth_mm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n  13.10   15.60   17.30   17.15   18.70   21.50       2 \n```\n\n\n:::\n\n```{.r .cell-code}\nIQR(pen$bill_depth_mm, na.rm=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.1\n```\n\n\n:::\n:::\n\n\\\n\nBill depth ranges from 13.1 to 21.5mm, and has an IQR of 3.1mm.\n\n### Base R Plots\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(pen$bill_depth_mm)\n```\n\n::: {.cell-output-display}\n![](lec04-describing_distributions_files/figure-revealjs/unnamed-chunk-7-1.png){width=960}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(pen$bill_depth_mm)\n```\n\n::: {.cell-output-display}\n![](lec04-describing_distributions_files/figure-revealjs/unnamed-chunk-8-1.png){width=960}\n:::\n:::\n\n\n:::\n\n::::\n\n### ggpubR\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nggpubr::gghistogram(pen$bill_depth_mm, add_density = TRUE)\n```\n\n::: {.cell-output-display}\n![](lec04-describing_distributions_files/figure-revealjs/unnamed-chunk-9-1.png){width=960}\n:::\n:::\n\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nggpubr::ggviolin(pen$bill_depth_mm, add = c(\"jitter\", \"boxplot\")) + coord_flip()\n```\n\n::: {.cell-output-display}\n![](lec04-describing_distributions_files/figure-revealjs/unnamed-chunk-10-1.png){width=960}\n:::\n:::\n\n\n:::\n\n::::\n\nThe distribution of bill depth appears to be bimodal with peaks around 15 and 18mm. \n\n\n\n### Description\n\n* Must include a description of `center`, `shape` and `spread`. \n* Include numbers\n* Always in context of the problem\n\n> The average penguin bill depth is 17.15mm, with a standard deviation of 1.9mm. Ranging from 13.1 to 21.5mm, there is a bimodal pattern with peaks around 15 and 18mm but otherwise no skew is noted and no outliers are present. \n\n\n:::\n\n## How to create graphs\n\n* Similar to the data management section, after identifying what you want to do, you go look up how to do that thing. \n* Don't expect to remember the exact code yet, just know where to look up an example and copy from there\n* copy/paste/pray\n* Keep graphs simple until you get more comfortable. \n\n\n## Additional Materials\n\n* PMA6 Chapter 4 \n* Applied Stats course Notes Chapter 2\n* `sjPlot` vignette: https://strengejacke.github.io/sjPlot/index.html\n* `ggpubr` vignette: https://rpkgs.datanovia.com/ggpubr/\n* `ggplot` vignette: https://ggplot2.tidyverse.org/index.html\n* R graphics cookbook: https://r-graphics.org/ \n\n## Inspiration\n\n* [https://r-graph-gallery.com/](https://r-graph-gallery.com/)\n",
    "supporting": [
      "lec04-describing_distributions_files/figure-revealjs"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}