---
title: "Exploring Soil Health Indicators: Yearly Trends in PLFA Biomass and Bacteria-to-Fungi Ratios Across Depths Regenerative Farming Systems"
Author: Figueroa, L, Woodward, A.
date: 2024-12-18
---

# Abstract

This study aims to assess how regenerative agriculture affects PLFA biomass and fungal-to-bacteria ratios in soil systems by depth yearly. There is an increased demand for food systems and overwhelming evidence that our current agricultural practices have devastating environmental effects. Results demonstrate that RA significantly enhances microbial biomass compared to conventional methods, with consistently higher biomass across all years. However, both systems experienced declines in biomass in 2023, with RA showing partial recovery in 2024 while conventional systems stagnated. Depth-specific analyses revealed significant increases in F:B ratios at deeper soil layers, though overall trends in F:B ratios fluctuated, with an increase in 2023 followed by a decline in 2024. These patterns suggest that while RA supports soil microbial health, broader environmental or systemic pressures, such as climate variability or soil management practices, may also influence microbial dynamics.

These findings align with existing literature highlighting the benefits of RA for soil health and microbial diversity, yet underscore the complexity of soil ecosystems and the need for further research. The work supports the hypothesis that RA enhances microbial biomass over time and offers valuable insights for sustainable agricultural policy and practice while emphasizing the necessity of long-term studies to capture its potential benefits fully.


[Read their paper here](Figueroa-Woodward.pdf)


    