<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.319">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Robin Donatello">
<meta name="dcterms.date" content="2023-10-11">
<meta name="description" content="8-10">

<title>Data Analysis for Graduate Research - Modeling Bivariate Relationships</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta name="twitter:title" content="Data Analysis for Graduate Research - Modeling Bivariate Relationships">
<meta name="twitter:description" content="8-10">
<meta name="twitter:image" content="https://norcalbiostat.github.io/MATH615/slides/lec07b-bivariate_modeling_files/figure-html/unnamed-chunk-2-1.png">
<meta name="twitter:creator" content="@norcalbiostat">
<meta name="twitter:image-height" content="960">
<meta name="twitter:image-width" content="1344">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Data Analysis for Graduate Research</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../topics.html" rel="" target="">
 <span class="menu-text">Topics</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../slides.html" rel="" target="">
 <span class="menu-text">Slides</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../hw.html" rel="" target="">
 <span class="menu-text">Assignments</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../collab_notes.html" rel="" target="">
 <span class="menu-text">Collab Notes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../project.html" rel="" target="">
 <span class="menu-text">Project</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-other-materials" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Other Materials</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-other-materials">    
        <li>
    <a class="dropdown-item" href="../syllabus.html" rel="" target="">
 <span class="dropdown-text">Syllabus</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://norcalbiostat.github.io/AppliedStatistics_notes/" rel="" target="">
 <span class="dropdown-text">Applied Stats Notebook</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://openintro-ims.netlify.app/" rel="" target="">
 <span class="dropdown-text">Intro to Modern Stats</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://drive.google.com/drive/folders/1HdjMCqhIeQ_4L0zbme2XPH296_t5fabr" rel="" target=""><i class="bi bi-google" role="img">
</i> 
 <span class="dropdown-text">Google Drive</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../help.html" rel="" target="">
 <span class="menu-text">Help!</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#advisory-note" id="toc-advisory-note" class="nav-link active" data-scroll-target="#advisory-note">Advisory note</a></li>
  <li><a href="#a-unifying-model-framework" id="toc-a-unifying-model-framework" class="nav-link" data-scroll-target="#a-unifying-model-framework">A unifying model framework</a></li>
  <li><a href="#quantitative-outcome-binary-covariate" id="toc-quantitative-outcome-binary-covariate" class="nav-link" data-scroll-target="#quantitative-outcome-binary-covariate">Quantitative Outcome ~ Binary Covariate</a>
  <ul class="collapse">
  <li><a href="#model" id="toc-model" class="nav-link" data-scroll-target="#model">Model</a></li>
  <li><a href="#t-test-for-difference-in-means-between-two-groups" id="toc-t-test-for-difference-in-means-between-two-groups" class="nav-link" data-scroll-target="#t-test-for-difference-in-means-between-two-groups">T-test for difference in means between two groups</a></li>
  <li><a href="#example-bmi-vs-smoking" id="toc-example-bmi-vs-smoking" class="nav-link" data-scroll-target="#example-bmi-vs-smoking">Example: BMI vs smoking</a></li>
  <li><a href="#identify-response-and-explanatory-variables" id="toc-identify-response-and-explanatory-variables" class="nav-link" data-scroll-target="#identify-response-and-explanatory-variables">1. Identify response and explanatory variables</a></li>
  <li><a href="#visualize-and-summarise-bivariate-relationship" id="toc-visualize-and-summarise-bivariate-relationship" class="nav-link" data-scroll-target="#visualize-and-summarise-bivariate-relationship">2. Visualize and summarise bivariate relationship</a></li>
  <li><a href="#write-the-relationship-you-want-to-examine-in-the-form-of-a-research-question." id="toc-write-the-relationship-you-want-to-examine-in-the-form-of-a-research-question." class="nav-link" data-scroll-target="#write-the-relationship-you-want-to-examine-in-the-form-of-a-research-question.">3. Write the relationship you want to examine in the form of a research question.</a></li>
  <li><a href="#perform-an-appropriate-statistical-analysis-using-dr-ds-4-step-method." id="toc-perform-an-appropriate-statistical-analysis-using-dr-ds-4-step-method." class="nav-link" data-scroll-target="#perform-an-appropriate-statistical-analysis-using-dr-ds-4-step-method.">4. Perform an appropriate statistical analysis using Dr D’s 4 step method.</a></li>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section"></a></li>
  <li><a href="#section-1" id="toc-section-1" class="nav-link" data-scroll-target="#section-1"></a></li>
  <li><a href="#write-a-conclusion-in-context-of-the-problem.-include-the-point-estimates-confidence-interval-for-the-difference-and-p-value." id="toc-write-a-conclusion-in-context-of-the-problem.-include-the-point-estimates-confidence-interval-for-the-difference-and-p-value." class="nav-link" data-scroll-target="#write-a-conclusion-in-context-of-the-problem.-include-the-point-estimates-confidence-interval-for-the-difference-and-p-value.">5. Write a conclusion in context of the problem. Include the point estimates, confidence interval for the difference and p-value.</a></li>
  <li><a href="#assumption-samples-come-from-the-same-population" id="toc-assumption-samples-come-from-the-same-population" class="nav-link" data-scroll-target="#assumption-samples-come-from-the-same-population">Assumption: Samples come from the same population</a></li>
  <li><a href="#but-we-could-be-wrong" id="toc-but-we-could-be-wrong" class="nav-link" data-scroll-target="#but-we-could-be-wrong">But we could be wrong</a></li>
  <li><a href="#but-we-could-be-wrong-1" id="toc-but-we-could-be-wrong-1" class="nav-link" data-scroll-target="#but-we-could-be-wrong-1">But we could be wrong</a></li>
  <li><a href="#type-i-and-type-ii-error" id="toc-type-i-and-type-ii-error" class="nav-link" data-scroll-target="#type-i-and-type-ii-error">Type I and Type II Error</a></li>
  </ul></li>
  <li><a href="#quant-cat" id="toc-quant-cat" class="nav-link" data-scroll-target="#quant-cat">Quant ~ Cat</a>
  <ul class="collapse">
  <li><a href="#analysis-of-variance-anova-model" id="toc-analysis-of-variance-anova-model" class="nav-link" data-scroll-target="#analysis-of-variance-anova-model">Analysis of Variance (ANOVA) Model</a></li>
  <li><a href="#hypothesis-specification" id="toc-hypothesis-specification" class="nav-link" data-scroll-target="#hypothesis-specification">Hypothesis specification</a></li>
  <li><a href="#section-2" id="toc-section-2" class="nav-link" data-scroll-target="#section-2"></a></li>
  <li><a href="#analysis-of-variance" id="toc-analysis-of-variance" class="nav-link" data-scroll-target="#analysis-of-variance">Analysis of Variance</a></li>
  <li><a href="#sum-of-squares" id="toc-sum-of-squares" class="nav-link" data-scroll-target="#sum-of-squares">Sum of Squares</a></li>
  <li><a href="#sum-of-squares-1" id="toc-sum-of-squares-1" class="nav-link" data-scroll-target="#sum-of-squares-1">Sum of Squares</a></li>
  <li><a href="#analysis-of-variance-table" id="toc-analysis-of-variance-table" class="nav-link" data-scroll-target="#analysis-of-variance-table">Analysis of Variance Table</a></li>
  <li><a href="#the-f-distribution" id="toc-the-f-distribution" class="nav-link" data-scroll-target="#the-f-distribution">The F-distribution</a></li>
  <li><a href="#assumptions" id="toc-assumptions" class="nav-link" data-scroll-target="#assumptions">Assumptions</a></li>
  <li><a href="#example-march-of-the-penguins" id="toc-example-march-of-the-penguins" class="nav-link" data-scroll-target="#example-march-of-the-penguins">Example: March of the Penguins</a></li>
  <li><a href="#identify-response-and-explanatory-variables-1" id="toc-identify-response-and-explanatory-variables-1" class="nav-link" data-scroll-target="#identify-response-and-explanatory-variables-1">1. Identify response and explanatory variables</a></li>
  <li><a href="#visualize-and-summarise-bivariate-relationship-1" id="toc-visualize-and-summarise-bivariate-relationship-1" class="nav-link" data-scroll-target="#visualize-and-summarise-bivariate-relationship-1">2. Visualize and summarise bivariate relationship</a></li>
  <li><a href="#write-the-relationship-you-want-to-examine-in-the-form-of-a-research-question.-1" id="toc-write-the-relationship-you-want-to-examine-in-the-form-of-a-research-question.-1" class="nav-link" data-scroll-target="#write-the-relationship-you-want-to-examine-in-the-form-of-a-research-question.-1">3. Write the relationship you want to examine in the form of a research question.</a></li>
  <li><a href="#perform-an-appropriate-statistical-analysis-using-dr-ds-4-step-method.-1" id="toc-perform-an-appropriate-statistical-analysis-using-dr-ds-4-step-method.-1" class="nav-link" data-scroll-target="#perform-an-appropriate-statistical-analysis-using-dr-ds-4-step-method.-1">4. Perform an appropriate statistical analysis using Dr D’s 4 step method.</a></li>
  <li><a href="#section-3" id="toc-section-3" class="nav-link" data-scroll-target="#section-3"></a></li>
  <li><a href="#section-4" id="toc-section-4" class="nav-link" data-scroll-target="#section-4"></a></li>
  <li><a href="#write-a-conclusion-in-context-of-the-problem." id="toc-write-a-conclusion-in-context-of-the-problem." class="nav-link" data-scroll-target="#write-a-conclusion-in-context-of-the-problem.">5. Write a conclusion in context of the problem.</a></li>
  <li><a href="#multiple-post-hoc-comparisons-which-group-is-different" id="toc-multiple-post-hoc-comparisons-which-group-is-different" class="nav-link" data-scroll-target="#multiple-post-hoc-comparisons-which-group-is-different">Multiple / Post-Hoc comparisons: Which group is different?</a></li>
  <li><a href="#section-5" id="toc-section-5" class="nav-link" data-scroll-target="#section-5"></a></li>
  <li><a href="#coefficient-of-determination-r2-fracssgsst" id="toc-coefficient-of-determination-r2-fracssgsst" class="nav-link" data-scroll-target="#coefficient-of-determination-r2-fracssgsst">Coefficient of Determination <span class="math inline">\(R^{2} = \frac{SSG}{SST}\)</span></a></li>
  <li><a href="#non-parametric-tests" id="toc-non-parametric-tests" class="nav-link" data-scroll-target="#non-parametric-tests">Non-parametric tests</a></li>
  <li><a href="#kruskal-wallis" id="toc-kruskal-wallis" class="nav-link" data-scroll-target="#kruskal-wallis">Kruskal-Wallis</a></li>
  </ul></li>
  <li><a href="#categorical-outcome-categorical-covariate" id="toc-categorical-outcome-categorical-covariate" class="nav-link" data-scroll-target="#categorical-outcome-categorical-covariate">Categorical Outcome ~ Categorical Covariate</a>
  <ul class="collapse">
  <li><a href="#opening-remarks" id="toc-opening-remarks" class="nav-link" data-scroll-target="#opening-remarks">Opening Remarks</a></li>
  <li><a href="#chi-squared-test-of-equal-proportions-ref-ascn-section-5.5" id="toc-chi-squared-test-of-equal-proportions-ref-ascn-section-5.5" class="nav-link" data-scroll-target="#chi-squared-test-of-equal-proportions-ref-ascn-section-5.5">Chi-squared test of equal proportions (Ref: ASCN Section 5.5)</a></li>
  <li><a href="#results-from-study" id="toc-results-from-study" class="nav-link" data-scroll-target="#results-from-study">Results from study</a></li>
  <li><a href="#assume-independenceno-association" id="toc-assume-independenceno-association" class="nav-link" data-scroll-target="#assume-independenceno-association">Assume independence/no association</a></li>
  <li><a href="#table-notation" id="toc-table-notation" class="nav-link" data-scroll-target="#table-notation">Table notation</a></li>
  <li><a href="#calculating-the-expected-count" id="toc-calculating-the-expected-count" class="nav-link" data-scroll-target="#calculating-the-expected-count">Calculating the expected count</a></li>
  <li><a href="#calculating-the-residuals" id="toc-calculating-the-residuals" class="nav-link" data-scroll-target="#calculating-the-residuals">Calculating the residuals</a></li>
  <li><a href="#chi2-test-statistic" id="toc-chi2-test-statistic" class="nav-link" data-scroll-target="#chi2-test-statistic"><span class="math inline">\(\chi^2\)</span> test statistic</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#example-income-and-general-health" id="toc-example-income-and-general-health" class="nav-link" data-scroll-target="#example-income-and-general-health">Example: Income and General Health</a></li>
  <li><a href="#identify-response-and-explanatory-variables-2" id="toc-identify-response-and-explanatory-variables-2" class="nav-link" data-scroll-target="#identify-response-and-explanatory-variables-2">1. Identify response and explanatory variables</a></li>
  <li><a href="#visualize-and-summarise-bivariate-relationship-2" id="toc-visualize-and-summarise-bivariate-relationship-2" class="nav-link" data-scroll-target="#visualize-and-summarise-bivariate-relationship-2">2. Visualize and summarise bivariate relationship</a></li>
  <li><a href="#b.-other-ways-to-visualize-this-fyi-only" id="toc-b.-other-ways-to-visualize-this-fyi-only" class="nav-link" data-scroll-target="#b.-other-ways-to-visualize-this-fyi-only">2b. Other ways to visualize this (FYI only)</a></li>
  <li><a href="#write-the-relationship-you-want-to-examine-in-the-form-of-a-research-question.-2" id="toc-write-the-relationship-you-want-to-examine-in-the-form-of-a-research-question.-2" class="nav-link" data-scroll-target="#write-the-relationship-you-want-to-examine-in-the-form-of-a-research-question.-2">3. Write the relationship you want to examine in the form of a research question.</a></li>
  <li><a href="#perform-an-appropriate-statistical-analysis-using-dr-ds-4-step-method.-2" id="toc-perform-an-appropriate-statistical-analysis-using-dr-ds-4-step-method.-2" class="nav-link" data-scroll-target="#perform-an-appropriate-statistical-analysis-using-dr-ds-4-step-method.-2">4. Perform an appropriate statistical analysis using Dr D’s 4 step method.</a></li>
  <li><a href="#section-6" id="toc-section-6" class="nav-link" data-scroll-target="#section-6"></a></li>
  <li><a href="#write-a-conclusion-in-context-of-the-problem.-1" id="toc-write-a-conclusion-in-context-of-the-problem.-1" class="nav-link" data-scroll-target="#write-a-conclusion-in-context-of-the-problem.-1">5. Write a conclusion in context of the problem.</a></li>
  <li><a href="#multiple-comparisons-which-group-is-different" id="toc-multiple-comparisons-which-group-is-different" class="nav-link" data-scroll-target="#multiple-comparisons-which-group-is-different">Multiple comparisons: Which group is different?</a></li>
  <li><a href="#examine-the-residuals" id="toc-examine-the-residuals" class="nav-link" data-scroll-target="#examine-the-residuals">Examine the residuals</a></li>
  <li><a href="#all-pairwise-comparisons" id="toc-all-pairwise-comparisons" class="nav-link" data-scroll-target="#all-pairwise-comparisons">All pairwise comparisons</a></li>
  <li><a href="#the-effect-of-small-sample-sizes" id="toc-the-effect-of-small-sample-sizes" class="nav-link" data-scroll-target="#the-effect-of-small-sample-sizes">The effect of small sample sizes</a></li>
  <li><a href="#fishers-exact-test" id="toc-fishers-exact-test" class="nav-link" data-scroll-target="#fishers-exact-test">Fishers Exact Test</a></li>
  <li><a href="#chi-squared-test-of-associationindependence" id="toc-chi-squared-test-of-associationindependence" class="nav-link" data-scroll-target="#chi-squared-test-of-associationindependence">Chi-Squared test of Association/Independence</a></li>
  <li><a href="#example" id="toc-example" class="nav-link" data-scroll-target="#example">Example</a></li>
  <li><a href="#state-hypothesis" id="toc-state-hypothesis" class="nav-link" data-scroll-target="#state-hypothesis">State Hypothesis</a></li>
  <li><a href="#visualize-the-relationship" id="toc-visualize-the-relationship" class="nav-link" data-scroll-target="#visualize-the-relationship">Visualize the relationship</a></li>
  <li><a href="#test-the-relationship-make-a-conclusion." id="toc-test-the-relationship-make-a-conclusion." class="nav-link" data-scroll-target="#test-the-relationship-make-a-conclusion.">Test the relationship &amp; make a conclusion.</a></li>
  <li><a href="#other-analysis-for-categorical-variables" id="toc-other-analysis-for-categorical-variables" class="nav-link" data-scroll-target="#other-analysis-for-categorical-variables">Other analysis for categorical variables</a></li>
  </ul></li>
  <li><a href="#quantitative-outcome-quantitative-covariate" id="toc-quantitative-outcome-quantitative-covariate" class="nav-link" data-scroll-target="#quantitative-outcome-quantitative-covariate">Quantitative Outcome ~ Quantitative Covariate</a>
  <ul class="collapse">
  <li><a href="#opening-remarks-1" id="toc-opening-remarks-1" class="nav-link" data-scroll-target="#opening-remarks-1">Opening Remarks</a></li>
  <li><a href="#bivariate-distribution" id="toc-bivariate-distribution" class="nav-link" data-scroll-target="#bivariate-distribution">Bivariate distribution</a></li>
  <li><a href="#ellipse-of-concentration" id="toc-ellipse-of-concentration" class="nav-link" data-scroll-target="#ellipse-of-concentration">Ellipse of concentration</a></li>
  <li><a href="#correlation" id="toc-correlation" class="nav-link" data-scroll-target="#correlation">Correlation</a></li>
  <li><a href="#strength-of-the-correlation" id="toc-strength-of-the-correlation" class="nav-link" data-scroll-target="#strength-of-the-correlation">Strength of the correlation</a></li>
  <li><a href="#as-a-measure-of-model-fit" id="toc-as-a-measure-of-model-fit" class="nav-link" data-scroll-target="#as-a-measure-of-model-fit">As a measure of model fit</a></li>
  <li><a href="#pearson-test-of-correlation" id="toc-pearson-test-of-correlation" class="nav-link" data-scroll-target="#pearson-test-of-correlation">Pearson test of correlation</a></li>
  <li><a href="#example-body-mass-and-bill-length-of-penguins" id="toc-example-body-mass-and-bill-length-of-penguins" class="nav-link" data-scroll-target="#example-body-mass-and-bill-length-of-penguins">Example: Body mass and bill length of penguins</a>
  <ul class="collapse">
  <li><a href="#identify-response-and-explanatory-variables-3" id="toc-identify-response-and-explanatory-variables-3" class="nav-link" data-scroll-target="#identify-response-and-explanatory-variables-3">1. Identify response and explanatory variables</a></li>
  </ul></li>
  <li><a href="#visualize-and-summarise-bivariate-relationship-3" id="toc-visualize-and-summarise-bivariate-relationship-3" class="nav-link" data-scroll-target="#visualize-and-summarise-bivariate-relationship-3">2. Visualize and summarise bivariate relationship</a></li>
  <li><a href="#write-the-relationship-you-want-to-examine-in-the-form-of-a-research-question.-3" id="toc-write-the-relationship-you-want-to-examine-in-the-form-of-a-research-question.-3" class="nav-link" data-scroll-target="#write-the-relationship-you-want-to-examine-in-the-form-of-a-research-question.-3">3. Write the relationship you want to examine in the form of a research question.</a></li>
  <li><a href="#perform-an-appropriate-statistical-analysis-using-dr-ds-4-step-method.-3" id="toc-perform-an-appropriate-statistical-analysis-using-dr-ds-4-step-method.-3" class="nav-link" data-scroll-target="#perform-an-appropriate-statistical-analysis-using-dr-ds-4-step-method.-3">4. Perform an appropriate statistical analysis using Dr D’s 4 step method.</a></li>
  <li><a href="#section-7" id="toc-section-7" class="nav-link" data-scroll-target="#section-7"></a></li>
  <li><a href="#write-a-conclusion-in-context-of-the-problem.-2" id="toc-write-a-conclusion-in-context-of-the-problem.-2" class="nav-link" data-scroll-target="#write-a-conclusion-in-context-of-the-problem.-2">5. Write a conclusion in context of the problem.</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/norcalbiostat/math615_test/edit/main/slides/lec07b-bivariate_modeling.qmd" class="toc-action">Edit this page</a></p><p><a href="https://github.com/norcalbiostat/math615_test/issues/new" class="toc-action">Report an issue</a></p></div></div><div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="lec07b-bivariate_modeling.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Modeling Bivariate Relationships</h1>
</div>

<div>
  <div class="description">
    8-10
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Robin Donatello </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 11, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="advisory-note" class="level2">
<h2 class="anchored" data-anchor-id="advisory-note">Advisory note</h2>
<ul>
<li>This set of slides is really long.</li>
<li>I recommend using the navigation menu (hamburger menu in the bottom left) to skip to the relevant section.</li>
<li>You can also download these slides as PDF in that same side menu</li>
<li>Similar/more details on coding for this section found in ASCN Ch 5</li>
</ul>
</section>
<section id="a-unifying-model-framework" class="level2">
<h2 class="anchored" data-anchor-id="a-unifying-model-framework">A unifying model framework</h2>
<p>A good way to think about all statistical models is that the observed data comes from some true model with some random error.</p>
<blockquote class="blockquote">
<p>DATA = MODEL + RESIDUAL</p>
</blockquote>
<p>The <code>MODEL</code> is a mathematical formula like <span class="math inline">\(y = f(x)\)</span>. The formulation of the <code>MODEL</code> will change depending on the number of, and data types of explanatory variables. One goal of inferential analysis is to explain the variation in our data, using information contained in other measures.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="lec07b-bivariate_modeling_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="quantitative-outcome-binary-covariate" class="level1" data-background-image="plot2norm.png" data-background-opacity="0.3">
<h1 data-background-image="plot2norm.png" data-background-opacity="0.3">Quantitative Outcome ~ Binary Covariate</h1>
<ul>
<li>Does knowing what group an observation is in tell you about the location of the data?</li>
<li>Are the means of <strong>two</strong> groups are <em>statistically</em> different from each other?</li>
</ul>
<section id="model" class="level2">
<h2 class="anchored" data-anchor-id="model">Model</h2>
<p><span class="math display">\[
y_{ij} = \mu_{j} + \epsilon_{ij} \qquad \qquad
\epsilon_{ij} \overset{iid}{\sim} \mathcal{N}(0,\sigma^{2})
\]</span></p>
<ul>
<li>Response data <span class="math inline">\(y_{ij}\)</span> from observation <span class="math inline">\(i=1\ldots n\)</span> belonging to group <span class="math inline">\(j=1,2\)</span></li>
<li>The random error terms <span class="math inline">\(\epsilon_{ij}\)</span> are independently and identically distributed (iid) as normal with mean zero and common variance.</li>
</ul>
</section>
<section id="t-test-for-difference-in-means-between-two-groups" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="t-test-for-difference-in-means-between-two-groups">T-test for difference in means between two groups</h2>
<ul>
<li>Parameter: <span class="math inline">\(\mu_{1} - \mu_{2}\)</span></li>
<li>Estimate: <span class="math inline">\(\bar{x}_{1} - \bar{x}_{2}\)</span></li>
<li>Assumptions:
<ul>
<li>Group 1 &amp; 2 are mutually exclusive and independent</li>
<li>Difference <span class="math inline">\(\bar{x}_{1} - \bar{x}_{2}\)</span> is normally distributed</li>
<li>Variance within each group are approximately the same (<span class="math inline">\(\sigma\)</span>)</li>
</ul></li>
</ul>
<p><span class="math inline">\(H_{0}: \mu_{1} - \mu_{2} = 0\)</span>: There is no difference in the averages between groups.</p>
<p><span class="math inline">\(H_{A}: \mu_{1} - \mu_{2} \neq 0\)</span>: There is a difference in the averages between groups.</p>
</section>
<section id="example-bmi-vs-smoking" class="level2">
<h2 class="anchored" data-anchor-id="example-bmi-vs-smoking">Example: BMI vs smoking</h2>
<p>We would like to know, is there convincing evidence that the average BMI differs between those who have ever smoked a cigarette in their life compared to those who have never smoked?</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nitty gritty detail
</div>
</div>
<div class="callout-body-container callout-body">
<p>For the purposes of learning, you will be writing out each step in the analysis in depth. As you begin to master these analyses, it is natural to slowly start to blend and some steps. However it is important for you to have a baseline reference.</p>
</div>
</div>
</section>
<section id="identify-response-and-explanatory-variables" class="level2">
<h2 class="anchored" data-anchor-id="identify-response-and-explanatory-variables">1. Identify response and explanatory variables</h2>
<ul>
<li>Ever smoker = binary explanatory variable (variable <code>eversmoke_c</code>)</li>
<li>BMI = quantitative response variable (variable <code>BMI</code>)</li>
</ul>
</section>
<section id="visualize-and-summarise-bivariate-relationship" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="visualize-and-summarise-bivariate-relationship">2. Visualize and summarise bivariate relationship</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>plot.bmi.smoke <span class="ot">&lt;-</span> addhealth <span class="sc">%&gt;%</span> <span class="fu">select</span>(eversmoke_c, BMI) <span class="sc">%&gt;%</span> <span class="fu">na.omit</span>()</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plot.bmi.smoke, <span class="fu">aes</span>(<span class="at">x=</span>eversmoke_c, <span class="at">y=</span>BMI, <span class="at">fill=</span>eversmoke_c)) <span class="sc">+</span> </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_boxplot</span>(<span class="at">width=</span>.<span class="dv">3</span>) <span class="sc">+</span> <span class="fu">geom_violin</span>(<span class="at">alpha=</span>.<span class="dv">4</span>) <span class="sc">+</span> <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Smoking status"</span>) <span class="sc">+</span> </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">scale_fill_manual</span>(<span class="at">values=</span><span class="fu">c</span>(<span class="st">"skyblue"</span>, <span class="st">"orange"</span>), <span class="at">guide =</span> <span class="st">"none"</span>) <span class="sc">+</span> </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">stat_summary</span>(<span class="at">fun=</span><span class="st">"mean"</span>, <span class="at">geom=</span><span class="st">"point"</span>, <span class="at">size=</span><span class="dv">3</span>, <span class="at">pch=</span><span class="dv">17</span>, </span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">position=</span><span class="fu">position_dodge</span>(<span class="at">width=</span><span class="fl">0.75</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lec07b-bivariate_modeling_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>plot.bmi.smoke <span class="sc">%&gt;%</span> </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tbl_summary</span>(</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">by=</span><span class="st">"eversmoke_c"</span>,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="fu">all_continuous</span>() <span class="sc">~</span> <span class="dv">1</span>,     </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">statistic =</span> <span class="fu">list</span>(</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">all_continuous</span>() <span class="sc">~</span> <span class="st">"{mean} ({sd})"</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    ))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div id="kcspoobsdu" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#kcspoobsdu .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#kcspoobsdu .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#kcspoobsdu .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#kcspoobsdu .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#kcspoobsdu .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#kcspoobsdu .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#kcspoobsdu .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#kcspoobsdu .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#kcspoobsdu .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#kcspoobsdu .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#kcspoobsdu .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#kcspoobsdu .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#kcspoobsdu .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#kcspoobsdu .gt_from_md > :first-child {
  margin-top: 0;
}

#kcspoobsdu .gt_from_md > :last-child {
  margin-bottom: 0;
}

#kcspoobsdu .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#kcspoobsdu .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#kcspoobsdu .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#kcspoobsdu .gt_row_group_first td {
  border-top-width: 2px;
}

#kcspoobsdu .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#kcspoobsdu .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#kcspoobsdu .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#kcspoobsdu .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#kcspoobsdu .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#kcspoobsdu .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#kcspoobsdu .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#kcspoobsdu .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#kcspoobsdu .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#kcspoobsdu .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#kcspoobsdu .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#kcspoobsdu .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#kcspoobsdu .gt_left {
  text-align: left;
}

#kcspoobsdu .gt_center {
  text-align: center;
}

#kcspoobsdu .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#kcspoobsdu .gt_font_normal {
  font-weight: normal;
}

#kcspoobsdu .gt_font_bold {
  font-weight: bold;
}

#kcspoobsdu .gt_font_italic {
  font-style: italic;
}

#kcspoobsdu .gt_super {
  font-size: 65%;
}

#kcspoobsdu .gt_two_val_uncert {
  display: inline-block;
  line-height: 1em;
  text-align: right;
  font-size: 60%;
  vertical-align: -0.25em;
  margin-left: 0.1em;
}

#kcspoobsdu .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#kcspoobsdu .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#kcspoobsdu .gt_slash_mark {
  font-size: 0.7em;
  line-height: 0.7em;
  vertical-align: 0.15em;
}

#kcspoobsdu .gt_fraction_numerator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: 0.45em;
}

#kcspoobsdu .gt_fraction_denominator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: -0.05em;
}
</style>

<table class="gt_table table table-sm table-striped small" data-quarto-postprocess="true">
<thead class="gt_col_headings">
<tr class="header">
<th class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th"><strong>Characteristic</strong></th>
<th class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th"><strong>Never Smoked</strong>, N = 1,750<sup>1</sup></th>
<th class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th"><strong>Smoked at least once</strong>, N = 3,276<sup>1</sup></th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left">BMI</td>
<td class="gt_row gt_center">29.7 (7.8)</td>
<td class="gt_row gt_center">28.8 (7.3)</td>
</tr>
</tbody><tfoot class="gt_footnotes">
<tr class="even">
<td colspan="3" class="gt_footnote"><sup>1</sup> Mean (SD)</td>
</tr>
</tfoot>

</table>

</div>
</div>
</div>
</div>
</div>
<p>Smokers have on average BMI of 28.8, smaller than the average BMI of non-smokers at 29.7. Non-smokers have more variation in their weights (7.8 vs 7.3lbs), but the distributions both look normal, if slightly skewed right.</p>
</section>
<section id="write-the-relationship-you-want-to-examine-in-the-form-of-a-research-question." class="level2">
<h2 class="anchored" data-anchor-id="write-the-relationship-you-want-to-examine-in-the-form-of-a-research-question.">3. Write the relationship you want to examine in the form of a research question.</h2>
<ul>
<li>Null Hypothesis: There is no difference in the average BMI between smokers and non-smokers.</li>
<li>Alternate Hypothesis: There is a difference in the average BMI between smokers and non-smokers.</li>
</ul>
</section>
<section id="perform-an-appropriate-statistical-analysis-using-dr-ds-4-step-method." class="level2">
<h2 class="anchored" data-anchor-id="perform-an-appropriate-statistical-analysis-using-dr-ds-4-step-method.">4. Perform an appropriate statistical analysis using Dr D’s 4 step method.</h2>
<p><strong>a. Define parameters</strong></p>
<p>Let <span class="math inline">\(\mu_{1}\)</span> be the average BMI for smokers, and <span class="math inline">\(\mu_{2}\)</span> be the average BMI for non-smokers</p>
<p><strong>b. State the null and alternative hypothesis as symbols</strong></p>
<p><span class="math inline">\(H_{0}: \mu_{1} - \mu_{2} = 0\)</span><br>
<span class="math inline">\(H_{A}: \mu_{1} - \mu_{2} \neq 0\)</span></p>
</section>
<section id="section" class="level2">
<h2 class="anchored" data-anchor-id="section"></h2>
<p><strong>c.&nbsp;State and justify the analysis model. Check assumptions.</strong></p>
<p>We are comparing the means between two independent samples. A Two-Sample T-Test for a difference in means will be conducted. The assumptions that the groups are independent is upheld because each individual can only be either a smoker or non smoker. The difference in sample means <span class="math inline">\(\bar{x}_{1}-\bar{x}_{2}\)</span> is normally distributed - this is a valid assumption due to the large sample size and that differences typically are normally distributed. The observations are independent, and the variances are roughly equal (67/44 = 1.5 is smaller than 2).</p>
</section>
<section id="section-1" class="level2">
<h2 class="anchored" data-anchor-id="section-1"></h2>
<p><strong>d.&nbsp;Conduct the test and make a decision about the plausibility of the alternative hypothesis.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(BMI <span class="sc">~</span> eversmoke_c, <span class="at">data=</span>addhealth)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  BMI by eversmoke_c
t = 3.6937, df = 3395.3, p-value = 0.0002245
alternative hypothesis: true difference in means between group Never Smoked and group Smoked at least once is not equal to 0
95 percent confidence interval:
 0.3906204 1.2744780
sample estimates:
        mean in group Never Smoked mean in group Smoked at least once 
                          29.67977                           28.84722 </code></pre>
</div>
</div>
<p>There is strong evidence in favor of the alternative hypothesis. The interval for the differences (0.4, 1.3) does not contain zero and the p-value = .0002.</p>
</section>
<section id="write-a-conclusion-in-context-of-the-problem.-include-the-point-estimates-confidence-interval-for-the-difference-and-p-value." class="level2">
<h2 class="anchored" data-anchor-id="write-a-conclusion-in-context-of-the-problem.-include-the-point-estimates-confidence-interval-for-the-difference-and-p-value.">5. Write a conclusion in context of the problem. Include the point estimates, confidence interval for the difference and p-value.</h2>
<p>On average, non-smokers have a significantly higher 0.82 (0.39, 1.27) BMI compared to smokers (p=.0002).</p>
</section>
<section id="assumption-samples-come-from-the-same-population" class="level2">
<h2 class="anchored" data-anchor-id="assumption-samples-come-from-the-same-population">Assumption: Samples come from the same population</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://cdn.myportfolio.com/45214904-6a61-4e23-98d6-b140f8654a40/fa7b5022-e604-44d4-8659-985f427a673f_rw_1920.png?h=bd0561fd403aa4d7607c5609ea1ea292" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Credit: Allison Horst https://allisonhorst.com/</figcaption><p></p>
</figure>
</div>
</section>
<section id="but-we-could-be-wrong" class="level2">
<h2 class="anchored" data-anchor-id="but-we-could-be-wrong">But we could be wrong</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://cdn.myportfolio.com/45214904-6a61-4e23-98d6-b140f8654a40/d37eedc5-e0f9-43f4-88da-e81d97f00540_rw_1920.png?h=db424d8a00f8e515824ddaf0aceee46c" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Credit: Allison Horst https://allisonhorst.com/</figcaption><p></p>
</figure>
</div>
</section>
<section id="but-we-could-be-wrong-1" class="level2">
<h2 class="anchored" data-anchor-id="but-we-could-be-wrong-1">But we could be wrong</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://cdn.myportfolio.com/45214904-6a61-4e23-98d6-b140f8654a40/49e0e9dd-63c5-435c-9e94-38ee61c5224b_rw_1920.png?h=938bf875e8e6456341336019290469ad" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Credit: Allison Horst https://allisonhorst.com/</figcaption><p></p>
</figure>
</div>
</section>
<section id="type-i-and-type-ii-error" class="level2 incremental">
<h2 class="incremental anchored" data-anchor-id="type-i-and-type-ii-error">Type I and Type II Error</h2>
<ul>
<li>AKA False positive or false negative. <a href="https://en.wikipedia.org/wiki/Type_I_and_type_II_errors">Wikipedia</a></li>
<li>The significance level, <span class="math inline">\(\alpha\)</span>, is what we use to define the amount of “risk” we are willing to take to falsely reject <span class="math inline">\(H_{0}\)</span> (false positive).</li>
<li>We talk more about false positive &amp; false negative, <a href="https://en.wikipedia.org/wiki/Sensitivity_and_specificity">specificity and sensitivity</a> in Math 456.</li>
<li>We will see shortly however how to conduct multiple comparisons while maintaining our “family-wise” error rate at <span class="math inline">\(\alpha\)</span></li>
</ul>
</section>
</section>
<section id="quant-cat" class="level1" data-background-image="plot3norm.png" data-background-opacity="0.3">
<h1 data-background-image="plot3norm.png" data-background-opacity="0.3">Quant ~ Cat</h1>
<ul>
<li>Does knowing what group an observation is in tell you about the location of the data?</li>
<li>Are the means of <strong>two or more</strong> groups are <em>statistically</em> different from each other?</li>
</ul>
<section id="analysis-of-variance-anova-model" class="level2">
<h2 class="anchored" data-anchor-id="analysis-of-variance-anova-model">Analysis of Variance (ANOVA) Model</h2>
<p><span class="math display">\[
y_{ij} = \mu_{j} + \epsilon_{ij} \qquad \qquad
\epsilon_{ij} \overset{iid}{\sim} \mathcal{N}(0,\sigma^{2})
\]</span></p>
<ul>
<li>Response data <span class="math inline">\(y_{ij}\)</span> from observation <span class="math inline">\(i=1\ldots n\)</span> belonging to group <span class="math inline">\(j=1,2\)</span></li>
<li>The random error terms <span class="math inline">\(\epsilon_{ij}\)</span> are independently and identically distributed (iid) as normal with mean zero and common variance.</li>
<li>Look familiar? T-test is a special case of ANOVA.</li>
</ul>
</section>
<section id="hypothesis-specification" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-specification">Hypothesis specification</h2>
<p>The null hypothesis is that there is no difference in the mean of the quantitative variable across groups (categorical variable), while the alternative is that there is a difference.</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: The mean outcome is the same across all groups. <span class="math inline">\(\mu_1 = \mu_2 = \cdots = \mu_j\)</span></li>
<li><span class="math inline">\(H_A\)</span>: At least one mean is different.</li>
</ul>
</section>
<section id="section-2" class="level2" data-background-image="https://imgs.xkcd.com/comics/significant.png" data-background-size="300px" data-background-position="85% 50%">
<h2 data-background-image="https://imgs.xkcd.com/comics/significant.png" data-background-size="300px" data-background-position="85% 50%" class="anchored" data-anchor-id="section-2"></h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><strong>Why not multiple T-tests between all pairs of groups?</strong></p>
<p><br>
</p>
<p>Each time you conduct a test, you risk coming to the wrong conclusion.</p>
<p>Repeated tests compound that chance of being wrong.</p>
<p><br>
</p>
<p>Img Ref: <a href="https://xkcd.com/882" class="uri">https://xkcd.com/882</a></p>
</div><div class="column" style="width:40%;">

</div>
</div>
</section>
<section id="analysis-of-variance" class="level2">
<h2 class="anchored" data-anchor-id="analysis-of-variance">Analysis of Variance</h2>
<p>By comparing the portion of the variance in the outcome that is explained by the groups, to the portion that’s leftover due to unexplained randomness. Essentially we’re comparing the ratio of <code>MODEL</code> to <code>RESIDUAL</code>.</p>
<blockquote class="blockquote">
<p>Total Variation = Between Group Variation + Within Group Variation</p>
</blockquote>
</section>
<section id="sum-of-squares" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="sum-of-squares">Sum of Squares</h2>
<p>Variation is measured using the Sum of Squares (SS): The sum of the squares within a group (SSE), the sum of squares between groups (SSG), and the total sum of squares (SST).</p>
<p><span class="math display">\[
SST =  \sum_{i=1}^{I}\sum_{j=1}^{n_{i}}(y_{ij}-\bar{y}..)^{2} = (N-1)Var(Y)
\]</span></p>
<p><strong>SST (Total)</strong>: Measures the variation of the <span class="math inline">\(N\)</span> data points around the overall mean.</p>
</section>
<section id="sum-of-squares-1" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="sum-of-squares-1">Sum of Squares</h2>
<p><span class="math display">\[
SSG = \sum_{i=1}^{I}n_{i}(\bar{y}_{i.}-\bar{y}..)^{2} = n_{1}(\bar{y}_{1.}-\bar{y}..)^{2} + n_{2}(\bar{y}_{2.}-\bar{y}..)^{2} + \ldots + n_{I}(\bar{y}_{I.}-\bar{y}..)^{2}
\]</span></p>
<p><strong>SSG (Between groups)</strong>: Measures the variation of the <span class="math inline">\(I\)</span> group means around the overall mean.</p>
<p><span class="math display">\[
SSE = \sum_{i=1}^{I}\sum_{j=1}^{n_{i}}(y_{ij}-\bar{y}_{i.})^{2} = \sum_{i=1}^{I}(n_{i}-1)Var(Y_{i})
\]</span></p>
<p><strong>SSE (Within group)</strong>: Measures the variation of each observation around its group mean.</p>
</section>
<section id="analysis-of-variance-table" class="level2">
<h2 class="anchored" data-anchor-id="analysis-of-variance-table">Analysis of Variance Table</h2>
<p>The results are typically summarized in an ANOVA table.</p>
<table class="table">
<colgroup>
<col style="width: 15%">
<col style="width: 12%">
<col style="width: 9%">
<col style="width: 34%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th>Source</th>
<th>SS</th>
<th>df</th>
<th>MS</th>
<th>F</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Groups</td>
<td>SSG</td>
<td><span class="math inline">\(I-1\)</span></td>
<td>MSG = <span class="math inline">\(\frac{SSG}{I-1}\)</span></td>
<td><span class="math inline">\(\frac{MSG}{MSE}\)</span></td>
</tr>
<tr class="even">
<td>Error</td>
<td>SSE</td>
<td><span class="math inline">\(N-I\)</span></td>
<td>MSE = <span class="math inline">\(\frac{MSE}{N-I}\)</span></td>
<td></td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td><strong>SST</strong></td>
<td><span class="math inline">\(N-1\)</span></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>The value in the <strong>F</strong> column is the test statistic, and has a F distribution with degrees of freedom (df) dependent on the number of groups (I-1), and the number of observations (N-I).</p>
</section>
<section id="the-f-distribution" class="level2">
<h2 class="anchored" data-anchor-id="the-f-distribution">The F-distribution</h2>
<p>The <span class="math inline">\(p\)</span>-value is the <strong>area to the right</strong> of the F statistic density curve. This is always to the right because the F-distribution is truncated at 0 and skewed right. This is true regardless of the <span class="math inline">\(df\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>df1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">8</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">10</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="cn">NULL</span>, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">5</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">xlab =</span> <span class="fu">expression</span>(F), <span class="at">ylab=</span><span class="st">""</span>, <span class="at">main =</span> <span class="st">"F Distribution"</span>, <span class="at">axes=</span><span class="cn">FALSE</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">2</span>, <span class="at">labels =</span> <span class="cn">FALSE</span>, <span class="at">tick =</span> <span class="cn">FALSE</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>); <span class="fu">box</span>()</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>) {</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">curve</span>(<span class="fu">df</span>(x, df1[i], df2[i]), <span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="dv">5</span>, <span class="at">col =</span> i, <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">lty =</span> i, <span class="at">lwd=</span><span class="dv">2</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">legend =</span> <span class="fu">paste</span>(<span class="st">"df1 ="</span>, df1, <span class="st">", df2 ="</span>, df2), <span class="at">col =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">lty =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="lec07b-bivariate_modeling_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="assumptions" class="level2">
<h2 class="anchored" data-anchor-id="assumptions">Assumptions</h2>
<p>Generally we must check three conditions on the data before performing ANOVA:</p>
<ul>
<li>The observations are independent within and across groups</li>
<li>The data within each group are nearly normal</li>
<li>The variability across the groups is about equal.</li>
</ul>
</section>
<section id="example-march-of-the-penguins" class="level2">
<h2 class="anchored" data-anchor-id="example-march-of-the-penguins">Example: March of the Penguins</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>pen <span class="ot">&lt;-</span> palmerpenguins<span class="sc">::</span>penguins</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="identify-response-and-explanatory-variables-1" class="level2">
<h2 class="anchored" data-anchor-id="identify-response-and-explanatory-variables-1">1. Identify response and explanatory variables</h2>
<ul>
<li>Species = categorical explanatory variable</li>
<li>Flipper length = quantitative response variable</li>
</ul>
</section>
<section id="visualize-and-summarise-bivariate-relationship-1" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="visualize-and-summarise-bivariate-relationship-1">2. Visualize and summarise bivariate relationship</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggdist) <span class="co"># for the "half-violin" plot (stat_slab)</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pen, <span class="fu">aes</span>(<span class="at">x=</span>flipper_length_mm, <span class="at">y=</span>species, <span class="at">fill=</span>species)) <span class="sc">+</span> </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>      <span class="fu">stat_slab</span>(<span class="at">alpha=</span>.<span class="dv">5</span>, <span class="at">justification =</span> <span class="dv">0</span>) <span class="sc">+</span> </span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_boxplot</span>(<span class="at">width =</span> .<span class="dv">2</span>,  <span class="at">outlier.shape =</span> <span class="cn">NA</span>) <span class="sc">+</span> </span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_jitter</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">height =</span> <span class="fl">0.05</span>) <span class="sc">+</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">stat_summary</span>(<span class="at">fun=</span><span class="st">"mean"</span>, <span class="at">geom=</span><span class="st">"point"</span>, <span class="at">col=</span><span class="st">"red"</span>, <span class="at">size=</span><span class="dv">4</span>, <span class="at">pch=</span><span class="dv">17</span>) <span class="sc">+</span> </span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Flipper Length (mm)"</span>, <span class="at">y =</span> <span class="st">"Species"</span>) <span class="sc">+</span> </span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lec07b-bivariate_modeling_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>pen <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(species) <span class="sc">%&gt;%</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean=</span><span class="fu">mean</span>(flipper_length_mm, <span class="at">na.rm=</span><span class="cn">TRUE</span>), </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd =</span> <span class="fu">sd</span>(flipper_length_mm, <span class="at">na.rm=</span><span class="cn">TRUE</span>), </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">IQR =</span> <span class="fu">IQR</span>(flipper_length_mm, <span class="at">na.rm=</span><span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">species</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">IQR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Adelie</td>
<td style="text-align: right;">190.0</td>
<td style="text-align: right;">6.5</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chinstrap</td>
<td style="text-align: right;">195.8</td>
<td style="text-align: right;">7.1</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gentoo</td>
<td style="text-align: right;">217.2</td>
<td style="text-align: right;">6.5</td>
<td style="text-align: right;">9</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p>The distribution of flipper length varies across the species, with Gentoo having the largest flippers on average at 217.2mm compared to Adelie (190mm) and Chinstrap (195.8mm). The distributions are normally distributed with very similar spreads, Chinstrap has the most variable flipper length with a SD of 7.1 compared to 6.5 for the other two species.</p>
<p><small> <a href="https://www.cedricscherer.com/2021/06/06/visualizing-distributions-with-raincloud-plots-and-how-to-create-them-with-ggplot2/"><em>A blog post about raincloud plots vs violins</em></a> </small></p>
</section>
<section id="write-the-relationship-you-want-to-examine-in-the-form-of-a-research-question.-1" class="level2">
<h2 class="anchored" data-anchor-id="write-the-relationship-you-want-to-examine-in-the-form-of-a-research-question.-1">3. Write the relationship you want to examine in the form of a research question.</h2>
<ul>
<li>Null Hypothesis: There is no association between flipper length and species.</li>
<li>Alternate Hypothesis: There is an association between flipper length and species.</li>
</ul>
</section>
<section id="perform-an-appropriate-statistical-analysis-using-dr-ds-4-step-method.-1" class="level2">
<h2 class="anchored" data-anchor-id="perform-an-appropriate-statistical-analysis-using-dr-ds-4-step-method.-1">4. Perform an appropriate statistical analysis using Dr D’s 4 step method.</h2>
<p><strong>a. Define parameters</strong></p>
<p>Let <span class="math inline">\(\mu_{A}, \mu_{C}\)</span> and <span class="math inline">\(\mu_{G}\)</span> be the average flipper length for the <em>Adelie, Chinstrap</em> and <em>Gentoo</em> species of penguins respectively.</p>
<p><strong>b. State the null and alternative hypothesis as symbols</strong></p>
<p><span class="math inline">\(H_{0}: \mu_{A} = \mu_{C} = \mu_{G}\)</span><br>
<span class="math inline">\(H_{A}:\)</span> At least one <span class="math inline">\(\mu_{j}\)</span> is different.</p>
</section>
<section id="section-3" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="section-3"></h2>
<p><strong>c.&nbsp;State and justify the analysis model. Check assumptions.</strong></p>
<p>We are comparing means from multiple groups, so an ANOVA is the appropriate procedure. We need to check for independence, approximate normality and approximately equal variances across groups.</p>
<p><strong>Independence</strong>: We are assuming that each penguin was sampled independently of each other, and that the species themselves are independent of each other.</p>
<p><strong>Normality</strong>: The distributions of flipper length within each group are fairly normal</p>
<p><strong>Equal variances</strong>: Both the standard deviation and IQR (as measures of variability) are very similar across all groups.</p>
</section>
<section id="section-4" class="level2">
<h2 class="anchored" data-anchor-id="section-4"></h2>
<p><strong>d.&nbsp;Conduct the test and make a decision about the plausibility of the alternative hypothesis.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aov</span>(flipper_length_mm <span class="sc">~</span> species, <span class="at">data=</span>pen) <span class="sc">|&gt;</span> <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)    
species       2  52473   26237   594.8 &lt;2e-16 ***
Residuals   339  14953      44                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
2 observations deleted due to missingness</code></pre>
</div>
</div>
<p>The pvalue is very small, so there is evidence to support <span class="math inline">\(H_{a}\)</span>: at least one mean is different.</p>
</section>
<section id="write-a-conclusion-in-context-of-the-problem." class="level2">
<h2 class="anchored" data-anchor-id="write-a-conclusion-in-context-of-the-problem.">5. Write a conclusion in context of the problem.</h2>
<p>There is sufficient evidence to believe that the average flipper length is significantly different between the Adelie, Chinstrap and Gentoo species of penguins (p&lt;.0001).</p>
</section>
<section id="multiple-post-hoc-comparisons-which-group-is-different" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="multiple-post-hoc-comparisons-which-group-is-different">Multiple / Post-Hoc comparisons: Which group is different?</h2>
<ul>
<li>Run Post Hoc tests (“Tukeys HSD”, or “Duncan”), <em>only</em> if your ANOVA is significant.</li>
<li>The overall ANOVA can be significant and NOT have any significant differences when you look at the post hoc results. The reason is that the two analyses ask two different questions.
<ul>
<li>The ANOVA is testing the overall pattern of the data and asking if as a whole the explanatory variable has a relationship (or lack thereof) with the response variable.</li>
<li>The post hoc is asking if one level of the explanatory variable is significantly different than another for the response variable. The post hoc is not as sensitive to differences as the ANOVA.</li>
<li><strong>The family-wise error rate of</strong> <span class="math inline">\(\alpha\)</span> is maintained</li>
</ul></li>
<li>Differences in group means can be non-significant at the post hoc level, but significant at the ANOVA level.</li>
</ul>
</section>
<section id="section-5" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="section-5"></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(<span class="fu">aov</span>(flipper_length_mm <span class="sc">~</span> species, <span class="at">data=</span>pen))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = flipper_length_mm ~ species, data = pen)

$species
                      diff       lwr       upr p adj
Chinstrap-Adelie  5.869887  3.586583  8.153191     0
Gentoo-Adelie    27.233349 25.334376 29.132323     0
Gentoo-Chinstrap 21.363462 19.000841 23.726084     0</code></pre>
</div>
</div>
<p>The results of the Tukey HSD post-hoc test indicate that the average flipper length in mm is significantly different between all pairs of penguin species at the 5% significance level. Chinstrap has an average flipper length 5.87mm(3.59-8.15) larger than Adelie, whereas Gentoo has an average flipper length 27.23mm(25.33-29.13) larger than Adelie.</p>
</section>
<section id="coefficient-of-determination-r2-fracssgsst" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="coefficient-of-determination-r2-fracssgsst">Coefficient of Determination <span class="math inline">\(R^{2} = \frac{SSG}{SST}\)</span></h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)    
species       2  52473   26237   594.8 &lt;2e-16 ***
Residuals   339  14953      44                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
2 observations deleted due to missingness</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="dv">52473</span><span class="sc">/</span>(<span class="dv">52473</span> <span class="sc">+</span> <span class="dv">14953</span>)<span class="sc">*</span><span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 77.82309</code></pre>
</div>
</div>
<p>The coefficient of determination is interpreted as the % of the variation seen in the outcome that is due to subject level variation within each of the treatment groups. The strength of this measure can be thought of in a similar manner as the correlation coefficient <span class="math inline">\(\rho\)</span>, <span class="math inline">\(&lt;.3\)</span> indicates a poor fit, <span class="math inline">\(&lt;.5\)</span> indicates a medium fit, and <span class="math inline">\(&gt;.7\)</span> indicates a good fit.</p>
<blockquote class="blockquote">
<p>77.8% of the variation in flipper length can be explained by the species of penguin</p>
</blockquote>
</section>
<section id="non-parametric-tests" class="level2">
<h2 class="anchored" data-anchor-id="non-parametric-tests">Non-parametric tests</h2>
<ul>
<li>Many stat tests rely on assumptions that ensure the sample estimate can be modeled with a normal distribution.</li>
<li>What do you do if your assumptions aren’t met?</li>
<li>We can “relax” some of those assumptions and perform a more robust, but less powerful test.
<ul>
<li>less power means you need more data to draw a conclusion with the same amount of confidence.</li>
</ul></li>
<li>No detailed examples will be provided in these notes. You tend to learn/use these on an “as-needed” basis.</li>
</ul>
</section>
<section id="kruskal-wallis" class="level2 incremental">
<h2 class="incremental anchored" data-anchor-id="kruskal-wallis">Kruskal-Wallis</h2>
<ul>
<li>The <a href="https://en.wikipedia.org/wiki/Kruskal%E2%80%93Wallis_one-way_analysis_of_variance">Kruskal-Wallis</a> test is the most common <strong>non-parametric</strong> method for testing whether or not groups of observations come from the same overall distribution.</li>
<li>By comparing the <em>medians</em> instead of the means, we can remove the normality assumption on the residuals.</li>
<li>Null hypothesis is now that the medians of all groups are equal vs at least one population median is different.</li>
<li><a href="http://www.sthda.com/english/wiki/kruskal-wallis-test-in-r">Ref on how to do this in R from STHDA</a></li>
</ul>
</section>
</section>
<section id="categorical-outcome-categorical-covariate" class="level1" data-background-color="#6c972b">
<h1 data-background-color="#6c972b">Categorical Outcome ~ Categorical Covariate</h1>
<section id="opening-remarks" class="level2">
<h2 class="anchored" data-anchor-id="opening-remarks">Opening Remarks</h2>
<p>If we are only concerned with testing the hypothesis that the proportion of successes between two groups are equal <span class="math inline">\(p_{1}-p_{2}=0\)</span>, we can leverage the Normal distribution and conduct a Z-test for two proportions.</p>
<p>However in this class we will use the more generalizable model via Chi-squared test of association/equal proportions.</p>
</section>
<section id="chi-squared-test-of-equal-proportions-ref-ascn-section-5.5" class="level2">
<h2 class="anchored" data-anchor-id="chi-squared-test-of-equal-proportions-ref-ascn-section-5.5">Chi-squared test of equal proportions <a href="https://norcalbiostat.github.io/AppliedStatistics_notes/bv-chisq.html">(Ref: ASCN Section 5.5)</a></h2>
<p>A 30-year study was conducted with nearly 90,000 female participants. (Miller AB. 2014) During a 5-year screening period, each woman was randomized to one of two groups: in the first group, women received regular mammograms to screen for breast cancer, and in the second group, women received regular non-mammogram breast cancer exams. No intervention was made during the following 25 years of the study, and we’ll consider death resulting from breast cancer over the full 30-year period.</p>
</section>
<section id="results-from-study" class="level2">
<h2 class="anchored" data-anchor-id="results-from-study">Results from study</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Alive</th>
<th style="text-align: right;">Dead</th>
<th style="text-align: right;">Sum</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control</td>
<td style="text-align: right;">44405</td>
<td style="text-align: right;">505</td>
<td style="text-align: right;">44910</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mammogram</td>
<td style="text-align: right;">44425</td>
<td style="text-align: right;">500</td>
<td style="text-align: right;">44925</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sum</td>
<td style="text-align: right;">88830</td>
<td style="text-align: right;">1005</td>
<td style="text-align: right;">89835</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The independent/explanatory variable is treatment (additional mammograms), and the dependent/response variable is death from breast cancer. Are these measures associated?</p>
</section>
<section id="assume-independenceno-association" class="level2 smaller incremental">
<h2 class="smaller incremental anchored" data-anchor-id="assume-independenceno-association">Assume independence/no association</h2>
<ul>
<li>If mammograms are more effective than non-mammogram breast cancer exams, then we would expect to see additional deaths from breast cancer in the control group (there is a relationship).</li>
<li>If mammograms are not as effective as regular breast cancer exams, we would expect to see no difference in breast cancer deaths in the two groups (there is no relationship).</li>
<li>Need to figure out how many deaths would be <strong>expected</strong>, if there was no relationship between treatment death by breast cancer,</li>
<li>Then examine the <strong>residuals</strong> - the difference between the observed counts and the expected counts in each cell.</li>
</ul>
</section>
<section id="table-notation" class="level2">
<h2 class="anchored" data-anchor-id="table-notation">Table notation</h2>
<p>Tables can be described by <span class="math inline">\(i\)</span> rows and <span class="math inline">\(j\)</span> columns. So the cell in the top left is <span class="math inline">\(i=1\)</span> and <span class="math inline">\(j=1\)</span>.</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;"><span class="math inline">\(O_{ij}\)</span></th>
<th style="text-align: center;">Alive</th>
<th style="text-align: center;">Dead</th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mammo</td>
<td style="text-align: center;"><span class="math inline">\(n_{11}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_{12}\)</span> | <span class="math inline">\(n_{1.}\)</span></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">Control</td>
<td style="text-align: center;"><span class="math inline">\(n_{21}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_{22}\)</span> | <span class="math inline">\(n_{2.}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: center;"><span class="math inline">\(n_{.1}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_{.2}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(N\)</span></td>
</tr>
</tbody>
</table>
<p>In our DATA = MODEL + RESIDUAL framework, the DATA (<span class="math inline">\(n_{11}, n_{12}\)</span>, etc)is the observed counts <span class="math inline">\(O_{ij}\)</span> and the MODEL is the expected counts <span class="math inline">\(E_{ij}\)</span>.</p>
</section>
<section id="calculating-the-expected-count" class="level2">
<h2 class="anchored" data-anchor-id="calculating-the-expected-count">Calculating the expected count</h2>
<p>Since we assume the variables are independent (unless the data show otherwise) the expected count for each cell is calculated as the row total times the column total for that cell, divided by the overall total.</p>
<p><span class="math display">\[E_{ij} = \frac{n_{i.}n_{.j}}{N}\]</span></p>
<p>In a probability framework this is stated as two variables <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are independent if <span class="math inline">\(P(A \cap B) = P(A)*P(B) = \frac{n_{i.}}{N}*\frac{n_{.j}}{N}\)</span></p>
</section>
<section id="calculating-the-residuals" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="calculating-the-residuals">Calculating the residuals</h2>
<p>The residuals are calculated as <span class="math inline">\((O_{ij} - E_{ij})\)</span></p>
<div class="columns">
<div class="column" style="width:50%;">
<p>Expected</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(a<span class="sc">$</span>Tx, a<span class="sc">$</span>Outcome)<span class="sc">$</span>expected <span class="sc">%&gt;%</span> <span class="fu">kable</span>(<span class="at">digits=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Alive</th>
<th style="text-align: right;">Dead</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control</td>
<td style="text-align: right;">44407.58</td>
<td style="text-align: right;">502.42</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mammogram</td>
<td style="text-align: right;">44422.42</td>
<td style="text-align: right;">502.58</td>
</tr>
</tbody>
</table>
</div>
</div>
</div><div class="column" style="width:50%;">
<p>Residuals</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(a<span class="sc">$</span>Tx, a<span class="sc">$</span>Outcome)<span class="sc">$</span>residuals <span class="sc">%&gt;%</span> <span class="fu">kable</span>(<span class="at">digits=</span><span class="dv">3</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Alive</th>
<th style="text-align: right;">Dead</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control</td>
<td style="text-align: right;">-0.012</td>
<td style="text-align: right;">0.115</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mammogram</td>
<td style="text-align: right;">0.012</td>
<td style="text-align: right;">-0.115</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p>If mammograms were not associated with survival, there were 0.01 fewer people still alive than expected, and 0.11 more people dead.</p>
</section>
<section id="chi2-test-statistic" class="level2">
<h2 class="anchored" data-anchor-id="chi2-test-statistic"><span class="math inline">\(\chi^2\)</span> test statistic</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>The <span class="math inline">\(\chi^2\)</span> test statistic is defined as the sum of the squared residuals, divided by the expected counts, and follows a <span class="math inline">\(\chi^2\)</span> distribution with degrees of freedom (#rows -1)(#cols -1).</p>
<p><span class="math display">\[ \sum_{ij}\frac{(O_{ij}-E_{ij})^{2}}{E_{ij}} \]</span></p>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dist_chisq</span>(<span class="at">chi2=</span>.<span class="dv">027</span>, <span class="at">deg.f=</span><span class="dv">1</span>, <span class="at">geom.colors=</span><span class="fu">c</span>(<span class="st">"#FDE725FF"</span>, <span class="st">"#440154FF"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lec07b-bivariate_modeling_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>In this example, the test statistic was 0.017 with p-value 0.895.</p>
<p>So there is not enough reason to believe that mammograms in addition to regular exams are associated with a reduced risk of death due to breast cancer.</p>
<p>This example demonstrated how we examine the residuals to see how closely our DATA fits a hypothesized MODEL.</p>
</section>
<section id="example-income-and-general-health" class="level2">
<h2 class="anchored" data-anchor-id="example-income-and-general-health">Example: Income and General Health</h2>
<p>Using the Addhealth data set, what can we say about the relationship between smoking status and a person’s perceived level of general health?</p>
<p>Is there an association between lifetime smoking status and perceived general health?</p>
</section>
<section id="identify-response-and-explanatory-variables-2" class="level2">
<h2 class="anchored" data-anchor-id="identify-response-and-explanatory-variables-2">1. Identify response and explanatory variables</h2>
<ul>
<li>The binary explanatory variable is whether the person has ever smoked an entire cigarette (<code>eversmoke_c</code>).</li>
<li>The categorical explanatory variable is the person’s general health (<code>genhealth</code>) and has levels “Excellent”, “Very Good”, “Good”, “Fair”, and “Poor”.</li>
</ul>
</section>
<section id="visualize-and-summarise-bivariate-relationship-2" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="visualize-and-summarise-bivariate-relationship-2">2. Visualize and summarise bivariate relationship</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_xtab</span>(<span class="at">grp=</span>addhealth<span class="sc">$</span>eversmoke_c, <span class="at">x=</span>addhealth<span class="sc">$</span>genhealth, </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">show.total =</span> <span class="cn">FALSE</span>, <span class="at">margin=</span><span class="st">"row"</span>, <span class="at">legend.title=</span><span class="st">""</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lec07b-bivariate_modeling_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The percentage of smokers seems to increase as the general health status decreases. Almost three-quarters (73%, n=40) of those reporting poor health have smoked an entire cigarette at least once in their life compared to 59% (n=573) of those reporting excellent health.</p>
</section>
<section id="b.-other-ways-to-visualize-this-fyi-only" class="level2">
<h2 class="anchored" data-anchor-id="b.-other-ways-to-visualize-this-fyi-only">2b. Other ways to visualize this (FYI only)</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>addhealth <span class="sc">%&gt;%</span> </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(genhealth) <span class="sc">%&gt;%</span> </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">p =</span> <span class="fu">mean</span>(eversmoke_c <span class="sc">==</span> <span class="st">"Smoked at least once"</span>, <span class="at">na.rm=</span><span class="cn">TRUE</span>)<span class="sc">*</span><span class="dv">100</span>, </span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">n =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>genhealth, <span class="at">y=</span>p, <span class="at">color=</span>genhealth)) <span class="sc">+</span> </span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">size =</span> n)) <span class="sc">+</span> </span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits=</span><span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">100</span>)) <span class="sc">+</span> </span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">x=</span>genhealth, <span class="at">xend=</span>genhealth, <span class="at">y=</span><span class="dv">0</span>, <span class="at">yend=</span>p)) <span class="sc">+</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_discrete</span>(<span class="at">guide=</span><span class="st">"none"</span>) <span class="sc">+</span> <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Proportion of smokers"</span>) <span class="sc">+</span> </span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Perceived General Health"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lec07b-bivariate_modeling_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>addhealth <span class="sc">%&gt;%</span> </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(genhealth, eversmoke_c) <span class="sc">%&gt;%</span> </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>() <span class="sc">%&gt;%</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(genhealth)<span class="sc">%&gt;%</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">p =</span> n<span class="sc">/</span><span class="fu">sum</span>(n)<span class="sc">*</span><span class="dv">100</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>genhealth, <span class="at">y=</span>p, <span class="at">fill=</span>eversmoke_c, </span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">label =</span> <span class="fu">paste0</span>(<span class="fu">round</span>(p, <span class="dv">1</span>), <span class="st">"%"</span>))) <span class="sc">+</span> </span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span> <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">name =</span> <span class="st">""</span>) <span class="sc">+</span> </span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">position=</span><span class="fu">position_stack</span>(<span class="fl">0.5</span>)) <span class="sc">+</span> </span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Proportion of smokers"</span>) <span class="sc">+</span> </span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Perceived General Health"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lec07b-bivariate_modeling_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
<p><small> These methods pre-calculate the proportions first, and then put them on a ggplot canvas. As you build your expertise with R/Ggplot you will find yourself wanting to enhance or move away from the “pre-packaged” plots from <code>sjPlot</code> and <code>ggpubr</code>. </small></p>
</section>
<section id="write-the-relationship-you-want-to-examine-in-the-form-of-a-research-question.-2" class="level2">
<h2 class="anchored" data-anchor-id="write-the-relationship-you-want-to-examine-in-the-form-of-a-research-question.-2">3. Write the relationship you want to examine in the form of a research question.</h2>
<ul>
<li>Null Hypothesis: The proportion of smokers is the same across all levels of general health.</li>
<li>Alternate Hypothesis: At least one group has a different proportion of smokers compared to the other general health groups.</li>
</ul>
</section>
<section id="perform-an-appropriate-statistical-analysis-using-dr-ds-4-step-method.-2" class="level2">
<h2 class="anchored" data-anchor-id="perform-an-appropriate-statistical-analysis-using-dr-ds-4-step-method.-2">4. Perform an appropriate statistical analysis using Dr D’s 4 step method.</h2>
<p><strong>a. Define parameters</strong></p>
<p>Let <span class="math inline">\(p_{1}, p_{2}, \ldots, p_{5}\)</span> be the true proportion of smokers in each of the 5 health categories: (1) Excellent to (5) Poor.</p>
<p><br>
</p>
<p><strong>b. State the null and alternative hypothesis as symbols</strong></p>
<p><span class="math inline">\(H_{0}: p_{1} = p_{2} = \ldots p_{5}\)</span><br>
<span class="math inline">\(H_{A}:\)</span> At least one <span class="math inline">\(p_{j}\)</span> is different.</p>
</section>
<section id="section-6" class="level2">
<h2 class="anchored" data-anchor-id="section-6"></h2>
<p><strong>c.&nbsp;State and justify the analysis model. Check assumptions.</strong></p>
<p>I will conduct a <span class="math inline">\(\chi^{2}\)</span> test of association. There is at least 10 observations in each combination of smoking status and general health.</p>
<p><strong>d.&nbsp;Conduct the test and make a decision about the plausibility of the alternative hypothesis.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(addhealth<span class="sc">$</span>genhealth, addhealth<span class="sc">$</span>eversmoke_c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  addhealth$genhealth and addhealth$eversmoke_c
X-squared = 30.795, df = 4, p-value = 3.371e-06</code></pre>
</div>
</div>
<p>We have strong evidence in favor of the alternative hypothesis, p&lt;.0001</p>
</section>
<section id="write-a-conclusion-in-context-of-the-problem.-1" class="level2">
<h2 class="anchored" data-anchor-id="write-a-conclusion-in-context-of-the-problem.-1">5. Write a conclusion in context of the problem.</h2>
<p>We can conclude that there is an association between ever smoking a cigarette in their life and perceived general health (<span class="math inline">\(\chi^{2} = 30.8, df=4, p&lt;.0001\)</span>).</p>
</section>
<section id="multiple-comparisons-which-group-is-different" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="multiple-comparisons-which-group-is-different">Multiple comparisons: Which group is different?</h2>
<p>Just like with ANOVA, if we find that the Chi-squared test indicates that at least one proportion is different from the others, it’s our job to figure out which ones might be different! We will analyze the residuals to accomplish this.</p>
</section>
<section id="examine-the-residuals" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="examine-the-residuals">Examine the residuals</h2>
<p>The residuals (<span class="math inline">\(O_{ij} - E_{ij}\)</span>) are automatically stored in the model output. You can either print them out and look at the values directly or create a plot. You’re looking for combinations that have much higher, or lower expected proportions.</p>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>health.smoke.model <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(addhealth<span class="sc">$</span>genhealth, addhealth<span class="sc">$</span>eversmoke_c)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>health.smoke.model<span class="sc">$</span>residuals <span class="sc">|&gt;</span> <span class="fu">round</span>(<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   addhealth$eversmoke_c
addhealth$genhealth Never Smoked Smoked at least once
          Excellent         3.45                -2.52
          Very good         0.48                -0.35
          Good             -2.44                 1.78
          Fair             -1.06                 0.77
          Poor             -0.94                 0.69</code></pre>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>plot.residuals <span class="ot">&lt;-</span> health.smoke.model<span class="sc">$</span>residuals <span class="sc">%&gt;%</span> <span class="fu">data.frame</span>()</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plot.residuals, <span class="fu">aes</span>(<span class="at">x=</span>addhealth.genhealth, <span class="at">y=</span>addhealth.eversmoke_c)) <span class="sc">+</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">geom_raster</span>(<span class="fu">aes</span>(<span class="at">fill=</span>Freq)) <span class="sc">+</span>  <span class="fu">scale_fill_viridis_c</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lec07b-bivariate_modeling_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
<p>The proportion of non-smokers in the excellent health category is much higher than expected if there were no relationship between these two variables.</p>
</section>
<section id="all-pairwise-comparisons" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="all-pairwise-comparisons">All pairwise comparisons</h2>
<div class="columns">
<div class="column" style="width:70%;">
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># library(rcompanion)</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>smoke.by.genhealth <span class="ot">&lt;-</span> <span class="fu">table</span>(addhealth<span class="sc">$</span>genhealth, addhealth<span class="sc">$</span>eversmoke_c)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>rcompanion<span class="sc">::</span><span class="fu">pairwiseNominalIndependence</span>(smoke.by.genhealth, <span class="at">fisher =</span> <span class="cn">FALSE</span>, <span class="at">gtest=</span><span class="cn">FALSE</span>) <span class="sc">|&gt;</span> <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Comparison</th>
<th style="text-align: right;">p.Chisq</th>
<th style="text-align: right;">p.adj.Chisq</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Excellent : Very good</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">0.008</td>
</tr>
<tr class="even">
<td style="text-align: left;">Excellent : Good</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Excellent : Fair</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">0.005</td>
</tr>
<tr class="even">
<td style="text-align: left;">Excellent : Poor</td>
<td style="text-align: right;">0.055</td>
<td style="text-align: right;">0.110</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Very good : Good</td>
<td style="text-align: right;">0.009</td>
<td style="text-align: right;">0.022</td>
</tr>
<tr class="even">
<td style="text-align: left;">Very good : Fair</td>
<td style="text-align: right;">0.167</td>
<td style="text-align: right;">0.278</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Very good : Poor</td>
<td style="text-align: right;">0.269</td>
<td style="text-align: right;">0.384</td>
</tr>
<tr class="even">
<td style="text-align: left;">Good : Fair</td>
<td style="text-align: right;">0.886</td>
<td style="text-align: right;">0.886</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Good : Poor</td>
<td style="text-align: right;">0.630</td>
<td style="text-align: right;">0.700</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fair : Poor</td>
<td style="text-align: right;">0.601</td>
<td style="text-align: right;">0.700</td>
</tr>
</tbody>
</table>
</div>
</div>
</div><div class="column" style="width:30%;">
<p>Using the adjusted (for multiple comparisons) p-value column, the proportion of smokers in the Excellent group (41.3%) is significantly different from nearly all other groups (35.4% for Very Good, 31.3% for Good, 31.8% for Fair).</p>
<p>But why is it not significantly different from the 27.3% in the Poor group?</p>
</div>
</div>
</section>
<section id="the-effect-of-small-sample-sizes" class="level2">
<h2 class="anchored" data-anchor-id="the-effect-of-small-sample-sizes">The effect of small sample sizes</h2>
<p>Why is 41.3% significantly different from 35.4%, but NOT different from 27.3%?</p>
<p>The standard error is always dependent on the sample size. Here, the number of individuals in the Poor health category is much smaller compared to all other groups - so the margin of error will be larger - making it less likely to be statistically significantly different from other groups.</p>
<p>When you have a small numbers (n&lt;10) in one or more cells the distribution of the test statistic can no longer be modeled well using the <span class="math inline">\(\chi^{2}\)</span> distribution. So we again go to a non-parametric test that uses a randomization based method.</p>
</section>
<section id="fishers-exact-test" class="level2">
<h2 class="anchored" data-anchor-id="fishers-exact-test">Fishers Exact Test</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(addhealth<span class="sc">$</span>genhealth, addhealth<span class="sc">$</span>eversmoke_c, </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">simulate.p.value =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data with simulated p-value (based on 2000 replicates)

data:  addhealth$genhealth and addhealth$eversmoke_c
p-value = 0.0004998
alternative hypothesis: two.sided</code></pre>
</div>
</div>
<p>Then you can use the <code>pairwiseNominalIndependence</code> function for all pairwise comparisons again, with the <code>fisher</code> argument set to <code>TRUE</code>.</p>
<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><small>Note: the <code>simulate.p.value = TRUE</code> argument here is only needed if the randomization space is larger than your workspace. R will let you know when this is needed.</small></p>
</div>
</div>
</div>
</section>
<section id="chi-squared-test-of-associationindependence" class="level2">
<h2 class="anchored" data-anchor-id="chi-squared-test-of-associationindependence">Chi-Squared test of Association/Independence</h2>
<p>We can still use the <span class="math inline">\(\chi^{2}\)</span> test of association to compare categorical variables with more than 2 levels. In this case we generalize the statement to ask: <strong>Is the distribution of 1 variable the same across levels of another variable?</strong>. In this sense, it is very much like an ANOVA.</p>
<p>Mathematically the <span class="math inline">\(\chi^{2}\)</span> test of association is the exact same as a test of equal proportions.</p>
</section>
<section id="example" class="level2">
<h2 class="anchored" data-anchor-id="example">Example</h2>
<p>Let’s analyze the relationship between a person’s income and perceived level of general health.</p>
<p>The categorical explanatory variable is income, binned into 4 ranges (<code>income_cat</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>addhealth<span class="sc">$</span>income_cat <span class="ot">&lt;-</span> Hmisc<span class="sc">::</span><span class="fu">cut2</span>(addhealth<span class="sc">$</span>income, <span class="at">g =</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="state-hypothesis" class="level2">
<h2 class="anchored" data-anchor-id="state-hypothesis">State Hypothesis</h2>
<ul>
<li>The income distribution is the same in each of the general health categories (no association)</li>
<li>The income distribution differs for at least one of the general health categories (association)</li>
</ul>
</section>
<section id="visualize-the-relationship" class="level2">
<h2 class="anchored" data-anchor-id="visualize-the-relationship">Visualize the relationship</h2>
<div class="columns">
<div class="column" style="width:60%;">
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_xtab</span>(<span class="at">grp=</span>addhealth<span class="sc">$</span>income_cat,</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">x=</span>addhealth<span class="sc">$</span>genhealth, </span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">show.total =</span> <span class="cn">FALSE</span>, <span class="at">margin=</span><span class="st">"row"</span>,</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">legend.title=</span><span class="st">""</span>) <span class="sc">+</span> </span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"top"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lec07b-bivariate_modeling_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div><div class="column" style="width:40%;">
<p><small> The income distribution is nearly flat for who rate themselves in excellent or very good condition. However, the proportion of individuals in the lower income categories increase as perceived general health decreases. Over 80% of those that rate themselves as in Poor condition have an annual income less than $35,500.</small></p><small>
</small><p><small>Since there are very small cell sizes, we will use a Fishers Exact test. </small></p>
</div>
</div>
</section>
<section id="test-the-relationship-make-a-conclusion." class="level2">
<h2 class="anchored" data-anchor-id="test-the-relationship-make-a-conclusion.">Test the relationship &amp; make a conclusion.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(addhealth<span class="sc">$</span>genhealth, addhealth<span class="sc">$</span>income_cat, </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">simulate.p.value =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data with simulated p-value (based on 2000 replicates)

data:  addhealth$genhealth and addhealth$income_cat
p-value = 0.0004998
alternative hypothesis: two.sided</code></pre>
</div>
</div>
<p>There is sufficient evidence to conclude that the distribution of income is not the same across all general health status categories.</p>
</section>
<section id="other-analysis-for-categorical-variables" class="level2">
<h2 class="anchored" data-anchor-id="other-analysis-for-categorical-variables">Other analysis for categorical variables</h2>
<p>There is a slew of methods to analyze categorical data, we can’t get into them all. To learn more start with Categorical Data Analysis by Alan Agresti, who has written <em>extensively</em> on the subject.</p>
<p>This R companion page also looks very useful http://rcompanion.org/handbook/H_01.html and where I got the <code>pairwiseNominalIndependence</code> function from.</p>
</section>
</section>
<section id="quantitative-outcome-quantitative-covariate" class="level1" data-background-color="#6c972b">
<h1 data-background-color="#6c972b">Quantitative Outcome ~ Quantitative Covariate</h1>
<section id="opening-remarks-1" class="level2">
<h2 class="anchored" data-anchor-id="opening-remarks-1">Opening Remarks</h2>
<p>The PMA6 textbook (Chapter 7) goes into great detail on this topic, since regression is typically the basis for all advanced models.</p>
<p>The book also distinguishes between a “fixed-x” case, where the values of the explanatory variable <span class="math inline">\(x\)</span> only take on pre-specified values, and a “variable-x” case, where the values of <span class="math inline">\(x\)</span> are observations from a population distribution of X’s.</p>
<p>This latter case is what we will be concerning ourselves with.</p>
</section>
<section id="bivariate-distribution" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="bivariate-distribution">Bivariate distribution</h2>
<p>The <em>bivariate distribution</em> describes how of <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are jointly distributed, and is best interpreted by a look at the scatter diagram.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>y.bar <span class="ot">&lt;-</span> <span class="fu">mean</span>(pen<span class="sc">$</span>bill_length_mm, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>x.bar <span class="ot">&lt;-</span> <span class="fu">mean</span>(pen<span class="sc">$</span>body_mass_g, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(pen, <span class="fu">aes</span>(<span class="at">x=</span>body_mass_g, <span class="at">y=</span>bill_length_mm)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> y.bar) <span class="sc">+</span> </span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> x.bar) </span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>ggExtra<span class="sc">::</span><span class="fu">ggMarginal</span>(p, <span class="at">type=</span><span class="st">"histogram"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="lec07b-bivariate_modeling_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>If <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> come from independent normal distributions, the pair <span class="math inline">\((X,Y)\)</span> comes from a <em>bivariate normal distribution</em>, and the data will tend to cluster around the means of <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>.</p>
</section>
<section id="ellipse-of-concentration" class="level2">
<h2 class="anchored" data-anchor-id="ellipse-of-concentration">Ellipse of concentration</h2>
<p>We can view the <em>ellipse of concentration</em> as measure of strength and direction of the correlation between X and Y.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>ggpubr<span class="sc">::</span><span class="fu">ggscatter</span>(pen, <span class="at">x =</span> <span class="st">"body_mass_g"</span>, <span class="at">y =</span> <span class="st">"bill_length_mm"</span>,</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>   <span class="at">ellipse =</span> <span class="cn">TRUE</span>, <span class="at">mean.point =</span> <span class="cn">TRUE</span>,</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>   <span class="at">star.plot =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="lec07b-bivariate_modeling_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>See PMA6 Figure 7.5 for more examples.</p>
</section>
<section id="correlation" class="level2">
<h2 class="anchored" data-anchor-id="correlation">Correlation</h2>
<p>The <strong>correlation coefficient</strong> is designated by <span class="math inline">\(r\)</span> for the sample correlation, and <span class="math inline">\(\rho\)</span> for the population correlation. The correlation is a measure of the strength and direction of a <em>linear relationship</em> between two variables.</p>
<p>The correlation ranges from +1 to -1. A correlation of +1 means that there is a perfect, positive linear relationship between the two variables. A correlation of -1 means there is a perfect, negative linear relationship between the two variables. In both cases, knowing the value of one variable, you can perfectly predict the value of the second.</p>
</section>
<section id="strength-of-the-correlation" class="level2">
<h2 class="anchored" data-anchor-id="strength-of-the-correlation">Strength of the correlation</h2>
<p>Here are rough estimates for interpreting the strengths of correlations based on the magnitude of <span class="math inline">\(r\)</span>.</p>
<ul>
<li><span class="math inline">\(|r| \geq 0.7\)</span>: Very strong relationship</li>
<li><span class="math inline">\(0.4 \leq |r| &lt; 0.7\)</span>: Strong relationship</li>
<li><span class="math inline">\(0.3 \leq |r| &lt; 0.4\)</span>: Moderate relationship</li>
<li><span class="math inline">\(0.2 \leq |r| &lt; 0.3:\)</span> Weak relationship</li>
<li><span class="math inline">\(|r| &lt; 0.2:\)</span> Negligible or no relationship</li>
</ul>
</section>
<section id="as-a-measure-of-model-fit" class="level2">
<h2 class="anchored" data-anchor-id="as-a-measure-of-model-fit">As a measure of model fit</h2>
<p>When we square <span class="math inline">\(r\)</span> (i.e.&nbsp;<span class="math inline">\(R^{2}\)</span>), it tells us what proportion of the variability in one variable that is described by variation in the second variable.</p>
<p><br>
</p>
<p>Yes, this is mathematically the same as the coefficient of determination we saw in ANOVA.</p>
</section>
<section id="pearson-test-of-correlation" class="level2">
<h2 class="anchored" data-anchor-id="pearson-test-of-correlation">Pearson test of correlation</h2>
<p>To test for a <em>linear</em> correlation between two variables we use the <strong>Pearson correlation coefficient</strong> which is defined as the covariance of the two variables divided by the product of their standard deviations.</p>
<p><span class="math display">\[
\rho_{X,Y} = \frac{cov(X,Y)}{\sigma_{x}\sigma_{Y}}
\]</span></p>
<p>There are many modifications and adjustments to this measure that we will not get into detail with. We are using correlation as a stepping stool to Linear Regression.</p>
</section>
<section id="example-body-mass-and-bill-length-of-penguins" class="level2">
<h2 class="anchored" data-anchor-id="example-body-mass-and-bill-length-of-penguins">Example: Body mass and bill length of penguins</h2>
<section id="identify-response-and-explanatory-variables-3" class="level3">
<h3 class="anchored" data-anchor-id="identify-response-and-explanatory-variables-3">1. Identify response and explanatory variables</h3>
<ul>
<li>The quantitative explanatory variable is body mass (g)</li>
<li>The quantitative response variable is bill length (mm)</li>
</ul>
</section>
</section>
<section id="visualize-and-summarise-bivariate-relationship-3" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="visualize-and-summarise-bivariate-relationship-3">2. Visualize and summarise bivariate relationship</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pen, <span class="fu">aes</span>(<span class="at">x=</span>body_mass_g, <span class="at">y=</span>bill_length_mm)) <span class="sc">+</span> </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lec07b-bivariate_modeling_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(pen<span class="sc">$</span>body_mass_g, pen<span class="sc">$</span>bill_length_mm, <span class="at">use =</span> <span class="st">"pairwise.complete.obs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5951098</code></pre>
</div>
</div>
</div><div class="column" style="width:50%;">
<p>There is a strong, positive, mostly linear relationship between the body mass (g) of penguins and their bill length (mm) (r=.595).</p>
</div>
</div>
</section>
<section id="write-the-relationship-you-want-to-examine-in-the-form-of-a-research-question.-3" class="level2">
<h2 class="anchored" data-anchor-id="write-the-relationship-you-want-to-examine-in-the-form-of-a-research-question.-3">3. Write the relationship you want to examine in the form of a research question.</h2>
<ul>
<li>Null Hypothesis: There is no correlation between the body mass and bill length of penguins.</li>
<li>Alternate Hypothesis: There is a correlation between the body mass and bill length of penguins.</li>
</ul>
</section>
<section id="perform-an-appropriate-statistical-analysis-using-dr-ds-4-step-method.-3" class="level2">
<h2 class="anchored" data-anchor-id="perform-an-appropriate-statistical-analysis-using-dr-ds-4-step-method.-3">4. Perform an appropriate statistical analysis using Dr D’s 4 step method.</h2>
<p><strong>a. Define parameters</strong> Let <span class="math inline">\(\rho\)</span> be the true correlation between body mass and bill length of penguins.</p>
<p><strong>b. State the null and alternative hypothesis as symbols</strong></p>
<p><span class="math inline">\(H_{0}: \rho=0 \qquad \qquad H_{A}: \rho \neq 0\)</span></p>
<p><strong>c.&nbsp;State and justify the analysis model.</strong></p>
<p>Pearsons test of correlation will be conducted. This is appropriate because both variables are quantitative, the relationship between variables are reasonably linear, and the sample size is large.</p>
</section>
<section id="section-7" class="level2">
<h2 class="anchored" data-anchor-id="section-7"></h2>
<p><strong>d.&nbsp;Conduct the test and make a decision about the plausibility of the alternative hypothesis.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(pen<span class="sc">$</span>body_mass_g, pen<span class="sc">$</span>bill_length_mm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  pen$body_mass_g and pen$bill_length_mm
t = 13.654, df = 340, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.5220040 0.6595358
sample estimates:
      cor 
0.5951098 </code></pre>
</div>
</div>
<p>The p-value is very small, there is evidence in favor of a non-zero correlation.</p>
</section>
<section id="write-a-conclusion-in-context-of-the-problem.-2" class="level2">
<h2 class="anchored" data-anchor-id="write-a-conclusion-in-context-of-the-problem.-2">5. Write a conclusion in context of the problem.</h2>
<p>There was a statistically significant and strong correlation between the body mass (g) and bill length (mm) of penguins (r = 0.595, 95%CI .5220-.6595, p &lt; .0001). The significant positive correlation shows that as the body mass of a penguin increases so does the bill length. These results suggest that 35% (95% CI: 27.2-43.5) of the variance in bill length can be explained by the body mass of the penguin.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">This site is built with 💚 and <a href="https://quarto.org/">Quarto</a> by <a href="www.norcalbiostat.com">Robin Donatello</a>.</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>