{
  "hash": "5e8d3fc466899a9c621aaaf4cb4fef87",
  "result": {
    "markdown": "---\ntitle: \"HW 04: Describing Distributions\"\nsubtitle: \"Let the data be beautiful\"\nexecute:\n  echo: true\n  warning: false\n  message: false\nformat:\n  html: default\n  pdf: default\n---\n\n\n# Purpose\n\nThere are a variety of conventional ways to visualize data - tables, histograms, bar graphs, etc. The purpose is always to examine the distribution of variables related to your research question. You will create a plot, follow up each graphic with a table of summary statistics (for quantitative variables) or frequency and proportion table (for categorical), and then a summary paragraph that brings it all together. \n\n----\n\n# Instructions \n\n\n**PART 1**: Completely describe 2 categorical and 2 quantitative variables using all of the following: \n\n* An explanation of what the variable is, and how it is measured. \n* A table of summary statistics,\n* An appropriate plot with titles and axes labels (include both a histogram and boxplot for numeric data)\n* A short paragraph description in full complete English sentences. \n    \n**PART 2**: Create an all-inclusive summary table using the `tbl_summary()` function inside the `gtsummary` package. See slide 10 in the lec04 notes or the [`gtsummary` tutorial](https://www.danieldsjoberg.com/gtsummary/articles/tbl_summary.html). Include all 4 variables that were analyzed as part of this assignment. \n\n\n\n\nTo guide your description of this distribution try to include the following information:\n\n* What is the trend in the data? What exactly does the chart show? (Use the chart title to help you answer this question)\n* Describe the location of the bulk of the data. Measures include\n    - Measures of center: mean/median\n    - IQR as Q3 and Q1 (i.e., 50% of the data lie between $x_{1}$ and $x_{2}$)\n    - N and (%) for categorical data for the largest category. \n* Describe the shape (for quantitative measures only):\n    - Symmetry/Skewness - Is it symmetric, skewed right, or skewed left?\n    - Modality - Is it uniform, unimodal, or bimodal?       \n* Describe the spread or variability in the data\n    - Appropriate measures include range, standard deviation, IQR for continuous data\n    - For categorical data describe if distribution is spread across multiple response categories or mainly only one.\n* Describe the outliers (note: there may not be any for every graph). Continuous data only.\n    - Are there any outliers for the variable?\n    - If yes, are these true outliers or false (due to data management or input error) outliers? \n    (This could alert you to missing codes like -77 or 99 that need to be set to missing)\n\n----\n\n# Submission instructions\n\n* Use the template provided: [[QMD]](_templates/hw04_describing_distributions_template.qmd)\n  - Right click and 'save as', put this in your `scripts` folder\n* Upload your draft PDF to Canvas by the due date. \n\n\n\n----\n\n\\newpage \n\n# Example - Part I\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load libraries\nlibrary(tidyverse)\nlibrary(sjPlot)\nlibrary(ggpubr)\n\nload(here::here(\"data/depression_clean.Rdata\")) # your import line will look something like this\n```\n:::\n\n\n> text written like this are example student submission text\n\n## Basic categorical\nDraft style plot, direct computer output showing/copied. Poor grammar and/or sentence structure, no attempt at explaining what the variable means, extra unnecessary or incorrect information included. Typos. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(clean$depressed)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n    depressed not depressed \n           45           249 \n```\n:::\n:::\n\n\n> There are 249 not depressed and 45 depressed. \n\n## Proficient categorical\nCleaned up plot, full English sentences, useful text formatting of variable names and levels. Explained what the variable was named and what it measured. \n\n> The `depressed` variable is an indicator variable created from the CESD scale to identify potential clinical depression. This variable has two levels: `depressed` or `not depressed`. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_frq(clean$depressed)\n```\n\n::: {.cell-output-display}\n![](hw04-describing_distributions_files/figure-html/unnamed-chunk-3-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n> The majority of respondents in this data set are not considered depressed; 84.7% (n=249) individuals did not meet the threshold on the CESD scale to indicate potential clinical depression.  \n\n\\newpage\n\n## Basic quantitative \nA \"for your eyes only\" quality plot, minimal description of characteristics, no information about the variable provided. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(clean$age)\n```\n\n::: {.cell-output-display}\n![](hw04-describing_distributions_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n\n```{.r .cell-code}\nsummary(clean$age)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  18.00   28.00   42.50   44.41   59.00   89.00 \n```\n:::\n\n```{.r .cell-code}\nsd(clean$age)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.08544\n```\n:::\n:::\n\n\n> age is skewed right with a mean of 44 and median of 42 and a sd of 18.\n\n## Proficient quantitative\nOverlaid a density curve on the histogram, added a dashed line at the mean. Table of summary statistics present in a nicely formatted way, digits rounded appropriately. Plot cleaned up with appropriate axis and titles.  \n\n\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\nggviolin(clean$age, add = c(\"jitter\", \"boxplot\")) + \n  coord_flip() + labs(x=\"\", y=\"Age\")\n```\n\n::: {.cell-output-display}\n![](hw04-describing_distributions_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n\n```{.r .cell-code}\ngghistogram(clean$age, add_density = TRUE) + xlab(\"Age\")\n```\n\n::: {.cell-output-display}\n![](hw04-describing_distributions_files/figure-html/unnamed-chunk-5-2.png){width=672}\n:::\n:::\n\n\n>  The ages of respondents range from 18 to 89 years old, is bimodal with peaks around 25 and 55ish. The mean age is 44.4 with the median very close at 42.5 - confirming the lack of skew. The standard deviation is 18, and 50% of the reported ages lie between 28 and 59.  \n\n# Example - Part II\n\n\n::: {.cell}\n\n:::\n",
    "supporting": [
      "hw04-describing_distributions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}