{
  "hash": "7b9aa0f95045b1dd070e13f7a414e5af",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"HW 05: Describing Relationships\"\nsubtitle: \"Exploring Associations between two variables\"\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n\n# Purpose\n\nTo fully explore the relationship between two variables both summary statistics and visualizations are important. \n\n----\n\n# Instructions \n\nFor this assignment you will describe the relationship between these **four** specific combinations of data types: \n\n* Categorical response and categorical explanatory variable. (C ~ C)\n* Quantitative response and categorical explanatory variable. (Q ~ C)\n* Any combination of the above with a binary variable (B ~ C, C ~ B, or Q ~ B)\n* Quantitative response and quantitative explanatory variable. (Q ~ Q)\n\n\n## Before you start, \n\n1. Determine what variables you want to graph based on your research topic. \n    * You will need a mixture of categorical and quantitative variables for this assignment. \n    * You should use variables that are relevant to your research topic. \n    * If you have not yet identified both a quantitative (Q), a binary (B), and a categorical (C) variable that you are interested in, now is the time to go back to the codebook and figure this out. \n2. Recode variables as needed. \n    * If your response variable is categorical with many levels, you may want to collapse it down to fewer than 5 levels. \n\nIf you do not already have a binary (B) variable in your clean data you can either a) go back and edit your `dm` file to include a binary varible, or b) dichotomize one of your categorical (C) varibles into two levels. (Make a new variable, don't overwrite your categorical variable).   \n\n\n\n## For each bivariate relationship under consideration you will do the following: \n\n1. Name and explain the two variables under consideration. \n\n2. Create the appropriate graphic for bivariate relationship under consideration. For these plots binary variables are treated as categorical variables with only 2 levels. \n    * C ~ C: Side by side barplot\n    * Q ~ C: Paneled histogram with density overlaid, or a grouped boxplot with overlaid violin plot. \n    * Q ~ Q: Scatterplot. Add both lowess and linear trend lines.\n\n3. Calculate appropriate grouped summary statistics\n    * For continuous outcomes you'll want to describe measures including the sample size, mean, median, range and variance for each level of the categorical variable. \n    * For categorical outcomes you'll want to calculate %'s of your outcome measurement across levels of your covariate. \n        - i.e. proportion of males who are smokers compared to proportion of females who are smokers\n        - or proportion of smokers who are male, compared to proportion of non-smokers who are male. \n\n4. Explain the relationship or trends you see in the data in a summary paragraph. Put this paragraph below the graphic. \n    * Use summary statistics in your text explanation. \n    * Use specific features of the graphic in your text explanation.\n        - i.e. are there outliers only in one group?\n        - Do the data seem clumped or clustered in one region of the scatterplot? \n        - Is there a linear or non-linear pattern? \n        - Does one combination of categorical levels (C~C) seem to hold most the data? \n        - Are there any outlying data points? Don't list off each one, just state if there is and where approximately it's at. \n\n----\n\n# Submission instructions\n\n\n* Use the template provided: [[QMD]](_templates/hw05_describing_relationships_template.qmd)\n  - Right click and 'save as', put this in your `scripts` folder\n* Upload your final PDF to Canvas by the due date. \n\n\n----\n\n## Example\n\nIn these examples I use a combination of `ggplot2` and `sjPlot` for plotting, `dplyr` for data management and to create summary statistics, `knitr` to create nice tables, `gridExtra` to put plots side by side. You do not need to report this information in your assignment. This is for your knowledge only. I also explain what I'm doing in code here for you to learn. you do not need to explain your own code. \n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2); library(dplyr); library(knitr); \nlibrary(scales); library(gridExtra); library(sjPlot)\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n\n### C ~ C Association\nFor this example I am using the `NC Births` data set, data on 1000 births in 2004 from North Carolina. \nThis example explores the association between the smoking status of the mother (`habit`) and whether or not the baby was born prematurely (`premie`). \n\n\n::: {.cell}\n\n:::\n\n\nFrequency tables to get counts, and _row_ percents because I specifically want to compare the percent of premie babies within the smoking and non-smoking groups. \n\n::: {.cell}\n\n```{.r .cell-code}\nnc %>% select(habit, premie) %>% table() %>% addmargins %>% kable()\n```\n\n::: {.cell-output-display}\n\n\n|          | full term| premie| Sum|\n|:---------|---------:|------:|---:|\n|nonsmoker |       739|    133| 872|\n|smoker    |       107|     19| 126|\n|Sum       |       846|    152| 998|\n\n\n:::\n\n```{.r .cell-code}\nnc %>% select(habit, premie) %>% table() %>% prop.table(margin=1) %>% kable(digits=3)\n```\n\n::: {.cell-output-display}\n\n\n|          | full term| premie|\n|:---------|---------:|------:|\n|nonsmoker |     0.847|  0.153|\n|smoker    |     0.849|  0.151|\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_xtab(x=nc$habit, grp=nc$premie, show.total=FALSE, margin='row')\n```\n\n::: {.cell-output-display}\n![](hw05-describing_relationships_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nContrary to what I was expecting, there is equal proportion of prematurely born babies to non-smokers (133/739, 15.2%) compared to babies born to smokers (19/107, 15.1%). There is no association between the smoking status of the mother and the likelihood of the baby being born prematurely. \n\n\n\n### Q ~ C Association\n\nThis example explores the association between the length of an iris petal and the species of iris. The quantitative response variable is petal length (`Petal.Length`) and the categorical explanatory variable is species (`Species`). \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\niris %>% group_by(Species) %>% \n         summarise(mean=mean(Petal.Length), \n                   sd=sd(Petal.Length), \n                   n=n()) %>% \n         kable(digits=2)\n```\n\n::: {.cell-output-display}\n\n\n|Species    | mean|   sd|  n|\n|:----------|----:|----:|--:|\n|setosa     | 1.46| 0.17| 50|\n|versicolor | 4.26| 0.47| 50|\n|virginica  | 5.55| 0.55| 50|\n\n\n:::\n\n```{.r .cell-code}\nggplot(iris, aes(x=Species, y=Petal.Length, fill=Species)) + \n  geom_boxplot(width=.4) + geom_violin(alpha=.3) + \n  stat_summary(fun.y=\"mean\", geom=\"point\", size=3, pch=17, \n    position=position_dodge(width=0.75)) + theme_bw()\n```\n\n::: {.cell-output-display}\n![](hw05-describing_relationships_files/figure-html/unnamed-chunk-5-1.png){fig-align='center' width=480}\n:::\n:::\n\n\nThere are 50 iris plants within each species. There is clear difference in the average Petal length across the pecies. _Setosa_ has the smallest average petal length of 1.46 cm and the smallest variation with a standard deviation of 0.17cm.  _Veriscolor_ has an average petal length of 4.26cm with SD of 0.47cm, and _Virginica_ has the largest average petal length of 5.55cm and the largest variation with a standard deviation of 0.55cm.  \n\n### Q ~ Q Association\n\nThis example explores the association between length of an iris petal and the length of the sepal. The quantitative response variable is petal length (`Petal.Length`) and the quantitative explanatory variable is sepal length (`Sepal.Length`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(iris$Petal.Length, iris$Sepal.Length) # calculate the correlation\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8717538\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(iris, aes(x=Sepal.Length, y=Petal.Length)) + geom_point() + \n  geom_smooth(se=FALSE, col=\"brown\") + geom_smooth(se=FALSE, method=\"lm\")\n```\n\n::: {.cell-output-display}\n![](hw05-describing_relationships_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nThere is a positive association between sepal and petal length of an iris. The correlation coefficient is 0.87, but the form of the data may not be linear. There is a cluster of values below 2cm petal length which are separated away from the rest of the data. It is hard to assess the linearity of this relationship due to the separate clusters. \n\n\n\n\n    ",
    "supporting": [
      "hw05-describing_relationships_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}