{
  "hash": "dd7d1b67a172fe2757ff539495da3981",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Simple Linear Regression Modeling\"\ndate: \"2025-10-22\"\ndescription: \"lec08\"\nfooter: \"[🔗 https://math615.netlify.app](https://math615.netlify.app)\"\nfrom: markdown+emoji\nformat: \n  revealjs:\n    theme: sky\n    transition: fade\n    slide-number: true\n    incremental: false \n    chalkboard: true\nexecute:\n  freeze: auto\n  echo: true\n  message: false\n  warning: false\nknitr:\n  opts_chunk: \n    R.options:\n      width: 200\neditor: \n  markdown: \n    wrap: 72\n---\n\n# Purpose & Estimation\n\n\n::: {.cell}\n\n:::\n\n\n## Purpose of Regression Modeling {.smaller}\n\n* Learn more about the relationship between several independent or predictor variables and a **quantitative** dependent (response) variable. \n* Regression is widely used in research as it allows us to ask  the general question \"_what is the best predictor of_...\", and does “_additional variable A_” or “_additional variable B confound the relationship between my explanatory and response variable?_” \n\nBoth Regression and Correlation can be used to \n\n* **Descriptive**: Draw inferences regarding the relationship \n* **Predictive**: Predict the value of $Y$ for given values of one or more $X$'s.\n\n\n## Examples in practice\n\n* Educational researchers might want to learn about the best predictors of success in high-school. \n* Sociologists may want to find out which of the multiple social indicators best predict whether or not a new immigrant group will adapt to their new country of residence. \n* Biologists may want to find out which factors (i.e. temperature, barometric pressure, humidity, etc.) best predict caterpillar reproduction.\n\n## Example - Lung function {.smaller}\n\n::: {.callout-tip appearance=minimal}\nLung function data were obtained from an epidemiological study of households living in four areas with different amounts and types of air pollution. The data set used in PMA6 is a subset of the total data. In this example we use only the data taken on the fathers, all of whom are nonsmokers. \n:::\n\nOne of the major early indicators of reduced respiratory function is FEV1 or forced expiratory volume in the first second (amount of air exhaled in 1 second). Since it is known that taller males tend to have higher FEV1, we wish to determine the relationship between height and FEV1. We can use regression analysis for both a descriptive and predictive purpose. \n\n* **Descriptive**: Describing the relationship between FEV1 and height\n* **Predictive**: Determine the expected or normal FEV1 for a given height\n\n\n## Visualize the relationship {.smaller}\n\n:::: {.columns}\n\n::: {.column width=\"40%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(fev, aes(y=FFEV1, x=FHEIGHT)) + \n  geom_point() + geom_smooth(se=FALSE, col=\"blue\") + \n  geom_smooth(se=FALSE, method = \"lm\", col=\"red\") + \n      xlab(\"Height\") + ylab(\"FEV1\") + \n      ggtitle(\"Scatterplot and Regression line of FEV1 \\n Versus Height for Males.\") + theme_bw() \n```\n\n::: {.cell-output-display}\n![](lec08-slr_files/figure-revealjs/unnamed-chunk-2-1.png){width=384}\n:::\n:::\n\n\n:::\n\n::: {.column width=\"60%\"}\n\n\\\nThere does appear to be a tendency for taller men to have higher FEV1. Since this relationship is reasonably linear (the blue loess line is similar to the red linear line) we can write the model the population average FEV $\\mu_{y}$ as a linear function of height $x$:\n\n$$\n  \\mu_{y} = \\beta_{0} + \\beta_{1}x\n$$\n\nThe intercept parameter, $\\beta_{0}$, represents where the line crosses the y-axis when $x=0$. The slope parameter, $\\beta_{1}$, represents the change in $\\mu_{y}$ per 1 unit $x$.\n:::\n\n::::\n\n\n## Unifying model framework {.smaller}\n\nWe know that there is always random noise in real data (DATA = MODEL FIT + RESIDUAL) so we introduce a random error term, $\\epsilon_{i}$ and assume the model:\n\n$$\ny_{i} = \\beta_{0} + \\beta_{1} X + \\epsilon_{i} \\\\\n\\epsilon_{i} \\sim N(0, \\sigma^{2})\n$$\n\nThis model states that the random variable $y$ to be made up of a predictable part (a linear function of $x$) and an unpredictable part (the random error, $\\epsilon_{i}$). The error (residual) term includes the effects of all other factors, known or unknown.\n\n\n## Least Squares Estimation {.smaller}\n\n* Most common method of fitting a straight line to two variables. \n* Also known as \"Ordinary Least Squares (OLS)\"\n* Calculates sample statistics $b_{0}$ and $b_{1}$ to estimate the population parameter values $\\beta_{0}$ and $\\beta_{1}$\n* The estimated mean function is $\\hat{y}_{i} = b_{0} + b_{1}x_{i}$\n* The _fitted value_, $\\hat{y}_{i}$, is the estimated value for point $i$, calculated by plugging in a value for $x_{i}$ and calculating the result.  \n* The _residual_ is the difference between the observed and the fitted value: $\\epsilon_{i} = y_{i}-\\hat{y}_{i}$\n\n## Least Squares Estimation {.smaller}\n\nThe estimates $b_{0}$ and $b_{1}$ are found such that they minimize the sum of the squared residuals (the unexplained residual error)\n\n$$ \\sum_{i=1}^{n} \\epsilon_{i} $$\n\nFor simple linear regression the regression coefficient estimates that minimize the sum of squared errors can be calculated as: \n\n$$ \\hat{\\beta_{0}} = \\bar{y} - \\hat{\\beta_{1}}\\bar{x} \\quad \\mbox{  and  } \\quad  \\hat{\\beta_{1}} = r\\frac{s_{y}}{s_{x}} $$\n\nwhere $r$ is the correlation coefficient between $x$ and $y$.\n\n\n# Partitioning the Variance\n\n## Revisiting the Sum of Squares {.smaller}\n\nGo to: [https://paternogbc.shinyapps.io/SS_regression/](https://paternogbc.shinyapps.io/SS_regression/). Then turn and talk to your group about the following features of the **Sum of Squares Graphs**\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n**Total**\n\n* What are the dots? \n* What does the horizontal line represent? \n* What do the blue lines represent?\n:::\n\n::: {.column width=\"50%\"}\n**Regression**\n\n* What does the horizontal line represent? \n* What does the sloped line represent? \n* What are the green lines? \n\n**Error**\n\n* What are the dots? \n* What does the sloped line represent? \n* What do the red lines represent? \n:::\n\n::::\n \n## Sum of Squares - Regression \n\n* SS Total- how far are the points away from $\\bar{y}$?\n* SS Regression - how far away is the regression line from $\\bar{y}$?\n* SS Error - how far are the points away from the estimated regression line? \n\nLooking at it this way, we are asking \"If I know the value of $x$, how much better will I be at predicting $y$ than if I were just to use $\\bar{y}$? \n\n\n# Fitting the model\n\n## Least Squares Estimation - in R\n\nA linear model using least squares estimation can be performed in R using the function `lm(y ~ x)`\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nfev.model <- lm(FFEV1 ~ FHEIGHT, data = fev)\nfev.model\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = FFEV1 ~ FHEIGHT, data = fev)\n\nCoefficients:\n(Intercept)      FHEIGHT  \n    -4.0867       0.1181  \n```\n\n\n:::\n:::\n\n\nThe regression equation for the model to explain FEV1 using height as a predictor is:  \n$$ \\hat{y} = -4.087 + 0.118x $$\n\n## Using this model\n\n$$ \\hat{y} = -4.087 + 0.118x $$\n\n* $b_{0}$: For a father that is 0 cm tall, the predicted FEV is -4.087 (an impossible result)\n* $b_{1}$: For every additional cm taller a father is, his predicted FEV increases by 0.118L. \n* $\\hat{y}_{x=70}$: A father who is 70cm tall has a predicted FEV1 of $-4.087 + 0.118(70) = 4.17L$\n\n## Other facts about LS regression {.smaller}\n\n* A change of one sd in $x$ corresponds to a change of $r$ sd in $y$ since $b_{1}=r\\frac{s_{y}}{s_{x}}$.\n* If the correlation is 0, the slope of the LS line is 0. A test of $\\beta_{1}=0$ is equivalent to a test of $\\rho=0$.\n* The LS line always passes through the point $(\\bar{x}, \\bar{y})$.\n* The distinction between explanatory and response variables is essential in regression. Reversing $x$ and $y$ results in a different regression line.\n* The Root Mean Squared Error (RMSE) is an estimate for $\\sigma$. \n\n\n# Assumptions\n\n## Mathematical Model {.smaller}\n\nThe mathematical model that we use for regression has these features that translate into assumptions.\n\n:::: {.columns}\n\n::: {.column width=\"40%\"}\n$$\n\\begin{align}\n  Y|X & \\sim N(\\mu_{Y|X}, \\sigma^{2}) \\\\\n  \\mu_{Y|X} & = \\beta_{0} + \\beta_{1} X \\\\\n   \\sigma^{2} & = Var(Y|X)\n\\end{align} \n$$\n\n![Figure 6.2](images/slr_graph.png)\n\n:::\n\n::: {.column width=\"60%\"}\n::: {.incremental}\n\n* **Independence** The observations are the result of a simple random sample and thus are independent from each other\n* **Linearity**: The mean of $Y$ values at any given $X$ follows a straight line\n* **Normality**: $Y$ values are normally distributed at any given $X$ \n* **Homoscedasticity** The variance of $Y$ values at any $X$ is $\\sigma^2$ (same for all X)\n* The last two assumptions are checked by examining the **residuals**, and so can only be checked after the model has been fit. \n:::\n:::\n\n::::\n\n## Assumption - Independence\n\n* Knowledge of the method of data collection here is key! \n* If the sampling method is not random, observations may not be independent. \n* No real good way to \"test\" for independence. Need to know how the sample was obtained. \n* Non simple random sample will not result in the same variance estimates\n* Can use hierarchical/multi-level models for clustered samples\n  \n\n## Assumption - Linearity \n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec08-slr_files/figure-revealjs/unnamed-chunk-4-1.png){width=288}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n* Slight departures OK\n* Can use transformations of strongly skewed data to achieve it\n* The lowess trend line reasonably follows a linear pattern.\n:::\n\n::::\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nggplot(fev, aes(y=FFEV1, x=FHEIGHT)) + \n  geom_point() + \n  geom_smooth(col=\"blue\", se=FALSE) + \n  geom_smooth(method = \"lm\", col=\"red\", se=FALSE) + \n  theme_minimal()\n```\n:::\n\n\n## Assumption - Normality {.smaller}\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec08-slr_files/figure-revealjs/unnamed-chunk-6-1.png){width=384}\n:::\n\n::: {.cell-output-display}\n![](lec08-slr_files/figure-revealjs/unnamed-chunk-6-2.png){width=384}\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n* Slight departures OK\n* Can use transformations to achieve it\n\nThese plots are generated from the `performance` package. \n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nplot(check_normality(fev.model), type=\"density\")\nplot(check_normality(fev.model), type=\"qq\")\n```\n:::\n\n\n* The residuals follow a normal distribution well. \n* Don't let the pattern of the residuals on the qqplot fool you, the y-axis is very zoomed in.\n:::\n\n::::\n\n## Assumption - Homoscedasticity {.smaller}\n\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(check_heteroskedasticity(fev.model))\n```\n\n::: {.cell-output-display}\n![](lec08-slr_files/figure-revealjs/unnamed-chunk-8-1.png){width=384}\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n* If the variance (std. residual) changes with the value of $\\hat{y}$, that is a sign of non-constant variance. \n* Violations result in reduced validity of inference and typically larger standard errors for the coefficients. \n* Could be caused by outliers or model mis-specificiation (e.g. non-normal data)\n* FEV Example - even though there is a slight increase in the trend of fitted values against the residuals, this is within the tolerance range. \n:::\n\n::::\n\n## Out of range predictions\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\\\n\n![Figure 6.2](images/slr_graph.png)\n:::\n\n::: {.column width=\"50%\"}\n::: {.callout-caution}\n### Caution!\n\nThe linear model is only valid within the range of the data used to fit the model \n\nTo take an extreme example, suppose a father was 2 feet tall. Then the equation would predict an impossible negative value of FEV1 ($-1.255$). \n\nA safe policy is to restrict the use of the equation to the range of the $X$ observed in the sample.\n\n:::\n:::\n\n::::\n\n## Model-check {.smaller}\n\n::: columns\n::: {.column width=\"60%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(check_predictions(fev.model))\n```\n\n::: {.cell-output-display}\n![](lec08-slr_files/figure-revealjs/unnamed-chunk-9-1.png){width=960}\n:::\n:::\n\n:::\n\n::: {.column width=\"40%\"}\nAnother way of assessing model fit is to check the distribution of the predictions created by this model. A good fitting model should predict values that are similar to the observed data used to fit the model. \n\n:::\n:::\n\n\n\n# Inference\n\n## Distribution of parameter estimates {.smaller}\n\n* The estimated coefficients are functions of both $x$ and $y$, and they are not themselves independent of each other (e.g. $Cov(b_{0}, b_{1}) \\neq 0)$. \n* The joint vector $\\hat{\\beta}(y, x)= (b_{0}, b_{1})$ has a multivariate normal distribution, with variance that depends on the predictor variables $x$ only. \n\n$$\n\\hat{\\beta}(y, x) \\sim \\mathcal{N}(\\beta, \\mathbf{x^{T}x}^{-1}\\sigma^{2})\n$$\n\n* The normality of the vector $\\hat{\\beta}$ is quite robust to the model assumptions. \n* Even if the residuals are not normally distributed, the CLT ensures that the $\\hat{\\beta}$ are close to normal \n* When sample sizes are low in a category, or $Var(X)$ is close to zero, $x^{T}x$ can't be inverted - leading to errors of \"non positive definite\"\n\n## Calculating Confidence Intervals {.smaller}\n\n$$ b_{p} \\pm 1.96*SE(b_{p})$$ \n\n> point estimate $\\pm$ critical value * standard error of estimate\n\nBut calculating the variance of $b_{p}$ involves $\\mathbf{x^{T}x}^{-1}\\sigma^{2}$, which is outside the scope of this class. So, we use R functions\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nconfint(fev.model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  2.5 %     97.5 %\n(Intercept) -6.36315502 -1.8102499\nFHEIGHT      0.08526328  0.1509472\n```\n\n\n:::\n:::\n\n\nWe can be 95% confident that the true slope parameter between a fathers height and his FEV1 is contained in the interval (0.085, 0.151). \n\n\n## Hypotheis Testing {.smaller}\n\nLet $\\beta_1$ be the true slope parameter that describes the change in FEV1 as a function of height in cm.\n\n-  $H_{0}: \\beta_{1}=0$ There is no linear relationship between FEV1 and Height\n-  $H_{A}: \\beta_{1} \\neq 0$ Alternate Hypothesis: There is a linear relationship between FEV1 and Height\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbroom::tidy(fev.model) |> kable(digits=3) #kable is in the knitr package\n```\n\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |   -4.087|     1.152|    -3.548|   0.001|\n|FHEIGHT     |    0.118|     0.017|     7.106|   0.000|\n\n\n:::\n:::\n\n\nThe p-value for $b_{1}$ is \\<.0001, so there is sufficient evidence to believe that there is a linear relationship between FEV1 and Height of fathers. \n\n##  Write a conclusion {.smaller}\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n**Base R (ish)**\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nfev.model |> coefficients() \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)     FHEIGHT \n -4.0867025   0.1181052 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\nfev.model |> confint()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  2.5 %     97.5 %\n(Intercept) -6.36315502 -1.8102499\nFHEIGHT      0.08526328  0.1509472\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\nfev.model |> r2() # from the performance package\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# R2 for Linear Regression\n       R2: 0.254\n  adj. R2: 0.249\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n**gtsummary package**\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\ntbl_regression(fev.model) %>% \n  add_glance_table(include = c(nobs, r.squared))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"tdiyibgnmb\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#tdiyibgnmb table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#tdiyibgnmb thead, #tdiyibgnmb tbody, #tdiyibgnmb tfoot, #tdiyibgnmb tr, #tdiyibgnmb td, #tdiyibgnmb th {\n  border-style: none;\n}\n\n#tdiyibgnmb p {\n  margin: 0;\n  padding: 0;\n}\n\n#tdiyibgnmb .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#tdiyibgnmb .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#tdiyibgnmb .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#tdiyibgnmb .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#tdiyibgnmb .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tdiyibgnmb .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tdiyibgnmb .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tdiyibgnmb .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#tdiyibgnmb .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#tdiyibgnmb .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#tdiyibgnmb .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#tdiyibgnmb .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#tdiyibgnmb .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#tdiyibgnmb .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#tdiyibgnmb .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#tdiyibgnmb .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#tdiyibgnmb .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#tdiyibgnmb .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#tdiyibgnmb .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tdiyibgnmb .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#tdiyibgnmb .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#tdiyibgnmb .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#tdiyibgnmb .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tdiyibgnmb .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#tdiyibgnmb .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#tdiyibgnmb .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tdiyibgnmb .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tdiyibgnmb .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#tdiyibgnmb .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tdiyibgnmb .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#tdiyibgnmb .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tdiyibgnmb .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tdiyibgnmb .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tdiyibgnmb .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tdiyibgnmb .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tdiyibgnmb .gt_left {\n  text-align: left;\n}\n\n#tdiyibgnmb .gt_center {\n  text-align: center;\n}\n\n#tdiyibgnmb .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#tdiyibgnmb .gt_font_normal {\n  font-weight: normal;\n}\n\n#tdiyibgnmb .gt_font_bold {\n  font-weight: bold;\n}\n\n#tdiyibgnmb .gt_font_italic {\n  font-style: italic;\n}\n\n#tdiyibgnmb .gt_super {\n  font-size: 65%;\n}\n\n#tdiyibgnmb .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#tdiyibgnmb .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#tdiyibgnmb .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#tdiyibgnmb .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#tdiyibgnmb .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#tdiyibgnmb .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#tdiyibgnmb .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#tdiyibgnmb .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#tdiyibgnmb div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"KipCZXRhKio=\"><span class='gt_from_md'><strong>Beta</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">FHEIGHT</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.12</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.09, 0.15</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: #D3D3D3;\">No. Obs.</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: #D3D3D3;\">150</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: #D3D3D3;\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: #D3D3D3;\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">R²</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.254</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"4\"><span data-qmd-base64=\"QWJicmV2aWF0aW9uOiBDSSA9IENvbmZpZGVuY2UgSW50ZXJ2YWw=\"><span class='gt_from_md'>Abbreviation: CI = Confidence Interval</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n:::\n\n::::\n\n**Conclusion**\n \nEach 1cm increase in height of a father is associated with a significant increase of 0.118 (0.09, 0.15) L of FEV1  (p\\<.0001). Height explains 25.4% of the variation in FEV1. \n\n\n",
    "supporting": [
      "lec08-slr_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}